"use client";

import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useState} from "react";
import {api} from "../../../../lib/api";

type Member={id:string;agent:string;agent_name:string;role:string;priority:number;can_delegate:boolean;enabled:boolean};
type Team={id:string;name:string;objective:string;kind:string;director:string;director_name:string;active:boolean;members:Member[];max_cost_rub_per_run:string};
type Run={id:string;state:string};

const kindLabel:Record<string,string>={generic:"Универсальная",marketing:"Маркетинг",content:"Контент",sales:"Продажи",development:"Разработка"};

export default function AgentTeamsPage(){
 const router=useRouter();const[teams,setTeams]=useState<Team[]>([]);const[description,setDescription]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const load=async()=>{try{setTeams(await api<Team[]>("/agent-teams/"));setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить команды")}};
 useEffect(()=>{void load()},[]);
 const create=async()=>{if(description.trim().length<12){setError("Опишите команду чуть подробнее");return}setBusy("create");setError("");setNotice("");try{const team=await api<Team>("/agent-teams/from-description/",{method:"POST",body:JSON.stringify({description:description.trim()})});setDescription("");setTeams(current=>[team,...current]);setNotice(`Команда «${team.name}» создана. Роли уже распределены.`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать команду")}finally{setBusy("")}};
 const run=async(team:Team)=>{setBusy(`run:${team.id}`);setError("");try{const started=await api<Run>(`/agent-teams/${team.id}/run/`,{method:"POST",body:JSON.stringify({objective:team.objective})});router.push(`/app/runs/${started.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось запустить команду")}finally{setBusy("")}};
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"32px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:28}}><div><Link href="/app/agents" style={{textDecoration:"none",opacity:.65}}>← Agent Studio</Link><h1 style={{fontSize:38,margin:"10px 0 8px"}}>Команды AI-сотрудников</h1><p style={{maxWidth:760,opacity:.7,fontSize:17}}>Опишите отдел обычными словами. Система создаст руководителя, распределит роли и подготовит команду к работе.</p></div><Link href="/app/dev" style={{textDecoration:"none",padding:"10px 13px",border:"1px solid #ddd",borderRadius:11}}>Dev Studio</Link></header>
  {notice&&<div style={{padding:12,border:"1px solid #7da78a",borderRadius:11,marginBottom:14}}>{notice}</div>}{error&&<div style={{padding:12,border:"1px solid #c96d74",borderRadius:11,marginBottom:14}}>{error}</div>}
  <section style={{border:"1px solid #ddd",borderRadius:20,padding:22,marginBottom:30}}><div style={{fontSize:12,opacity:.5,textTransform:"uppercase"}}>Создать отдел</div><h2 style={{margin:"7px 0"}}>Что должна делать команда?</h2><p style={{opacity:.66}}>Например: «Нужна маркетинговая команда: директор, SMM, копирайтер и аналитик. Каждый день готовить контент, перед публикацией спрашивать подтверждение».</p><textarea rows={6} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Опишите цель отдела, роли можно не перечислять — система предложит их сама" style={{width:"100%",boxSizing:"border-box",padding:14,border:"1px solid #ccc",borderRadius:13,resize:"vertical",font:"inherit"}}/><div style={{display:"flex",justifyContent:"flex-end",marginTop:11}}><button disabled={!!busy||description.trim().length<12} onClick={()=>void create()} style={{padding:"11px 16px",border:0,borderRadius:10,fontWeight:700}}>{busy==="create"?"Собираем команду…":"Создать команду"}</button></div></section>
  <section><h2>Мои команды</h2>{teams.length?<div style={{display:"grid",gap:13}}>{teams.map(team=><article key={team.id} style={{border:"1px solid #ddd",borderRadius:18,padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start"}}><div style={{minWidth:0}}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:21}}>{team.name}</strong><span style={{fontSize:12,border:"1px solid #ddd",borderRadius:999,padding:"4px 8px"}}>{kindLabel[team.kind]||team.kind}</span><span style={{fontSize:12,opacity:.6}}>{team.active?"● Работает":"○ Пауза"}</span></div><p style={{opacity:.7,margin:"7px 0 10px"}}>{team.objective}</p><div style={{fontSize:13,opacity:.65,marginBottom:8}}>Руководитель: <strong>{team.director_name}</strong></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{team.members.map(member=><span key={member.id} style={{fontSize:12,padding:"5px 8px",border:"1px solid #ddd",borderRadius:999}}>{member.role}</span>)}</div><div style={{fontSize:12,opacity:.55,marginTop:10}}>Лимит на запуск: {Number(team.max_cost_rub_per_run||0).toFixed(2)} ₽</div></div><button disabled={!!busy||!team.active} onClick={()=>void run(team)} style={{padding:"10px 14px",border:0,borderRadius:10,fontWeight:700,whiteSpace:"nowrap"}}>{busy===`run:${team.id}`?"Запускаем…":"Запустить команду"}</button></div></article>)}</div>:<div style={{border:"1px dashed #bbb",borderRadius:16,padding:30,textAlign:"center",opacity:.7}}>Команд пока нет. Опишите первый отдел выше.</div>}</section>
 </main>;
}
