"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";
import styles from "../admin.module.css";

type Model={id:string;slug:string;enabled:boolean;current_version:string|null};
type Provider={id:string;slug:string;name:string;enabled:boolean;emergency_disabled:boolean;health_state:string;last_latency_ms:number|null;models:Model[]};
type ActivePrice={id:string;model:string;currency:string;input_price_per_million:string|null;output_price_per_million:string|null;input_rub_per_million:string;output_rub_per_million:string;markup_percent:string;effective_from:string};
type MarkupRule={id:string;scope_type:string;scope_key:string;markup_percent:string|null;price_multiplier:string;effective_from:string};
type Pricing={margin_policy:{minimum_gross_margin_percent:string;anomaly_cost_deviation_percent:string}|null;active_prices:ActivePrice[];markup_rules:MarkupRule[];open_anomalies:{id:string;kind:string;severity:string;model:string;provider:string;expected_rub:string|null;actual_rub:string|null;created_at:string}[]};

const healthLabel:Record<string,string>={healthy:"Работает",unknown:"Не проверен",degraded:"Нестабилен",open:"Автоматически отключён",disabled:"Отключён"};
const severityLabel:Record<string,string>={info:"Информация",warning:"Предупреждение",critical:"Критическая"};
const scopeLabel:Record<string,string>={global:"Все запросы",provider:"Провайдер",model:"Модель",operation:"Тип операции",organization:"Организация",contract:"Договор"};
const operationOptions=[
 {value:"chat",label:"Обычный чат"},
 {value:"compare",label:"Сравнение моделей"},
 {value:"compare_synthesis",label:"Итог Compare"},
 {value:"image",label:"Изображения"},
 {value:"b2b_api",label:"B2B API"},
];

export default function ProvidersAdmin(){
 const[providers,setProviders]=useState<Provider[]>([]);
 const[pricing,setPricing]=useState<Pricing|null>(null);
 const[error,setError]=useState("");
 const[notice,setNotice]=useState("");
 const[busy,setBusy]=useState("");
 const[markupScope,setMarkupScope]=useState("global");
 const modelOptions=useMemo(()=>providers.flatMap(provider=>provider.models.map(model=>({slug:model.slug,label:`${provider.name} · ${model.slug}`}))),[providers]);
 const load=async()=>{try{const[p,r]=await Promise.all([api<Provider[]>("/admin/providers/"),api<Pricing>("/admin/pricing/")]);setProviders(p);setPricing(r);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить конфигурацию");}};
 useEffect(()=>{void load();},[]);
 const bulk=async(target:"providers"|"models",action:string,ids:string[])=>{setBusy(`${target}:${ids.join(",")}`);setError("");setNotice("");try{await api("/admin/providers/bulk-action/",{method:"POST",body:JSON.stringify({target,action,ids})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Операция не выполнена");}finally{setBusy("");}};
 const health=async(slug:string)=>{setBusy(slug);setError("");try{await api(`/admin/commercial-setup/providers/${slug}/health/`,{method:"POST",body:"{}"});}catch(reason){setError(reason instanceof Error?reason.message:"Проверка провайдера завершилась ошибкой");}finally{await load();setBusy("");}};
 const addPrice=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setBusy("price");setError("");setNotice("");try{await api("/admin/pricing/",{method:"POST",body:JSON.stringify({model:data.get("model"),input_rub_per_million:data.get("input"),output_rub_per_million:data.get("output"),markup_percent:data.get("base_markup"),effective_from:data.get("effective")||""})});form.reset();setNotice("Новая версия себестоимости создана. Старые версии сохранены для воспроизводимости прошлых списаний.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось создать версию цены");}finally{setBusy("");}};
 const addMarkup=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setBusy("markup");setError("");setNotice("");try{await api("/admin/pricing/",{method:"POST",body:JSON.stringify({kind:"markup_rule",scope_type:markupScope,scope_key:markupScope==="global"?"":data.get("scope_key"),markup_percent:data.get("markup"),price_multiplier:data.get("multiplier"),effective_from:data.get("effective")||"",reason:data.get("reason")})});form.reset();setNotice("Новое правило наценки создано. Оно будет применяться к новым запросам с указанной даты.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось создать правило наценки");}finally{setBusy("");}};
 const ruleKeyInput=markupScope==="provider"?<select name="scope_key" required defaultValue=""><option value="" disabled>Выберите провайдера</option>{providers.map(item=><option key={item.slug} value={item.slug}>{item.name} · {item.slug}</option>)}</select>:markupScope==="model"?<select name="scope_key" required defaultValue=""><option value="" disabled>Выберите модель</option>{modelOptions.map(item=><option key={item.slug} value={item.slug}>{item.label}</option>)}</select>:markupScope==="operation"?<select name="scope_key" required defaultValue=""><option value="" disabled>Выберите операцию</option>{operationOptions.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select>:null;
 return <>
  <header className={styles.header}><div><h1>Провайдеры и цены</h1><p>Доступность моделей, состояние провайдеров, аварийное отключение и фактическая экономика.</p></div><button className={styles.button} onClick={()=>void load()}>Обновить</button></header>
  {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={`${styles.notice} ${styles.error}`}>{error}</div>}
  <section className={styles.section}><h2>Провайдеры</h2><table className={styles.table}><thead><tr><th>Провайдер</th><th>Состояние</th><th>Задержка</th><th>Модели</th><th>Управление</th></tr></thead><tbody>{providers.map(provider=><tr key={provider.id}><td><b>{provider.name}</b><br/><small>{provider.slug} · {provider.enabled?"включён":"выключен"}{provider.emergency_disabled?" · аварийно отключён":""}</small></td><td className={provider.health_state==="healthy"?styles.good:styles.warn}>{healthLabel[provider.health_state]||provider.health_state}</td><td>{provider.last_latency_ms==null?"—":`${provider.last_latency_ms} мс`}</td><td>{provider.models.map(model=><div key={model.id} style={{marginBottom:6}}><span className={styles.pill}>{model.slug} · {model.current_version??"версия не назначена"}</span> <button className={styles.button} disabled={!!busy} onClick={()=>void bulk("models",model.enabled?"disable":"enable",[model.id])}>{model.enabled?"Выключить":"Включить"}</button></div>)}</td><td><div className={styles.actions}><button className={styles.button} disabled={!!busy} onClick={()=>void health(provider.slug)}>Проверить связь</button><button className={styles.button} disabled={!!busy} onClick={()=>void bulk("providers",provider.enabled?"disable":"enable",[provider.id])}>{provider.enabled?"Выключить":"Включить"}</button><button className={`${styles.button} ${provider.emergency_disabled?styles.primary:styles.danger}`} disabled={!!busy} onClick={()=>void bulk("providers",provider.emergency_disabled?"emergency_enable":"emergency_disable",[provider.id])}>{provider.emergency_disabled?"Снять аварийное отключение":"Аварийно отключить"}</button></div></td></tr>)}</tbody></table></section>
  {pricing&&<>
   <section className={styles.grid}><div className={styles.card}><small>Минимальная маржа</small><strong>{pricing.margin_policy?.minimum_gross_margin_percent??"—"}%</strong></div><div className={styles.card}><small>Порог аномалии себестоимости</small><strong>{pricing.margin_policy?.anomaly_cost_deviation_percent??"—"}%</strong></div><div className={styles.card}><small>Версии себестоимости</small><strong>{pricing.active_prices.length}</strong></div><div className={styles.card}><small>Открытые ценовые аномалии</small><strong className={pricing.open_anomalies.length?styles.warn:styles.good}>{pricing.open_anomalies.length}</strong></div></section>
   <section className={styles.section}><h2>Новая версия себестоимости</h2><p>Здесь фиксируется стоимость провайдера. Пользовательская цена определяется отдельными правилами наценки ниже. Поле базовой наценки используется только как fallback, если ни одного действующего правила нет.</p><form className={styles.filters} onSubmit={addPrice}><select name="model" required defaultValue=""><option value="" disabled>Выберите модель</option>{modelOptions.map(item=><option key={item.slug} value={item.slug}>{item.label}</option>)}</select><input name="input" type="number" min="0.0001" step="0.0001" placeholder="Вход ₽ / 1 млн" required/><input name="output" type="number" min="0.0001" step="0.0001" placeholder="Выход ₽ / 1 млн" required/><input name="base_markup" type="number" min="0" step="0.01" defaultValue="100" title="Fallback-наценка, если нет правил"/><input name="effective" type="datetime-local" title="Пусто = действует сразу"/><button className={`${styles.button} ${styles.primary}`} disabled={!!busy}>Создать версию</button></form></section>
   <section className={styles.section}><h2>Новое правило наценки</h2><p>Правила версионируются и не меняют историю. Более узкая область переопределяет процент более общей, а множители применяются последовательно.</p><form className={styles.filters} onSubmit={addMarkup}><select value={markupScope} onChange={e=>setMarkupScope(e.target.value)}><option value="global">Все запросы</option><option value="provider">Провайдер</option><option value="model">Модель</option><option value="operation">Тип операции</option></select>{ruleKeyInput}<input name="markup" type="number" min="0" step="0.001" placeholder="Наценка %" required/><input name="multiplier" type="number" min="0.0001" step="0.0001" defaultValue="1" placeholder="Множитель" required/><input name="effective" type="datetime-local" title="Пусто = действует сразу"/><input name="reason" maxLength={300} placeholder="Причина изменения"/><button className={`${styles.button} ${styles.primary}`} disabled={!!busy}>Создать правило</button></form></section>
   <section className={styles.section}><h2>Действующие правила наценки</h2><table className={styles.table}><thead><tr><th>Область</th><th>Ключ</th><th>Наценка</th><th>Множитель</th><th>Действует с</th></tr></thead><tbody>{pricing.markup_rules.map(item=><tr key={item.id}><td>{scopeLabel[item.scope_type]??item.scope_type}</td><td>{item.scope_key||"Все"}</td><td>{item.markup_percent==null?"Не переопределяет":`${item.markup_percent}%`}</td><td>×{item.price_multiplier}</td><td>{new Date(item.effective_from).toLocaleString("ru-RU")}</td></tr>)}</tbody></table></section>
   <section className={styles.section}><h2>Версии себестоимости</h2><table className={styles.table}><thead><tr><th>Модель</th><th>Вход</th><th>Выход</th><th>Fallback-наценка</th><th>Действует с</th></tr></thead><tbody>{pricing.active_prices.map(item=><tr key={item.id}><td>{item.model}</td><td>{item.input_rub_per_million} ₽ / 1 млн</td><td>{item.output_rub_per_million} ₽ / 1 млн</td><td>{item.markup_percent}%</td><td>{new Date(item.effective_from).toLocaleString("ru-RU")}</td></tr>)}</tbody></table></section>
   {pricing.open_anomalies.length>0&&<section className={styles.section}><h2>Аномалии стоимости</h2><table className={styles.table}><thead><tr><th>Важность</th><th>Провайдер / модель</th><th>Тип</th><th>Ожидалось → фактически</th></tr></thead><tbody>{pricing.open_anomalies.map(item=><tr key={item.id}><td>{severityLabel[item.severity]||item.severity}</td><td>{item.provider}/{item.model}</td><td>{item.kind}</td><td>{item.expected_rub??"—"} → {item.actual_rub??"—"}</td></tr>)}</tbody></table></section>}
  </>}
 </>;
}
