"use client";

import {useEffect,useState} from "react";
import {api} from "../../../lib/api";
import styles from "../admin.module.css";

type Model={id:string;slug:string;enabled:boolean;current_version:string|null};
type Provider={id:string;slug:string;name:string;enabled:boolean;emergency_disabled:boolean;health_state:string;last_latency_ms:number|null;models:Model[]};
type ApiKey={id:string;label:string;masked:string;enabled:boolean;priority:number;health_state:string;last_error_code:string;last_latency_ms:number|null;balance_supported:boolean;balance_amount:string|null;balance_currency:string;balance_checked_at:string|null;last_checked_at:string|null};
type Credential={slug:string;name:string;adapter_type:string;api_base_url:string;credential_configured:boolean;credential_source:string;health_state:string;last_checked_at:string|null;last_latency_ms:number|null;keys:ApiKey[]};
type Price={input_rub_per_million:string;output_rub_per_million:string;example_1k_input_rub:string;example_1k_output_rub:string};
type DiscoveredModel={id:string;display_name:string;purpose:string;selected:boolean;price:Price|null};
type Discovery={provider:string;models:DiscoveredModel[]};
type Activation={provider:string;provider_enabled:boolean;activated:{id:string;slug:string;upstream_model:string}[];blocked:{model:string;reasons:string[]}[]};
type LedgerKey={id:string;provider:string;provider_name:string;label:string;masked:string;enabled:boolean;health_state:string;provider_balance_amount:string|null;provider_balance_currency:string;provider_balance_supported:boolean;account_id:string|null;account_currency:string|null;ledger_available_native:string|null;ledger_spent_native:string|null;is_default:boolean};
type LedgerData={keys:LedgerKey[]};

const healthLabel:Record<string,string>={healthy:"Работает",unknown:"Не проверен",degraded:"Ошибка",open:"Временно отключён",disabled:"Отключён"};
const fmt=(v:string|number|null|undefined,d=4)=>Number(v??0).toFixed(d).replace(".",",");

export default function ProvidersAdmin(){
 const[providers,setProviders]=useState<Provider[]>([]);
 const[credentials,setCredentials]=useState<Record<string,Credential>>({});
 const[ledgerKeys,setLedgerKeys]=useState<Record<string,LedgerKey>>({});
 const[keyDraft,setKeyDraft]=useState<Record<string,string>>({});
 const[labelDraft,setLabelDraft]=useState<Record<string,string>>({});
 const[models,setModels]=useState<Record<string,DiscoveredModel[]>>({});
 const[selected,setSelected]=useState<Record<string,Set<string>>>({});
 const[busy,setBusy]=useState("");
 const[error,setError]=useState("");
 const[notice,setNotice]=useState("");

 const load=async()=>{try{const p=await api<Provider[]>("/admin/providers/");const [configs,ledger]=await Promise.all([Promise.all(p.map(item=>api<Credential>(`/admin/providers/${item.slug}/credentials/`))),api<LedgerData>("/admin/procurement/ledger/")]);setProviders(p);setCredentials(Object.fromEntries(configs.map(item=>[item.slug,item])));setLedgerKeys(Object.fromEntries((ledger.keys||[]).map(item=>[item.id,item])));setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить AI-провайдеров");}};
 useEffect(()=>{void load();},[]);

 const addKey=async(slug:string)=>{const value=(keyDraft[slug]||"").trim();if(!value){setError("Вставьте API-ключ");return;}setBusy(`add:${slug}`);setError("");setNotice("");try{const result=await api<ApiKey>(`/admin/providers/${slug}/keys/`,{method:"POST",body:JSON.stringify({api_key:value,label:(labelDraft[slug]||"").trim()})});setKeyDraft(v=>({...v,[slug]:""}));setLabelDraft(v=>({...v,[slug]:""}));setNotice(result.health_state==="healthy"?"Ключ добавлен и проверен — подключение работает.":`Ключ сохранён, но проверка вернула ${result.last_error_code||"ошибку"}.`);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось добавить API-ключ");}finally{setBusy("");}};
 const keyAction=async(slug:string,key:ApiKey,action:"recheck"|"balance"|"toggle"|"delete")=>{setBusy(`${action}:${key.id}`);setError("");setNotice("");try{if(action==="delete"){if(!window.confirm(`Удалить ${key.label}?`))return;await api(`/admin/providers/${slug}/keys/${key.id}/`,{method:"DELETE"});}else if(action==="recheck"||action==="balance"){const result=await api<ApiKey>(`/admin/providers/${slug}/keys/${key.id}/`,{method:"PATCH",body:JSON.stringify({recheck:true})});if(action==="balance"){const ledger=ledgerKeys[key.id];if(result.balance_supported&&result.balance_amount!=null){setNotice(`${key.label}: баланс провайдера ${result.balance_amount} ${result.balance_currency}.`);}else if(ledger?.ledger_available_native!=null){setNotice(`${key.label}: OpenAI не отдаёт prepaid balance через project key. Наш учётный остаток: ${fmt(ledger.ledger_available_native)} ${ledger.account_currency||""}; уже израсходовано ${fmt(ledger.ledger_spent_native)} ${ledger.account_currency||""}.`);}else{setNotice(`${key.label}: провайдер не отдаёт баланс через этот ключ. Оформите закупку в «Экономика и закупки API», после этого здесь появится наш учётный остаток.`);}}}else{await api(`/admin/providers/${slug}/keys/${key.id}/`,{method:"PATCH",body:JSON.stringify({enabled:!key.enabled})});}await load();}catch(reason){setError(reason instanceof Error?reason.message:"Операция с ключом не выполнена")}finally{setBusy("");}};
 const discover=async(slug:string)=>{setBusy(`discover:${slug}`);setError("");setNotice("");try{const result=await api<Discovery>(`/admin/providers/${slug}/discover-models/`);setModels(current=>({...current,[slug]:result.models}));setSelected(current=>({...current,[slug]:new Set(result.models.filter(x=>x.selected).map(x=>x.id))}));if(!result.models.length)setNotice("Провайдер не вернул доступных моделей для этого ключа.");}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось получить модели");}finally{setBusy("");}};
 const toggleModelChoice=(slug:string,id:string)=>setSelected(current=>{const next=new Set(current[slug]||[]);next.has(id)?next.delete(id):next.add(id);return {...current,[slug]:next};});
 const saveModels=async(slug:string)=>{const ids=[...(selected[slug]||new Set<string>())];if(!ids.length){setError("Выберите хотя бы одну модель");return;}setBusy(`models:${slug}`);setError("");setNotice("");try{await api(`/admin/providers/${slug}/discover-models/`,{method:"POST",body:JSON.stringify({model_ids:ids})});const activation=await api<Activation>(`/admin/providers/${slug}/activate-models/`,{method:"POST",body:JSON.stringify({model_ids:ids})});if(activation.blocked.length){const details=activation.blocked.map(item=>`${item.model}: ${item.reasons.join(", ")}`).join("; ");setNotice(`Для клиентов включено моделей: ${activation.activated.length}. Не включены: ${details}`);}else{setNotice(`Готово. ${activation.activated.length} моделей подключены и доступны в клиентском чате.`);}await load();await discover(slug);}catch(reason){setError(reason instanceof Error?reason.message:"Модель сохранена, но не удалось сделать её доступной клиентам. Проверьте официальный прайс и маржу в разделе «Экономика AI».");}finally{setBusy("");}};
 const toggleProvider=async(provider:Provider)=>{setBusy(`provider:${provider.id}`);setError("");try{await api("/admin/providers/bulk-action/",{method:"POST",body:JSON.stringify({target:"providers",action:provider.enabled?"disable":"enable",ids:[provider.id]})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось изменить состояние провайдера");}finally{setBusy("");}};
 const priceText=(price:Price|null)=>price?`${price.input_rub_per_million} ₽ вход / ${price.output_rub_per_million} ₽ выход за 1 млн токенов`:"Точная стоимость ещё не синхронизирована";
 const providerBalanceText=(key:ApiKey)=>key.balance_supported&&key.balance_amount!=null?`${key.balance_amount} ${key.balance_currency}`:"не предоставляется";
 const ledgerBalanceText=(key:ApiKey)=>{const ledger=ledgerKeys[key.id];return ledger?.ledger_available_native!=null?`${fmt(ledger.ledger_available_native)} ${ledger.account_currency||""}`:"не заведён";};

 return <>
  <header className={styles.header}><div><h1>AI-провайдеры</h1><p>Ключи, их работоспособность и реальный закупочный остаток по внутреннему учёту.</p></div><button className={styles.button} disabled={!!busy} onClick={()=>void load()}>Обновить</button></header>
  {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={`${styles.notice} ${styles.error}`}>{error}</div>}
  <div className={styles.notice}><b>Баланс:</b> «Баланс провайдера» показывается только когда сам API его отдаёт. Для OpenAI project key такой остаток официально не предоставляется, поэтому рядом показывается <b>наш закупочный остаток</b>: закуплено − списано − зарезервировано. Оформить закупку можно в разделе «Экономика и закупки API».</div>
  {providers.map(provider=>{
   const credential=credentials[provider.slug];const keys=credential?.keys||[];const discovered=models[provider.slug]||[];const healthyKeys=keys.filter(k=>k.enabled&&k.health_state==="healthy").length;
   const ledgerTotals=keys.reduce<Record<string,number>>((acc,k)=>{const l=ledgerKeys[k.id];if(l?.ledger_available_native!=null&&l.account_currency){acc[l.account_currency]=(acc[l.account_currency]||0)+Number(l.ledger_available_native);}return acc;},{});
   const totalLedger=Object.entries(ledgerTotals).map(([currency,amount])=>`${fmt(amount)} ${currency}`).join(" + ");
   return <section className={styles.section} key={provider.id}>
    <div className={styles.header}><div><h2>{provider.name}</h2><p>{healthyKeys?`Рабочих ключей: ${healthyKeys} из ${keys.length}`:keys.length?"Нет рабочего ключа":"Ключи ещё не добавлены"}</p></div><div className={styles.actions}><strong className={provider.health_state==="healthy"?styles.good:styles.warn}>{healthLabel[provider.health_state]||provider.health_state}</strong><button className={styles.button} disabled={!!busy} onClick={()=>void toggleProvider(provider)}>{provider.enabled?"Выключить":"Включить"}</button></div></div>
    <section className={styles.grid}><div className={styles.card}><small>Подключено ключей</small><strong>{keys.length}</strong></div><div className={styles.card}><small>Рабочих ключей</small><strong>{healthyKeys}</strong></div><div className={styles.card}><small>Наш закупочный остаток</small><strong>{totalLedger||"—"}</strong><small>по оформленным закупкам этого провайдера</small></div></section>
    <h3>API-ключи</h3>
    <div className={styles.filters}><input value={labelDraft[provider.slug]||""} onChange={e=>setLabelDraft(v=>({...v,[provider.slug]:e.target.value}))} placeholder="Название, например Основной"/><input type="password" autoComplete="off" value={keyDraft[provider.slug]||""} onChange={e=>setKeyDraft(v=>({...v,[provider.slug]:e.target.value}))} placeholder="Вставьте API-ключ"/><button className={`${styles.button} ${styles.primary}`} disabled={!!busy} onClick={()=>void addKey(provider.slug)}>{busy===`add:${provider.slug}`?"Проверяем…":"Подключить ключ"}</button></div>
    {keys.length>0&&<table className={styles.table}><thead><tr><th>Ключ</th><th>Статус</th><th>Наш остаток</th><th>Баланс провайдера</th><th>Задержка</th><th></th></tr></thead><tbody>{keys.map(key=>{const ledger=ledgerKeys[key.id];return <tr key={key.id}><td><b>{key.label}</b><br/><small>{key.masked}</small>{ledger?.is_default&&<><br/><span className={styles.good}>основной закупочный</span></>}</td><td className={key.health_state==="healthy"?styles.good:styles.warn}>{healthLabel[key.health_state]||key.health_state}{key.last_error_code&&<><br/><small>{key.last_error_code}</small></>}</td><td><b>{ledgerBalanceText(key)}</b>{ledger?.ledger_spent_native!=null&&<><br/><small>израсходовано: {fmt(ledger.ledger_spent_native)} {ledger.account_currency}</small></>}{!ledger?.account_id&&<><br/><small>закупка ещё не оформлена</small></>}</td><td><b>{providerBalanceText(key)}</b>{key.balance_checked_at&&<><br/><small>Проверено: {new Date(key.balance_checked_at).toLocaleString("ru-RU")}</small></>}</td><td>{key.last_latency_ms!=null?`${key.last_latency_ms} мс`:"—"}</td><td><div className={styles.actions}><button className={`${styles.button} ${styles.primary}`} disabled={!!busy} onClick={()=>void keyAction(provider.slug,key,"balance")}>{busy===`balance:${key.id}`?"Проверяем…":"Обновить баланс"}</button><button className={styles.button} disabled={!!busy} onClick={()=>void keyAction(provider.slug,key,"recheck")}>{busy===`recheck:${key.id}`?"Проверяем…":"Проверить API"}</button><button className={styles.button} disabled={!!busy} onClick={()=>void keyAction(provider.slug,key,"toggle")}>{key.enabled?"Выключить":"Включить"}</button><button className={`${styles.button} ${styles.danger}`} disabled={!!busy} onClick={()=>void keyAction(provider.slug,key,"delete")}>Удалить</button></div></td></tr>})}</tbody></table>}
    <div className={styles.actions} style={{marginTop:16}}><button className={`${styles.button} ${styles.primary}`} disabled={!!busy||(!healthyKeys&&!credential?.credential_configured)} onClick={()=>void discover(provider.slug)}>{busy===`discover:${provider.slug}`?"Получаем модели…":"Показать доступные модели"}</button></div>
    {discovered.length>0&&<><h3>Доступные модели</h3><p>Список получен непосредственно у {provider.name}. Выбранная модель попадёт клиентам только после проверки рабочей цены и минимальной маржи.</p><table className={styles.table}><thead><tr><th></th><th>Модель</th><th>Для чего лучше</th><th>Стоимость расхода</th></tr></thead><tbody>{discovered.map(model=><tr key={model.id}><td><input type="checkbox" checked={selected[provider.slug]?.has(model.id)||false} onChange={()=>toggleModelChoice(provider.slug,model.id)}/></td><td><b>{model.display_name}</b><br/><small>{model.id}</small>{model.selected&&<><br/><span className={styles.good}>добавлена в каталог</span></>}</td><td>{model.purpose}</td><td>{priceText(model.price)}{model.price&&<><br/><small>1000 токенов: вход {model.price.example_1k_input_rub} ₽, выход {model.price.example_1k_output_rub} ₽</small></>}</td></tr>)}</tbody></table><div className={styles.actions}><button className={`${styles.button} ${styles.primary}`} disabled={!!busy} onClick={()=>void saveModels(provider.slug)}>{busy===`models:${provider.slug}`?"Подключаем…":"Подключить выбранные модели клиентам"}</button></div></>}
   </section>;
  })}
 </>;
}
