"use client";

import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";
import type {Project} from "../../../lib/types";

type Binding={id:string;repository_id:number;full_name:string;default_branch:string;private:boolean;write_enabled:boolean;last_synced_at:string|null};
type BoundProject={project:Project;binding:Binding};
type GitHubHealth={healthy:boolean;read_ok:boolean;write_ready:boolean;write_enabled:boolean;contents_permission:string;repository:string;default_branch:string;root_items:number;checked_at:string;error:string};
type TeamMember={id:string;role:string;enabled:boolean};
type Team={id:string;project:string|null;name:string;objective:string;kind:string;active:boolean;max_cost_rub_per_run:string;members:TeamMember[]};
type Run={id:string;team:string|null;state:string;objective:string;created_at:string};

const stateLabel:Record<string,string>={queued:"В очереди",planning:"Планирует",running:"Разрабатывает",waiting_tool:"Ждёт инструмент",waiting_approval:"Ждёт решения",reviewing:"Проверяет",completed:"Готово",failed:"Ошибка",canceled:"Остановлен",budget_exceeded:"Лимит бюджета"};

export default function DevStudioV2(){
 const router=useRouter();
 const[projects,setProjects]=useState<BoundProject[]>([]);const[selectedProject,setSelectedProject]=useState("");const[health,setHealth]=useState<GitHubHealth|null>(null);const[healthLoading,setHealthLoading]=useState(false);const[teams,setTeams]=useState<Team[]>([]);const[runs,setRuns]=useState<Run[]>([]);const[objective,setObjective]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 const devTeams=useMemo(()=>teams.filter(team=>team.kind==="development"),[teams]);
 const runByTeam=useMemo(()=>{const map=new Map<string,Run>();for(const run of runs){if(run.team&&!map.has(run.team))map.set(run.team,run)}return map},[runs]);
 const projectName=useMemo(()=>Object.fromEntries(projects.map(item=>[item.project.id,item.project.name])),[projects]);
 const selected=projects.find(item=>item.project.id===selectedProject)??null;
 const load=async()=>{setLoading(true);try{const[projectRows,teamRows,runRows]=await Promise.all([api<Project[]>("/projects/"),api<Team[]>("/agent-teams/"),api<Run[]>("/agent-runs/")]);setTeams(teamRows);setRuns(runRows);const owned=projectRows.filter(item=>item.role==="owner"&&!item.archived_at);const checked=await Promise.all(owned.map(async project=>{try{return {project,binding:await api<Binding>(`/projects/${project.id}/github/`)};}catch{return null}}));const bound=checked.filter((item):item is BoundProject=>Boolean(item));setProjects(bound);setSelectedProject(current=>current||bound[0]?.project.id||"");setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить Dev Studio")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{let active=true;if(!selectedProject){setHealth(null);return()=>{active=false}};setHealthLoading(true);void api<GitHubHealth>(`/projects/${selectedProject}/github/health/`).then(value=>{if(active)setHealth(value)}).catch(e=>{if(active)setHealth({healthy:false,read_ok:false,write_ready:false,write_enabled:false,contents_permission:"unknown",repository:"",default_branch:"",root_items:0,checked_at:new Date().toISOString(),error:e instanceof Error?e.message:"Не удалось проверить подключение"})}).finally(()=>{if(active)setHealthLoading(false)});return()=>{active=false}},[selectedProject]);
 useEffect(()=>{if(!runs.some(run=>["queued","planning","running","reviewing","waiting_tool"].includes(run.state)))return;const timer=window.setInterval(()=>void api<Run[]>("/agent-runs/").then(setRuns).catch(()=>undefined),5000);return()=>window.clearInterval(timer)},[runs]);
 const create=async()=>{if(!selectedProject){setError("Сначала выберите проект с подключённым GitHub");return}if(!health?.write_ready){setError("Подключение проекта не готово для безопасной записи. Откройте настройки проекта и проверьте GitHub.");return}if(objective.trim().length<12){setError("Опишите, что нужно разработать или исправить");return}setBusy(true);setError("");try{const team=await api<Team>("/agent-teams/bootstrap-dev/",{method:"POST",body:JSON.stringify({objective:objective.trim(),project:selectedProject})});router.push(`/app/dev/${team.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать проект разработки")}finally{setBusy(false)}};
 const connectionText=!selected?"Подключите GitHub к проекту":healthLoading?"Проверяем подключение…":health?.write_ready?"Готово к работе":health?.read_ok?"Можно читать код, но нельзя безопасно записывать изменения":"Подключение требует настройки";
 return <main className="studioPage devStudioSimple">
  <header className="studioHero"><div><span className="studioEyebrow">DEV STUDIO</span><h1>Опишите задачу — AI-команда подготовит изменения</h1><p>Выберите проект и сформулируйте результат обычными словами. Архитектор, разработчик и проверка качества работают внутри одной задачи.</p></div><div className="studioHeroActions"><Link href="/app/runs">Запуски</Link><Link href="/app/projects">Проекты</Link></div></header>
  {error&&<div className="studioAlert error">{error}</div>}
  <section className="devStartGrid"><div className="studioCreateCard"><div className="studioCreateIntro"><div><span>Новая задача</span><h2>Что нужно сделать?</h2></div></div>{projects.length?<label className="studioField"><span>Проект</span><select value={selectedProject} onChange={e=>setSelectedProject(e.target.value)}>{projects.map(item=><option key={item.project.id} value={item.project.id}>{item.project.name}</option>)}</select></label>:<div className="studioSetup"><b>Сначала подключите проект</b><span>Dev Studio работает с GitHub-репозиторием проекта и создаёт изменения безопасно в рабочем контуре.</span><Link href="/app/projects">Подключить проект →</Link></div>}<textarea className="studioPrompt" rows={6} value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Например: найди причину падения личного кабинета, исправь критические ошибки, добавь проверки и подготовь безопасное обновление."/><div className="studioCreateFooter"><span>Перед запуском система проверит доступ, модели и среду. Изменения не отправляются в основной код без безопасного процесса.</span><button className="studioPrimary" onClick={()=>void create()} disabled={busy||healthLoading||!health?.write_ready||objective.trim().length<12}>{busy?"Создаём…":"Создать задачу разработки"}</button></div></div>
   <aside className={`studioConnection ${health&&!health.write_ready?"warning":""}`}><span className="studioEyebrow">ПОДКЛЮЧЕНИЕ</span><h3>{connectionText}</h3>{selected&&<><b>{selected.project.name}</b><p>{selected.binding.full_name}</p>{!health?.write_ready&&<Link href="/app/projects">Исправить подключение →</Link>}<details><summary>Технические детали</summary><dl><div><dt>Чтение</dt><dd>{health?.read_ok?"OK":"Нет"}</dd></div><div><dt>Запись</dt><dd>{health?.write_ready?"OK":"Не готова"}</dd></div><div><dt>Ветка</dt><dd>{selected.binding.default_branch}</dd></div>{health?.error&&<div><dt>Ошибка</dt><dd>{health.error}</dd></div>}</dl></details></>}</aside>
  </section>
  <section className="studioSection"><div className="studioSectionHead"><div><h2>Проекты разработки</h2><p>Продолжайте существующую работу без повторной настройки команды.</p></div></div>{loading?<div className="studioEmpty">Загружаем проекты…</div>:devTeams.length?<div className="studioCards">{devTeams.map(team=>{const last=runByTeam.get(team.id);return <Link href={`/app/dev/${team.id}`} className="studioCard" key={team.id}><div className="studioCardTop"><span className="studioStatus active">{last?stateLabel[last.state]||last.state:"Готов"}</span><small>{projectName[team.project||""]||"Проект"}</small></div><h3>{team.name}</h3><p>{team.objective}</p><div className="studioRoleRow">{team.members.filter(item=>item.enabled).slice(0,4).map(item=><span key={item.id}>{item.role}</span>)}</div><span className="studioOpen">Открыть →</span></Link>})}</div>:<div className="studioEmpty">Пока нет задач разработки. Создайте первую выше.</div>}</section>
 </main>;
}
