"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {api} from "../../../lib/api";

type Installation={id:string;account_login?:string;account_type?:string};
type TeamMember={id:string;agent:string;agent_name:string;role:string;priority:number;can_delegate:boolean;enabled:boolean};
type Team={id:string;name:string;objective:string;director:string;director_name:string;active:boolean;members:TeamMember[]};
type Run={id:string;state:string;objective:string;cost_actual_rub:string;step_count:number;created_at:string};

const stateLabel:Record<string,string>={queued:"В очереди",planning:"Планирование",running:"Выполняется",waiting_tool:"Ожидает инструмент",waiting_approval:"Нужно подтверждение",reviewing:"Проверка",completed:"Готово",failed:"Ошибка",canceled:"Отменён",budget_exceeded:"Лимит бюджета"};

export default function DevStudioPage(){
 const[installations,setInstallations]=useState<Installation[]>([]);const[teams,setTeams]=useState<Team[]>([]);const[runs,setRuns]=useState<Run[]>([]);const[objective,setObjective]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const load=async()=>{const results=await Promise.allSettled([api<Installation[]>("/github/installations/"),api<Team[]>("/agent-teams/"),api<Run[]>("/agent-runs/")]);if(results[0].status==="fulfilled")setInstallations(results[0].value);if(results[1].status==="fulfilled")setTeams(results[1].value);if(results[2].status==="fulfilled")setRuns(results[2].value);if(results[1].status==="rejected")setError(results[1].reason instanceof Error?results[1].reason.message:"Не удалось загрузить Dev Studio")};
 useEffect(()=>{void load()},[]);
 const createTeam=async()=>{if(!objective.trim()){setError("Опишите задачу разработки");return}setBusy("create");setError("");setNotice("");try{const team=await api<Team>("/agent-teams/bootstrap-dev/",{method:"POST",body:JSON.stringify({objective:objective.trim(),name:"Dev Team"})});setTeams(current=>[team,...current]);setNotice("Команда создана. Engineering Director, Architect, Software Engineer и QA & Security готовы к работе.");setObjective("")}catch(e){setError(e instanceof Error?e.message:"Не удалось создать команду")}finally{setBusy("")}};
 const runTeam=async(team:Team)=>{setBusy(`run:${team.id}`);setError("");setNotice("");try{await api(`/agent-teams/${team.id}/run/`,{method:"POST",body:JSON.stringify({objective:team.objective})});setNotice("Задача поставлена Engineering Director в очередь.");await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось запустить команду")}finally{setBusy("")}};
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"32px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:34}}><div><div style={{fontSize:13,opacity:.6,marginBottom:8}}>AI WORKSPACE · DEV STUDIO</div><h1 style={{fontSize:38,margin:"0 0 10px"}}>AI-команда разработки</h1><p style={{maxWidth:760,opacity:.72,fontSize:17}}>Отдельная среда для сложных проектов. Engineering Director управляет архитектором, разработчиком и QA/Security. GitHub и выполнение кода подключаются как инструменты, а не как часть обычного чата.</p></div><Link href="/app" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>← В чат</Link></header>
  {notice&&<div style={{padding:13,border:"1px solid #7aa78b",borderRadius:12,marginBottom:16}}>{notice}</div>}{error&&<div style={{padding:13,border:"1px solid #cb747a",borderRadius:12,marginBottom:16}}>{error}</div>}
  <section style={{display:"grid",gridTemplateColumns:"minmax(0,1.25fr) minmax(280px,.75fr)",gap:18,marginBottom:30}}><div style={{border:"1px solid #ddd",borderRadius:20,padding:22}}><div style={{fontSize:12,opacity:.55,textTransform:"uppercase"}}>Новый Dev-проект</div><h2 style={{margin:"8px 0 10px"}}>Опишите результат, который должна получить команда</h2><textarea rows={7} value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Например: проведи аудит репозитория, найди причины ошибок, исправь критические баги, добавь тесты и подготовь безопасный релиз..." style={{width:"100%",boxSizing:"border-box",padding:14,border:"1px solid #ccc",borderRadius:13,resize:"vertical",font:"inherit"}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginTop:12}}><span style={{fontSize:13,opacity:.6}}>Команда создаётся отдельно от обычных чатов.</span><button disabled={!!busy||!objective.trim()} onClick={()=>void createTeam()} style={{padding:"11px 16px",border:0,borderRadius:11,fontWeight:700,cursor:"pointer"}}>{busy==="create"?"Создаём…":"Создать AI-команду"}</button></div></div><aside style={{border:"1px solid #ddd",borderRadius:20,padding:22}}><div style={{fontSize:12,opacity:.55,textTransform:"uppercase"}}>GitHub</div><h3 style={{fontSize:21,margin:"8px 0"}}>{installations.length?"Подключён":"Нужно подключение"}</h3>{installations.length?<><p style={{opacity:.68}}>Найдено установок: {installations.length}. Следующий спринт связывает конкретный repository binding с Dev Team и sandbox.</p>{installations.slice(0,3).map(item=><div key={item.id} style={{padding:"9px 0",borderTop:"1px solid #eee"}}>{item.account_login||"GitHub installation"}</div>)}</>:<><p style={{opacity:.68}}>Dev Studio использует существующее GitHub App-подключение AI Workspace.</p><Link href="/app/settings" style={{display:"inline-block",padding:"10px 13px",border:"1px solid #ddd",borderRadius:10,textDecoration:"none"}}>Подключить GitHub</Link></>}</aside></section>
  <section style={{marginBottom:32}}><h2>Мои команды разработки</h2>{teams.length?<div style={{display:"grid",gap:12}}>{teams.map(team=><article key={team.id} style={{border:"1px solid #ddd",borderRadius:18,padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start"}}><div><strong style={{fontSize:21}}>{team.name}</strong><p style={{opacity:.7,margin:"6px 0 10px"}}>{team.objective}</p><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{team.members.map(member=><span key={member.id} style={{fontSize:12,border:"1px solid #ddd",borderRadius:999,padding:"5px 8px"}}>{member.role}</span>)}</div></div><button disabled={!!busy} onClick={()=>void runTeam(team)} style={{padding:"10px 14px",borderRadius:10,border:0,fontWeight:700,whiteSpace:"nowrap"}}>{busy===`run:${team.id}`?"Запуск…":"Запустить"}</button></div></article>)}</div>:<div style={{border:"1px dashed #bbb",borderRadius:16,padding:28,opacity:.7}}>Команд пока нет. Опишите задачу выше.</div>}</section>
  <section style={{marginBottom:32}}><h2>Последние запуски</h2>{runs.length?<div style={{display:"grid",gap:8}}>{runs.slice(0,10).map(run=><div key={run.id} style={{display:"grid",gridTemplateColumns:"140px 1fr auto",gap:12,padding:"11px 13px",border:"1px solid #ddd",borderRadius:12}}><strong>{stateLabel[run.state]||run.state}</strong><span style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{run.objective}</span><span style={{opacity:.6}}>{run.step_count} шагов</span></div>)}</div>:<p style={{opacity:.65}}>Запусков пока нет.</p>}</section>
  <section><h2>Контур команды</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}>{[["1","Engineering Director","Разбивает задачу, назначает работу и принимает результат."],["2","Architecture","Изучает репозиторий и риски до изменения кода."],["3","Development","Меняет код только в разрешённой рабочей среде."],["4","QA + Security","Проверяет тесты, регрессии и опасные изменения."],["5","Review / Release","Директор либо принимает результат, либо возвращает на доработку."]].map(([n,title,text])=><article key={n} style={{border:"1px solid #ddd",borderRadius:16,padding:17}}><div style={{fontSize:12,opacity:.45}}>ЭТАП {n}</div><strong style={{display:"block",fontSize:18,margin:"7px 0"}}>{title}</strong><span style={{opacity:.68}}>{text}</span></article>)}</div></section>
 </main>
}
