"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {api} from "../../../lib/api";

type Installation={id:string;account_login?:string;account_type?:string};

export default function DevStudioPage(){
 const[installations,setInstallations]=useState<Installation[]>([]);const[error,setError]=useState("");
 useEffect(()=>{api<Installation[]>("/github/installations/").then(setInstallations).catch(e=>setError(e instanceof Error?e.message:"GitHub пока не подключён"))},[]);
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"32px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:34}}><div><div style={{fontSize:13,opacity:.6,marginBottom:8}}>AI WORKSPACE · DEV STUDIO</div><h1 style={{fontSize:38,margin:"0 0 10px"}}>AI-команда разработки</h1><p style={{maxWidth:760,opacity:.72,fontSize:17}}>Подключите GitHub-проект. Engineering Director разложит задачу на архитектуру, backend, frontend, тесты и review. Код будет выполняться только в изолированной среде.</p></div><Link href="/app" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>← В чат</Link></header>
  <section style={{display:"grid",gridTemplateColumns:"minmax(0,1.25fr) minmax(280px,.75fr)",gap:18,marginBottom:30}}><div style={{border:"1px solid #ddd",borderRadius:20,padding:22}}><div style={{fontSize:12,opacity:.55,textTransform:"uppercase"}}>Новый проект</div><h2 style={{margin:"8px 0 10px"}}>Опишите, что нужно разработать</h2><textarea rows={7} placeholder="Например: проведи аудит репозитория, исправь критические баги, добавь биллинг и покрой основные сценарии тестами..." style={{width:"100%",boxSizing:"border-box",padding:14,border:"1px solid #ccc",borderRadius:13,resize:"vertical",font:"inherit"}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginTop:12}}><span style={{fontSize:13,opacity:.6}}>На следующем спринте здесь появится запуск Engineering Director.</span><button disabled style={{padding:"11px 16px",border:0,borderRadius:11,fontWeight:700}}>Создать план</button></div></div><aside style={{border:"1px solid #ddd",borderRadius:20,padding:22}}><div style={{fontSize:12,opacity:.55,textTransform:"uppercase"}}>GitHub</div><h3 style={{fontSize:21,margin:"8px 0"}}>{installations.length?"Подключён":"Нужно подключение"}</h3>{installations.length?<><p style={{opacity:.68}}>Найдено установок: {installations.length}. Репозитории будут выбираться для каждого Dev-проекта отдельно.</p>{installations.slice(0,3).map(item=><div key={item.id} style={{padding:"9px 0",borderTop:"1px solid #eee"}}>{item.account_login||"GitHub installation"}</div>)}</>:<><p style={{opacity:.68}}>Dev Studio использует существующее безопасное GitHub App-подключение AI Workspace.</p><Link href="/app/settings" style={{display:"inline-block",padding:"10px 13px",border:"1px solid #ddd",borderRadius:10,textDecoration:"none"}}>Подключить GitHub</Link></>}{error&&<p style={{fontSize:13,opacity:.6}}>{error}</p>}</aside></section>
  <section><h2>Как будет работать команда</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}>{[["1","Engineering Director","Понимает цель, строит roadmap и назначает работу."],["2","Architecture","Изучает репозиторий и зависимости до изменения кода."],["3","Developers","Backend и frontend работают по независимым задачам."],["4","QA + Security","Тесты, регрессии и проверка опасных изменений."],["5","Review","Директор принимает результат или возвращает на исправление."]].map(([n,title,text])=><article key={n} style={{border:"1px solid #ddd",borderRadius:16,padding:17}}><div style={{fontSize:12,opacity:.45}}>ЭТАП {n}</div><strong style={{display:"block",fontSize:18,margin:"7px 0"}}>{title}</strong><span style={{opacity:.68}}>{text}</span></article>)}</div></section>
 </main>
}
