"use client";

import Link from "next/link";
import {FormEvent,useState} from "react";
import {api,ensureCsrf} from "../../lib/api";
import styles from "../auth.module.css";

export default function RegisterPage(){
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [done,setDone]=useState(false);const [email,setEmail]=useState("");const [show,setShow]=useState(false);const [resent,setResent]=useState(false);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const address=String(f.get("email")||"").trim();try{await ensureCsrf();await api("/auth/register/",{method:"POST",body:JSON.stringify({username:f.get("username"),email:address,password:f.get("password"),accepted_terms:f.get("accepted_terms")==="on"})});setEmail(address);setDone(true);}catch(r){setError(r instanceof Error?r.message:"Не удалось создать аккаунт");}finally{setBusy(false);}};
  const resend=async()=>{if(!email)return;setBusy(true);try{await api("/auth/verify-email/request/",{method:"POST",body:JSON.stringify({email})});setResent(true);}catch{}finally{setBusy(false);}};
  if(done)return <main className={styles.page}><div className={styles.shell}><section className={`${styles.card} ${styles.success}`}><p className={styles.eyebrow}>АККАУНТ СОЗДАН</p><h1>Подтвердите email</h1><p className={styles.muted}>Мы отправили ссылку на <b>{email}</b>. После подтверждения можно переходить к первому запросу.</p>{resent&&<div className={styles.notice}>Письмо отправлено повторно.</div>}<div className={styles.actions}><button className={styles.primary} onClick={resend} disabled={busy}>{busy?"Отправляем…":"Отправить письмо ещё раз"}</button><Link className={styles.secondary} href="/app">Открыть AI Workspace</Link></div></section></div></main>;
  return <main className={styles.page}><div className={styles.shell}><div className={styles.brand}><Link href="/">AI Workspace</Link></div><section className={styles.card}><p className={styles.eyebrow}>НОВЫЙ АККАУНТ</p><h1>Начните работу с AI</h1><p className={styles.muted}>Один аккаунт для моделей, проектов, файлов, изображений и рублёвого баланса.</p><form className={styles.form} onSubmit={submit}><label>Логин<div className={styles.inputWrap}><input name="username" autoComplete="username" minLength={3} maxLength={150} required autoFocus/></div></label><label>Email<div className={styles.inputWrap}><input name="email" type="email" autoComplete="email" required/></div></label><label>Пароль<div className={styles.inputWrap}><input name="password" type={show?"text":"password"} minLength={8} autoComplete="new-password" required/><button className={styles.show} type="button" onClick={()=>setShow(v=>!v)}>{show?"Скрыть":"Показать"}</button></div></label><p className={styles.muted}>Используйте не менее 8 символов. В production применяются стандартные проверки надёжности Django.</p><label className={styles.check}><input name="accepted_terms" type="checkbox" required/><span>Я принимаю <Link href="/legal/offer" target="_blank">оферту</Link> и ознакомлен(а) с <Link href="/legal/privacy" target="_blank">политикой конфиденциальности</Link>.</span></label>{error&&<div className={styles.error} role="alert">{error}</div>}<button className={styles.primary} disabled={busy}>{busy?"Создаём аккаунт…":"Создать аккаунт"}</button></form><div className={styles.links}><Link href="/login">Уже есть аккаунт? Войти</Link></div></section></div></main>;
}
