# Generated by Django 5.2.5 on 2026-08-23 19:05

import apps.files.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "blob",
                    models.FileField(
                        max_length=500, upload_to=apps.files.models.isolated_upload_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("declared_content_type", models.CharField(blank=True, max_length=160)),
                ("detected_type", models.CharField(max_length=32)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Загружен"),
                            ("quarantine", "Проверяется"),
                            ("parsing", "Извлекается текст"),
                            ("ready", "Готов"),
                            ("partial", "Частично обработан"),
                            ("rejected", "Отклонён"),
                            ("failed", "Ошибка"),
                            ("deleting", "Удаляется"),
                            ("deleted", "Удалён"),
                        ],
                        default="uploaded",
                        max_length=16,
                    ),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("basic_passed", "Базовая проверка пройдена"),
                            ("rejected", "Отклонён"),
                        ],
                        max_length=32,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("extracted_chars", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("source_location", models.JSONField(blank=True, default=dict)),
                ("content", models.TextField()),
                ("untrusted_content", models.BooleanField(default=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="files.fileasset",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="FileProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Выполняется"),
                            ("completed", "Готово"),
                            ("partial", "Частично"),
                            ("failed", "Ошибка"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="files.fileasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="fileasset",
            index=models.Index(
                fields=["owner", "project", "status"], name="files_filea_owner_i_1be885_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.UniqueConstraint(
                fields=("owner", "idempotency_key"), name="unique_file_upload_idempotency"
            ),
        ),
        migrations.AddConstraint(
            model_name="filechunk",
            constraint=models.UniqueConstraint(
                fields=("file", "position"), name="unique_file_chunk_position"
            ),
        ),
    ]
