# Generated by Django 5.2.5 on 2026-08-25 18:39

import hashlib
import math
import re

import pgvector.django.vector
from django.db import migrations, models
from django.utils import timezone


WORD_RE = re.compile(r"[a-zа-яё0-9]{2,}", re.IGNORECASE)


def enable_vector(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


def backfill_chunks(apps, _schema_editor):
    FileChunk = apps.get_model("files", "FileChunk")
    blocked = re.compile(
        r"ignore\s+(?:all\s+)?(?:previous|system)|игнорируй\s+(?:предыдущие|системные)|"
        r"<\|(?:system|developer|assistant)\|>|(?:reveal|покажи).{0,48}(?:prompt|secret|token|секрет)",
        re.IGNORECASE | re.DOTALL,
    )
    for chunk in FileChunk.objects.select_related("file").iterator():
        vector = [0.0] * 384
        for token in WORD_RE.findall(chunk.content.casefold()):
            digest = hashlib.sha256(token.encode()).digest()
            vector[int.from_bytes(digest[:4], "big") % 384] += 1.0 if digest[4] & 1 else -1.0
        norm = math.sqrt(sum(value * value for value in vector))
        if norm:
            vector = [value / norm for value in vector]
        chunk.content_sha256 = hashlib.sha256(chunk.content.encode()).hexdigest()
        chunk.embedding = vector
        chunk.embedding_model = "local-hash-v1"
        chunk.acl_owner_id = chunk.file.owner_id
        chunk.acl_project_id = chunk.file.project_id
        chunk.injection_risk = "blocked" if blocked.search(chunk.content) else "safe"
        chunk.injection_signals = (
            ["legacy_prompt_injection"] if chunk.injection_risk == "blocked" else []
        )
        chunk.indexed_at = timezone.now()
        chunk.save(
            update_fields=[
                "content_sha256",
                "embedding",
                "embedding_model",
                "acl_owner_id",
                "acl_project_id",
                "injection_risk",
                "injection_signals",
                "indexed_at",
            ]
        )


def create_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "CREATE INDEX files_chunk_embedding_hnsw ON files_filechunk "
            "USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL"
        )


def drop_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP INDEX IF EXISTS files_chunk_embedding_hnsw")


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(enable_vector, migrations.RunPython.noop),
        migrations.AddField(
            model_name="filechunk",
            name="acl_owner_id",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="filechunk",
            name="acl_project_id",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="filechunk",
            name="content_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="filechunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name="filechunk",
            name="embedding_model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="filechunk",
            name="indexed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filechunk",
            name="injection_risk",
            field=models.CharField(
                choices=[
                    ("safe", "Безопасный"),
                    ("suspicious", "Подозрительный"),
                    ("blocked", "Заблокирован"),
                ],
                db_index=True,
                default="safe",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="filechunk",
            name="injection_signals",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="filechunk",
            index=models.Index(
                fields=["acl_project_id", "injection_risk"], name="filechunk_acl_risk_idx"
            ),
        ),
        migrations.RunPython(backfill_chunks, migrations.RunPython.noop),
        migrations.RunPython(create_hnsw_index, drop_hnsw_index),
    ]
