"use client";

import {useEffect,useRef,useState} from "react";
import type {Conversation} from "../../lib/types";
import {ConversationAssetsPanel} from "./ConversationAssetsPanel";
import {ErrorBoundary} from "./ErrorBoundary";
import {Icon} from "./Icons";
import {MessageCard} from "./MessageCard";

export function ChatThread({conversation,hasMore,loadingOlder,onLoadOlder,onConversation,onStarter}:{conversation:Conversation|null;hasMore:boolean;loadingOlder:boolean;onLoadOlder:()=>void;onConversation:(value:Conversation)=>void;onStarter:(value:string)=>void}){
 const ref=useRef<HTMLElement|null>(null);const[away,setAway]=useState(false);const previousCount=useRef(0);const pagingAnchor=useRef<{height:number;top:number}|null>(null);
 const messageCount=conversation?.messages.length??0;const lastMessage=messageCount?conversation!.messages[messageCount-1]:null;const lastContentLength=lastMessage?.content.length??0;
 useEffect(()=>{const el=ref.current;if(!el)return;if(pagingAnchor.current&&messageCount>previousCount.current){const anchor=pagingAnchor.current;pagingAnchor.current=null;requestAnimationFrame(()=>{el.scrollTop=anchor.top+(el.scrollHeight-anchor.height)});}else{const nearBottom=el.scrollHeight-el.scrollTop-el.clientHeight<160;if(messageCount>=previousCount.current&&nearBottom)requestAnimationFrame(()=>{el.scrollTop=el.scrollHeight});}previousCount.current=messageCount;},[messageCount,lastContentLength]);
 useEffect(()=>{const el=ref.current;if(el)requestAnimationFrame(()=>{el.scrollTop=el.scrollHeight});previousCount.current=conversation?.messages.length??0;pagingAnchor.current=null;},[conversation?.id]);
 const loadOlder=()=>{const el=ref.current;if(el)pagingAnchor.current={height:el.scrollHeight,top:el.scrollTop};onLoadOlder();};
 if(!conversation||conversation.messages.length===0)return <section className="emptyChat"><div className="emptyMark"><Icon name="spark" size={23}/></div><h1>Чем помочь сегодня?</h1><p className="emptySubhead">Опишите задачу своими словами. Сервис сам подберёт подходящую модель и постарается не расходовать лишние токены.</p><div className="starterGrid"><button onClick={()=>onStarter("Разбери документ и выдели главное. Сначала дай краткое резюме, затем ключевые выводы и риски.")}><span className="starterIcon"><Icon name="folder" size={16}/></span><span className="starterCopy"><b>Разобрать документ</b><small>Резюме, выводы и важные детали</small></span></button><button onClick={()=>onStarter("Помоги написать сильный текст. Сначала уточни цель и аудиторию, если это необходимо.")}><span className="starterIcon"><Icon name="pencil" size={16}/></span><span className="starterCopy"><b>Написать текст</b><small>Структура, редактура и финальная версия</small></span></button><button onClick={()=>onStarter("Помоги написать и проверить код. Найди ошибки, предложи решение и объясни важные изменения.")}><span className="starterIcon"><Icon name="zap" size={16}/></span><span className="starterCopy"><b>Помочь с кодом</b><small>Разработка, аудит и исправление ошибок</small></span></button><button onClick={()=>onStarter("Найди актуальную информацию в интернете, сравни источники и укажи ссылки на ключевые факты.")}><span className="starterIcon"><Icon name="search" size={16}/></span><span className="starterCopy"><b>Найти информацию</b><small>Актуальные данные с источниками</small></span></button></div></section>;
 return <section ref={ref} className="threadViewport" onScroll={e=>{const el=e.currentTarget;setAway(el.scrollHeight-el.scrollTop-el.clientHeight>260)}}><div className="threadInner"><ConversationAssetsPanel conversationId={conversation.id}/>{hasMore&&<button className="olderButton" disabled={loadingOlder} onClick={loadOlder}>{loadingOlder?"Загружаем…":"Показать более ранние сообщения"}</button>}{conversation.messages.map(message=><ErrorBoundary key={message.id}><MessageCard conversationId={conversation.id} message={message} onConversation={onConversation}/></ErrorBoundary>)}</div>{away&&<button className="jumpBottom" onClick={()=>{const el=ref.current;if(el)el.scrollTo({top:el.scrollHeight,behavior:"smooth"})}}><Icon name="arrowDown" size={16}/>К последнему</button>}</section>;
}
