"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {api} from "../../lib/api";
import type {AIModel} from "../../lib/types";
import {Icon} from "./Icons";

type Props={value:string;models:AIModel[];disabled?:boolean;onChange:(value:string)=>void};
type PickerSection="auto"|"model";
type RoutingTier="economy"|"balanced"|"maximum";

const MODEL_CATALOG_EVENT="aiws:model-catalog";
const modes=[
 {value:"auto:auto",label:"Авто",hint:"Сам выберет сложность и рабочую модель",icon:"spark" as const},
 {value:"auto:economy",label:"Простой",hint:"Быстро и экономно для обычных задач",icon:"zap" as const},
 {value:"auto:balanced",label:"Средний",hint:"Оптимально для большинства задач",icon:"spark" as const},
 {value:"auto:maximum",label:"Сложный",hint:"Для анализа, кода и сложных задач",icon:"brain" as const},
];

const PROVIDERS:Record<string,{label:string;order:number}>={
 "llm-system":{label:"LLM System",order:10},system:{label:"LLM System",order:10},gigachat:{label:"LLM System",order:10},
 yandexgpt:{label:"YandexGPT",order:20},yandex:{label:"YandexGPT",order:20},
 openai:{label:"ChatGPT",order:30},chatgpt:{label:"ChatGPT",order:30},deepseek:{label:"DeepSeek",order:40},
 anthropic:{label:"Claude",order:50},claude:{label:"Claude",order:50},gemini:{label:"Gemini",order:60},google:{label:"Gemini",order:60},
 xai:{label:"Grok",order:70},grok:{label:"Grok",order:70},openrouter:{label:"OpenRouter",order:80},
};

function normalizedProvider(model:AIModel){const raw=(model.provider||"").trim().toLowerCase();if(PROVIDERS[raw])return raw;const haystack=`${raw} ${model.display_name} ${model.slug}`.toLowerCase();if(haystack.includes("llm system")||haystack.includes("system lite")||haystack.includes("system pro")||haystack.includes("system max")||haystack.includes("giga"))return "llm-system";if(haystack.includes("yandexgpt")||haystack.includes("yandex gpt")||haystack.includes("яндекс"))return "yandexgpt";if(haystack.includes("chatgpt")||haystack.includes("openai")||haystack.includes("gpt-"))return "openai";if(haystack.includes("deepseek"))return "deepseek";if(haystack.includes("claude")||haystack.includes("anthropic"))return "anthropic";if(haystack.includes("gemini")||haystack.includes("google"))return "gemini";if(haystack.includes("grok")||haystack.includes("xai"))return "xai";if(haystack.includes("openrouter"))return "openrouter";return raw||"other"}
function providerLabelByKey(key:string){return PROVIDERS[key]?.label??(key==="other"?"Другие модели":key)}
function modelLabel(model:AIModel){let label=(model.display_name||model.slug).trim();const provider=providerLabelByKey(normalizedProvider(model));for(const prefix of [`${provider} · `,`${provider}: `,`${provider} - `]){if(label.toLowerCase().startsWith(prefix.toLowerCase())){label=label.slice(prefix.length).trim();break}}if(normalizedProvider(model)==="llm-system"){const haystack=`${model.slug} ${model.display_name} ${model.exact_api_id}`.toLowerCase();if(haystack.includes("max"))return "Max";if(haystack.includes("pro"))return "Pro";return "Lite"}return label||model.slug}
function tierForMode(value:string):RoutingTier|null{if(value==="auto:economy")return"economy";if(value==="auto:balanced")return"balanced";if(value==="auto:maximum")return"maximum";return null}
function broadcastCatalogState(state:"ready"|"error",available:boolean){if(typeof window==="undefined")return;window.dispatchEvent(new CustomEvent(MODEL_CATALOG_EVENT,{detail:{state,available}}))}

export function ModelPicker({value,models,disabled=false,onChange}:Props){
 const initialCatalog=models.filter(item=>item.available);const[open,setOpen]=useState(false);const[catalog,setCatalog]=useState<AIModel[]>(()=>initialCatalog);const catalogAvailableRef=useRef(initialCatalog.length>0);const root=useRef<HTMLDivElement|null>(null);const autoFallbackRef=useRef("");const initialSection:PickerSection=value.startsWith("model:")?"model":"auto";const[section,setSection]=useState<PickerSection>(initialSection);
 useEffect(()=>{const rows=models.filter(item=>item.available);if(rows.length>0){setCatalog(rows);catalogAvailableRef.current=true;broadcastCatalogState("ready",true)}},[models]);
 useEffect(()=>{let active=true;const refresh=async()=>{if(typeof document!=="undefined"&&document.visibilityState==="hidden")return;try{const rows=await api<AIModel[]>("/models/");if(active){const ready=rows.filter(item=>item.available);setCatalog(ready);catalogAvailableRef.current=ready.length>0;broadcastCatalogState("ready",ready.length>0)}}catch{if(active)broadcastCatalogState("error",catalogAvailableRef.current)}};void refresh();const timer=window.setInterval(()=>void refresh(),30000);const wake=()=>void refresh();window.addEventListener("online",wake);window.addEventListener("focus",wake);return()=>{active=false;window.clearInterval(timer);window.removeEventListener("online",wake);window.removeEventListener("focus",wake)}},[]);
 const tiersConfigured=useMemo(()=>catalog.some(item=>item.routing_tiers_configured===true),[catalog]);
 const tierAvailable=(tier:RoutingTier)=>!tiersConfigured||catalog.some(item=>(item.routing_tiers??[]).includes(tier));
 const visibleModes=useMemo(()=>modes.filter(item=>{const tier=tierForMode(item.value);return tier===null||tierAvailable(tier)}),[catalog,tiersConfigured]);
 const selectedTier=tierForMode(value);const selectedTierUnavailable=Boolean(selectedTier&&tiersConfigured&&!tierAvailable(selectedTier));
 useEffect(()=>{if(!selectedTierUnavailable||disabled)return;if(autoFallbackRef.current===value)return;autoFallbackRef.current=value;onChange("auto:auto")},[selectedTierUnavailable,disabled,value,onChange]);
 useEffect(()=>{if(!selectedTierUnavailable)autoFallbackRef.current=""},[selectedTierUnavailable]);
 const groups=useMemo(()=>{const map=new Map<string,AIModel[]>();for(const model of catalog){const key=normalizedProvider(model);map.set(key,[...(map.get(key)??[]),model])}return Array.from(map.entries()).sort(([a],[b])=>{const ao=PROVIDERS[a]?.order??999;const bo=PROVIDERS[b]?.order??999;return ao-bo||providerLabelByKey(a).localeCompare(providerLabelByKey(b),"ru")})},[catalog]);
 const currentMode=modes.find(item=>item.value===value);const currentModel=!currentMode&&value.startsWith("model:")?catalog.find(item=>`model:${item.slug}`===value):undefined;const unavailableManual=!currentMode&&value.startsWith("model:")&&!currentModel;const currentProvider=currentModel?normalizedProvider(currentModel):"";const firstProvider=groups[0]?.[0]??"";const[selectedProvider,setSelectedProvider]=useState<string>(currentProvider||firstProvider);
 useEffect(()=>{if(value.startsWith("model:")){setSection("model");const model=catalog.find(item=>`model:${item.slug}`===value);if(model)setSelectedProvider(normalizedProvider(model))}},[value,catalog]);
 useEffect(()=>{if(!selectedProvider&&firstProvider)setSelectedProvider(firstProvider);if(selectedProvider&&!groups.some(([key])=>key===selectedProvider)&&firstProvider)setSelectedProvider(firstProvider)},[groups,selectedProvider,firstProvider]);
 useEffect(()=>{if(!open)return;const outside=(event:MouseEvent)=>{if(root.current&&!root.current.contains(event.target as Node))setOpen(false)};const key=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("mousedown",outside);window.addEventListener("keydown",key);return()=>{document.removeEventListener("mousedown",outside);window.removeEventListener("keydown",key)}},[open]);
 const choose=(next:string)=>{if(disabled)return;onChange(next);setOpen(false)};
 const label=selectedTierUnavailable?"Авто":currentMode?currentMode.label:currentModel?`${providerLabelByKey(currentProvider)} · ${modelLabel(currentModel)}`:unavailableManual?"Авто":"Авто";
 const sub=selectedTierUnavailable?"Выбранный уровень недоступен — используем автоматический маршрут":currentMode?.hint??(currentModel?"Конкретная модель; при сбое сработает резервный маршрут":unavailableManual?"Выбранная модель недоступна — чат автоматически использует рабочую резервную":"Сам выберет сложность и рабочую модель");const providerModels=groups.find(([key])=>key===selectedProvider)?.[1]??[];
 return <div className="modelPicker" ref={root}><button type="button" className="modelPickerTrigger" disabled={disabled} onClick={()=>setOpen(v=>!v)} aria-haspopup="dialog" aria-expanded={open} title="Выбрать режим или модель"><span className="modelPickerMark"><Icon name={currentMode?.icon??"brain"} size={14}/></span><span className="modelPickerCurrent"><b>{label}</b><small>{sub}</small></span><Icon name="chevron" size={13}/></button>{open&&<div className="modelPickerMenu modelPickerMenuV2" role="dialog" aria-label="Выбор режима и модели"><div className="modelPickerHead"><div><b>Режим ответа</b><span>Выберите автоматический уровень или конкретную нейросеть.</span></div><button type="button" onClick={()=>setOpen(false)} aria-label="Закрыть"><Icon name="x" size={15}/></button></div><div className="modelPickerTabs" role="tablist" aria-label="Способ выбора"><button type="button" role="tab" aria-selected={section==="auto"} className={section==="auto"?"active":""} onClick={()=>setSection("auto")}><Icon name="spark" size={15}/>Авто</button><button type="button" role="tab" aria-selected={section==="model"} className={section==="model"?"active":""} onClick={()=>setSection("model")}><Icon name="brain" size={15}/>Модель</button></div>{section==="auto"?<div className="modelPickerPane"><div className="modelModeGrid">{visibleModes.map(item=><button type="button" key={item.value} className={value===item.value?"active":""} onClick={()=>choose(item.value)}><span><Icon name={item.icon} size={16}/></span><b>{item.label}</b><small>{item.hint}</small>{value===item.value&&<Icon name="check" size={15}/>}</button>)}</div></div>:<div className="modelPickerPane"><div className="modelProviderTabs" role="tablist" aria-label="Нейросеть">{groups.map(([provider,items])=><button type="button" role="tab" aria-selected={selectedProvider===provider} key={provider} className={selectedProvider===provider?"active":""} onClick={()=>setSelectedProvider(provider)}><b>{providerLabelByKey(provider)}</b><small>{items.length} {items.length===1?"модель":"модели"}</small></button>)}</div><div className="modelPickerModels modelPickerProviderModels">{providerModels.length?providerModels.map(model=>{const selected=value===`model:${model.slug}`;return <button type="button" key={model.slug} className={selected?"active":""} onClick={()=>choose(`model:${model.slug}`)}><span className="modelDot online"/><span className="modelCopy"><b>{modelLabel(model)}</b><small>Доступна</small></span>{selected&&<Icon name="check" size={15}/>}</button>}):<div className="modelPickerEmpty">Сейчас нет доступных моделей.</div>}</div></div>}</div>}</div>;
}
