"use client";

import Link from "next/link";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {api,clearTestUserMode} from "../../lib/api";
import type {Wallet} from "../../lib/types";
import {Icon} from "./Icons";
import type {ConversationFolder,ConversationSummary} from "./types";

type Props={
 items:ConversationSummary[];folders:ConversationFolder[];activeId:string|null;wallet:Wallet|null;collapsed:boolean;runningIds?:Set<string>;
 mobile?:boolean;
 onError?:(message:string)=>void;
 onToggle:()=>void;onCreate:()=>void;onSelect:(id:string)=>void;onSearch:()=>void;
 onCreateFolder:(name:string)=>Promise<void>;onRenameFolder:(id:string,name:string)=>Promise<void>;onPinFolder:(id:string,pinned:boolean)=>Promise<void>;onDeleteFolder:(id:string)=>Promise<void>;
 onRenameChat:(id:string,title:string)=>Promise<void>;onPinChat:(id:string,pinned:boolean)=>Promise<void>;onMoveChat:(id:string,folder:string|null)=>Promise<void>;onDeleteChat:(id:string)=>Promise<void>;
};
type RenameTarget={type:"chat"|"folder";id:string;current:string}|null;

export function Sidebar(props:Props){
 const {items,folders,activeId,wallet,collapsed}=props;const runningIds=props.runningIds??new Set<string>();
 const renameDialogRef=useRef<HTMLDialogElement|null>(null);
 const sideRef=useRef<HTMLElement|null>(null);
 const[openMenu,setOpenMenu]=useState<string|null>(null);const[folderInput,setFolderInput]=useState(false);const[folderName,setFolderName]=useState("");const[profileOpen,setProfileOpen]=useState(false);const[closedFolders,setClosedFolders]=useState<Set<string>>(new Set());const[renameTarget,setRenameTarget]=useState<RenameTarget>(null);const[renameValue,setRenameValue]=useState("");const[renameBusy,setRenameBusy]=useState(false);

 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpenMenu(null);setProfileOpen(false);setFolderInput(false);if(!renameBusy)setRenameTarget(null);if(props.mobile&&!collapsed)props.onToggle();}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[props.mobile,collapsed,props.onToggle,renameBusy]);
 useEffect(()=>{if(!openMenu&&!profileOpen)return;const outside=(event:PointerEvent)=>{if(!(event.target as HTMLElement).closest(".contextMenu,.sideMore,.profileMenu,.profileButton")){setOpenMenu(null);setProfileOpen(false)}};document.addEventListener("pointerdown",outside);return()=>document.removeEventListener("pointerdown",outside)},[openMenu,profileOpen]);
 const perform=(task:Promise<void>)=>void task.then(()=>setOpenMenu(null)).catch(reason=>props.onError?.(reason instanceof Error?reason.message:"Не удалось сохранить изменение. Попробуйте ещё раз."));
 useEffect(()=>{if(!props.mobile||collapsed||!sideRef.current)return;const previous=document.activeElement as HTMLElement|null;const side=sideRef.current;side.querySelector<HTMLElement>("button")?.focus();const trap=(event:KeyboardEvent)=>{if(event.key!=="Tab")return;const items=[...side.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),summary')].filter(item=>item.getClientRects().length>0);const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}};side.addEventListener("keydown",trap);return()=>{side.removeEventListener("keydown",trap);previous?.focus()}},[props.mobile,collapsed]);
 const pinned=useMemo(()=>items.filter(x=>x.is_pinned),[items]);
 const unfiled=useMemo(()=>items.filter(x=>!x.folder&&!x.is_pinned),[items]);
 const byFolder=(id:string)=>items.filter(x=>x.folder===id&&!x.is_pinned);
 const openRename=(target:Exclude<RenameTarget,null>)=>{setOpenMenu(null);setRenameTarget(target);setRenameValue(target.current)};
 useEffect(()=>{const rename=(event:Event)=>{const detail=(event as CustomEvent<{id:string;title:string}>).detail;if(detail)openRename({type:"chat",id:detail.id,current:detail.title})};window.addEventListener("aiws:rename-chat",rename);return()=>window.removeEventListener("aiws:rename-chat",rename)},[]);
 useEffect(()=>{if(!renameTarget||!renameDialogRef.current)return;const dialog=renameDialogRef.current;const previous=document.activeElement as HTMLElement|null;dialog.showModal();return()=>{dialog.close();previous?.focus()}},[renameTarget]);
 const submitRename=async(event:FormEvent)=>{event.preventDefault();if(!renameTarget)return;const next=renameValue.trim();if(!next||next===renameTarget.current){setRenameTarget(null);return}setRenameBusy(true);try{if(renameTarget.type==="chat")await props.onRenameChat(renameTarget.id,next);else await props.onRenameFolder(renameTarget.id,next);setRenameTarget(null);}catch(reason){props.onError?.(reason instanceof Error?reason.message:"Не удалось переименовать")}finally{setRenameBusy(false)}};
 const createFolder=async()=>{const name=folderName.trim();if(!name)return;try{await props.onCreateFolder(name);setFolderName("");setFolderInput(false)}catch(reason){props.onError?.(reason instanceof Error?reason.message:"Не удалось создать папку")}};
 const toggleFolder=(id:string)=>setClosedFolders(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next});
 const selectChat=(id:string)=>{props.onSelect(id);if(window.innerWidth<=820&&!collapsed)props.onToggle();};
 const logout=async()=>{if(typeof window!=="undefined"&&sessionStorage.getItem("aiws:test-user")){clearTestUserMode();window.location.assign("/admin-console/users");return;}try{await api("/auth/logout/",{method:"POST"});}finally{window.location.assign("/login")}};
 const ChatRow=({item}:{item:ConversationSummary})=>{const running=runningIds.has(item.id);return <div className={`sideRow ${item.id===activeId?"active":""} ${running?"running":""}`}><button className="sideRowMain" onClick={()=>selectChat(item.id)} title={running?`${item.title} · ответ формируется`:item.title}>{item.is_pinned&&<Icon name="pin" size={13}/>}<span>{item.title||"Новый чат"}</span></button><button className="sideMore" aria-label={`Меню чата ${item.title||"Новый чат"}`} onClick={()=>setOpenMenu(openMenu===`chat:${item.id}`?null:`chat:${item.id}`)}><Icon name="more"/></button>{openMenu===`chat:${item.id}`&&<div className="contextMenu" role="menu"><button onClick={()=>openRename({type:"chat",id:item.id,current:item.title||"Новый чат"})}><Icon name="pencil"/>Переименовать</button><button onClick={()=>perform(props.onPinChat(item.id,!item.is_pinned))}><Icon name="pin"/>{item.is_pinned?"Открепить":"Закрепить"}</button><div className="contextSubLabel">Папка</div><button onClick={()=>perform(props.onMoveChat(item.id,null))}><Icon name="folder"/>Без папки</button>{folders.map(folder=><button key={folder.id} onClick={()=>perform(props.onMoveChat(item.id,folder.id))}><Icon name="folder"/>{folder.name}</button>)}<div className="contextDivider"/><button className="danger" disabled={running} title={running?"Сначала остановите или дождитесь ответа":"Удалить чат"} onClick={()=>perform(props.onDeleteChat(item.id))}><Icon name="trash"/>{running?"Сначала остановите ответ":"Удалить"}</button></div>}</div>};
 return <><button type="button" className={`sidebarBackdrop ${collapsed?"hidden":""}`} aria-label="Закрыть меню" onClick={props.onToggle}/><aside ref={sideRef} role={props.mobile?"dialog":undefined} aria-modal={props.mobile&&!collapsed?true:undefined} aria-label="Меню чатов" className={`workspaceSidebar ${collapsed?"collapsed":""}`}>
  <div className="sideTop"><button className="iconButton" onClick={props.onToggle} aria-label={collapsed?"Развернуть панель":"Скрыть панель"}><Icon name="panel"/></button>{!collapsed&&<Link className="workspaceBrand" href="/app">AIlegend</Link>}</div>
  <button className="newChatButton" onClick={()=>{props.onCreate();if(window.innerWidth<=820&&!collapsed)props.onToggle();}}><Icon name="plus"/><span>Новый чат</span></button>
  <button className="sideAction" aria-label="Поиск" onClick={()=>{props.onSearch();if(window.innerWidth<=820&&!collapsed)props.onToggle();}}><Icon name="search"/><span>Поиск</span><kbd>⌘K</kbd></button>
  <nav className="sidePrimaryNav" aria-label="Основные разделы">
   <Link href="/app/projects" title="Проекты"><Icon name="folder"/><span>Проекты</span></Link>
   <Link href="/app/agents" title="AI-сотрудники"><Icon name="brain"/><span>Агенты</span></Link>
   <Link href="/app/images" title="Изображения"><Icon name="spark"/><span>Изображения</span></Link>
   <details className="sideMoreSections"><summary>Ещё разделы</summary>
   <Link href="/app/teams" title="Команды AI-сотрудников"><Icon name="brain"/><span>Команды</span></Link>
   <Link href="/app/schedules" title="Автономная работа по расписанию"><Icon name="calendar"/><span>Автономность</span></Link>
   <Link href="/app/events" title="Запуск агентов по внешним событиям"><Icon name="zap"/><span>События</span></Link>
   <Link href="/app/dev" title="AI-команда разработки"><Icon name="zap"/><span>Dev Studio</span></Link>
   <Link href="/app/compare" title="Сравнение моделей"><Icon name="scale"/><span>Сравнить модели</span></Link>
   </details>
  </nav>
  {!collapsed&&<div className="sideScroll">
   {pinned.length>0&&<section className="sideSection"><div className="sideLabel">Закреплённые</div>{pinned.map(item=><ChatRow key={item.id} item={item}/>)}</section>}
   <section className="sideSection"><div className="sideLabel sideLabelAction"><span>Папки</span><button aria-label="Создать папку" onClick={()=>setFolderInput(true)}><Icon name="folderPlus" size={16}/></button></div>{folderInput&&<div className="folderInput"><input autoFocus value={folderName} placeholder="Название папки" aria-label="Название новой папки" onChange={e=>setFolderName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void createFolder();if(e.key==="Escape")setFolderInput(false)}}/><button aria-label="Создать папку" disabled={!folderName.trim()} onClick={()=>void createFolder()}><Icon name="check"/></button></div>}{folders.map(folder=>{const closed=closedFolders.has(folder.id);return <div key={folder.id} className="folderBlock"><div className="sideRow"><button className="sideRowMain" aria-expanded={!closed} onClick={()=>toggleFolder(folder.id)}><Icon name="folder" size={15}/><span>{folder.name}</span><small>{folder.conversation_count}</small><span className={`folderChevron ${closed?"closed":""}`}>⌄</span></button><button className="sideMore" aria-label={`Меню папки ${folder.name}`} onClick={()=>setOpenMenu(openMenu===`folder:${folder.id}`?null:`folder:${folder.id}`)}><Icon name="more"/></button>{openMenu===`folder:${folder.id}`&&<div className="contextMenu" role="menu"><button onClick={()=>openRename({type:"folder",id:folder.id,current:folder.name})}><Icon name="pencil"/>Переименовать</button><button onClick={()=>perform(props.onPinFolder(folder.id,!folder.is_pinned))}><Icon name="pin"/>{folder.is_pinned?"Открепить":"Закрепить"}</button><button className="danger" onClick={()=>perform(props.onDeleteFolder(folder.id))}><Icon name="trash"/>Удалить папку</button></div>}</div>{!closed&&byFolder(folder.id).map(item=><ChatRow key={item.id} item={item}/>)}</div>})}</section>
   <section className="sideSection"><div className="sideLabel">Недавние</div>{unfiled.map(item=><ChatRow key={item.id} item={item}/>)}</section>
  </div>}
  <div className="sideFooter">{!collapsed&&<Link className="walletMini" href="/app/wallet"><span><Icon name="wallet"/>Баланс</span><b>{(wallet?Number(wallet.available_rub).toLocaleString("ru-RU",{minimumFractionDigits:2,maximumFractionDigits:2}):"—")} ₽</b></Link>}<div className="profileRow"><button type="button" className="profileButton" onClick={()=>setProfileOpen(current=>!current)} aria-expanded={profileOpen} aria-label="Открыть меню профиля"><span className="avatar"><Icon name="user" size={16}/></span>{!collapsed&&<span>Профиль</span>}</button>{!collapsed&&<Link className="iconButton" href="/app/settings" aria-label="Настройки"><Icon name="settings"/></Link>}{profileOpen&&<div className="profileMenu"><Link href="/app/account"><Icon name="user"/>Аккаунт</Link><Link href="/app/notifications"><Icon name="bell"/>Уведомления</Link><Link href="/app/usage"><Icon name="wallet"/>Использование</Link><Link href="/app/wallet"><Icon name="wallet"/>Баланс и платежи</Link><Link href="/app/settings"><Icon name="settings"/>Настройки</Link><Link href="/app/help"><Icon name="search"/>Помощь</Link><div className="contextDivider"/><button type="button" onClick={()=>void logout()}>Выйти</button></div>}</div></div>
 </aside>{renameTarget&&<dialog ref={renameDialogRef} className="miniDialog renameDialog" onCancel={event=>{event.preventDefault();if(!renameBusy)setRenameTarget(null)}} aria-labelledby="rename-title"><form onSubmit={submitRename}><header><div><h2 id="rename-title">{renameTarget.type==="chat"?"Переименовать чат":"Переименовать папку"}</h2><p>Короткое название легче найти в истории и поиске.</p></div><button type="button" className="iconButton" onClick={()=>setRenameTarget(null)} aria-label="Закрыть"><Icon name="x" size={16}/></button></header><input autoFocus value={renameValue} maxLength={160} onChange={event=>setRenameValue(event.target.value)} onKeyDown={event=>{if(event.key==="Escape")setRenameTarget(null)}} aria-label="Новое название"/><footer><button type="button" onClick={()=>setRenameTarget(null)}>Отмена</button><button className="dialogPrimary" disabled={renameBusy||!renameValue.trim()}>{renameBusy?"Сохраняем…":"Сохранить"}</button></footer></form></dialog>}</>;
}
