"use client";

import Link from "next/link";
import {ChangeEvent,useCallback,useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {ApiError,api,ensureCsrf,streamMessage} from "../../lib/api";
import type {AIModel,ChatMessage,Conversation,FileAsset,Project,User,Wallet} from "../../lib/types";
import {trackProductEvent} from "../components/ProductAnalytics";
import {ChatThread} from "./ChatThread";
import {Composer} from "./Composer";
import {ErrorBoundary} from "./ErrorBoundary";
import {Icon} from "./Icons";
import {SearchOverlay} from "./SearchOverlay";
import {Sidebar} from "./Sidebar";
import type {ConversationFolder,ConversationSummary,DraftState} from "./types";

type WorkspacePage={conversation:Conversation;has_more:boolean;next_before:string|null};
type ServerDraft={content:string;version:number;updated_at:string|null};
type OnboardingStatus={completed_generations:number};
type Running={controller:AbortController;assistantId:string;startedAt:number};

const draftKey=(id:string|null)=>`aiws:draft:${id??"new"}`;
const nowIso=()=>new Date().toISOString();
const summaryFromConversation=(value:Conversation,existing?:ConversationSummary):ConversationSummary=>({id:value.id,title:value.title,routing_mode:value.routing_mode,selected_model:value.selected_model,project:value.project,folder:existing?.folder??null,is_pinned:existing?.is_pinned??false,created_at:value.created_at,updated_at:value.updated_at});

export default function WorkspaceV2(){
 const router=useRouter();
 const[boot,setBoot]=useState<"loading"|"ready"|"error">("loading");const[user,setUser]=useState<User|null>(null);const[summaries,setSummaries]=useState<ConversationSummary[]>([]);const[folders,setFolders]=useState<ConversationFolder[]>([]);const[active,setActive]=useState<Conversation|null>(null);const[hasMore,setHasMore]=useState(false);const[nextBefore,setNextBefore]=useState<string|null>(null);const[loadingOlder,setLoadingOlder]=useState(false);const[models,setModels]=useState<AIModel[]>([]);const[projects,setProjects]=useState<Project[]>([]);const[wallet,setWallet]=useState<Wallet|null>(null);const[value,setValue]=useState("");const[error,setError]=useState("");const[note,setNote]=useState("");const[offline,setOffline]=useState(false);const[collapsed,setCollapsed]=useState(false);const[searchOpen,setSearchOpen]=useState(false);const[toolsOpen,setToolsOpen]=useState(false);const[attachments,setAttachments]=useState<FileAsset[]>([]);const[uploading,setUploading]=useState(false);const[runningIds,setRunningIds]=useState<Set<string>>(new Set());const[newRouting,setNewRouting]=useState<{mode:"economy"|"balanced"|"maximum"|"manual";model:string}>({mode:"balanced",model:""});const[newProject,setNewProject]=useState<string|null>(null);
 const runningRef=useRef(new Map<string,Running>());const draftTimer=useRef<number|null>(null);const serverDraftTimer=useRef<number|null>(null);const fileInput=useRef<HTMLInputElement|null>(null);const activeId=active?.id??null;
 const availableModels=useMemo(()=>models.filter(model=>model.available),[models]);
 const runningCurrent=activeId?runningIds.has(activeId):false;

 const loadFolders=useCallback(async()=>setFolders(await api<ConversationFolder[]>("/conversation-folders/")),[]);
 const loadSummaries=useCallback(async()=>setSummaries(await api<ConversationSummary[]>("/conversation-summaries/?limit=120")),[]);
 const loadConversation=useCallback(async(id:string,replaceDraft=true)=>{setError("");try{const page=await api<WorkspacePage>(`/conversation-workspace/${id}/?limit=60`);setActive(page.conversation);setHasMore(page.has_more);setNextBefore(page.next_before);if(replaceDraft){let local:DraftState|null=null;try{const raw=localStorage.getItem(draftKey(id));if(raw)local=JSON.parse(raw) as DraftState;}catch{}let server:ServerDraft|null=null;try{server=await api<ServerDraft>(`/conversations/${id}/draft/`);}catch{}const serverTime=server?.updated_at?new Date(server.updated_at).getTime():0;if(local&&local.updatedAt>=serverTime)setValue(local.content);else setValue(server?.content??"");}setAttachments([]);}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось открыть чат");}},[]);
 const load=useCallback(async()=>{setBoot("loading");setError("");try{await ensureCsrf();const me=await api<User>("/auth/me/");const[summaryRows,folderRows,modelRows,projectRows,walletData]=await Promise.all([api<ConversationSummary[]>("/conversation-summaries/?limit=120"),api<ConversationFolder[]>("/conversation-folders/"),api<AIModel[]>("/models/"),api<Project[]>("/projects/"),api<Wallet>("/wallet/")]);setUser(me);setSummaries(summaryRows);setFolders(folderRows);setModels(modelRows);setProjects(projectRows);setWallet(walletData);setNewRouting(current=>({...current,model:current.model||modelRows.find(item=>item.available)?.slug||""}));const stored=localStorage.getItem("aiws:sidebar-collapsed");setCollapsed(stored==="1");if(summaryRows[0])await loadConversation(summaryRows[0].id);else{setActive(null);const raw=localStorage.getItem(draftKey(null));if(raw){try{setValue((JSON.parse(raw) as DraftState).content);}catch{}}}setBoot("ready");}catch(reason){if(reason instanceof ApiError&&[401,403].includes(reason.status)){router.replace("/login");return;}setError(reason instanceof Error?reason.message:"Сервис временно недоступен");setBoot("error");}},[router,loadConversation]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{const online=()=>setOffline(false);const offlineHandler=()=>setOffline(true);setOffline(!navigator.onLine);window.addEventListener("online",online);window.addEventListener("offline",offlineHandler);return()=>{window.removeEventListener("online",online);window.removeEventListener("offline",offlineHandler)}},[]);
 useEffect(()=>{const starter=sessionStorage.getItem("starter-prompt");if(starter){setValue(starter);sessionStorage.removeItem("starter-prompt");}},[]);
 useEffect(()=>{const shortcut=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setSearchOpen(true)}};window.addEventListener("keydown",shortcut);return()=>window.removeEventListener("keydown",shortcut)},[]);

 useEffect(()=>{if(boot!=="ready")return;if(draftTimer.current)window.clearTimeout(draftTimer.current);draftTimer.current=window.setTimeout(()=>{try{localStorage.setItem(draftKey(activeId),JSON.stringify({content:value,updatedAt:Date.now(),serverVersion:0} satisfies DraftState));}catch{}},300);if(activeId){if(serverDraftTimer.current)window.clearTimeout(serverDraftTimer.current);serverDraftTimer.current=window.setTimeout(()=>{void api(`/conversations/${activeId}/draft/`,{method:"PUT",body:JSON.stringify({content:value})}).catch(()=>undefined)},1400);}return()=>{if(draftTimer.current)window.clearTimeout(draftTimer.current);if(serverDraftTimer.current)window.clearTimeout(serverDraftTimer.current)}},[value,activeId,boot]);

 const clearDraft=async(id:string|null)=>{try{localStorage.removeItem(draftKey(id));}catch{}if(id)await api(`/conversations/${id}/draft/`,{method:"DELETE"}).catch(()=>undefined)};
 const newChat=()=>{setActive(null);setHasMore(false);setNextBefore(null);setAttachments([]);setError("");setNote("");try{const raw=localStorage.getItem(draftKey(null));setValue(raw?(JSON.parse(raw) as DraftState).content:"");}catch{setValue("")}};
 const createConversation=async()=>{const payload:Record<string,unknown>={title:"Новый чат",routing_mode:newRouting.mode,project:newProject};if(newRouting.model)payload.selected_model=newRouting.model;const conversation=await api<Conversation>("/conversations/",{method:"POST",body:JSON.stringify(payload)});const summary=summaryFromConversation(conversation);setSummaries(current=>[summary,...current.filter(x=>x.id!==conversation.id)]);setActive(conversation);setHasMore(false);setNextBefore(null);return conversation;};
 const openChat=async(id:string)=>{if(activeId===id)return;await loadConversation(id);};
 const mergeConversation=(conversation:Conversation)=>{setActive(current=>{if(!current||current.id!==conversation.id)return current;const map=new Map(current.messages.map(message=>[message.id,message]));for(const message of conversation.messages)map.set(message.id,message);return {...conversation,messages:Array.from(map.values()).sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime())};});setSummaries(current=>{const existing=current.find(x=>x.id===conversation.id);const next=summaryFromConversation(conversation,existing);return [next,...current.filter(x=>x.id!==conversation.id)]})};
 const refreshConversation=async(id:string)=>{const page=await api<WorkspacePage>(`/conversation-workspace/${id}/?limit=60`);mergeConversation(page.conversation);setHasMore(page.has_more);setNextBefore(page.next_before);};
 const loadOlder=async()=>{if(!active||!hasMore||!nextBefore||loadingOlder)return;setLoadingOlder(true);try{const page=await api<WorkspacePage>(`/conversation-workspace/${active.id}/?limit=60&before=${encodeURIComponent(nextBefore)}`);setActive(current=>current&&current.id===active.id?{...current,messages:[...page.conversation.messages,...current.messages]}:current);setHasMore(page.has_more);setNextBefore(page.next_before);}finally{setLoadingOlder(false)}};
 const updateConversation=async(changes:Record<string,unknown>)=>{if(!active){if("routing_mode" in changes)setNewRouting(r=>({...r,mode:String(changes.routing_mode) as typeof r.mode}));if("selected_model" in changes)setNewRouting(r=>({...r,mode:"manual",model:String(changes.selected_model)}));if("project" in changes)setNewProject(changes.project?String(changes.project):null);return;}try{const result=await api<Conversation>(`/conversations/${active.id}/`,{method:"PATCH",body:JSON.stringify(changes)});mergeConversation(result);}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось изменить чат")}};
 const trackActivation=async()=>{try{const onboarding=await api<OnboardingStatus>("/auth/onboarding/");if(onboarding.completed_generations===1)void trackProductEvent("first_chat");if(onboarding.completed_generations===2)void trackProductEvent("second_chat");}catch{}};

 const send=async()=>{const prompt=value.trim();if(!prompt||offline)return;setError("");setNote("");let conversation=active;try{if(!conversation)conversation=await createConversation();if(!conversation||runningRef.current.has(conversation.id))return;const conversationId=conversation.id;const userMessage:ChatMessage={id:`local-user-${crypto.randomUUID()}`,branch:conversation.active_branch,role:"user",content:prompt,status:"saved",generation:null,created_at:nowIso()};const assistantId=`local-ai-${crypto.randomUUID()}`;const assistant:ChatMessage={id:assistantId,branch:conversation.active_branch,role:"assistant",content:"",status:"streaming",generation:null,created_at:nowIso()};setActive(current=>current&&current.id===conversationId?{...current,messages:[...current.messages,userMessage,assistant]}:current);setValue("");await clearDraft(conversationId);await clearDraft(null);const controller=new AbortController();runningRef.current.set(conversationId,{controller,assistantId,startedAt:Date.now()});setRunningIds(current=>new Set(current).add(conversationId));let pending="";let timer:number|null=null;const flush=()=>{timer=null;if(!pending)return;const chunk=pending;pending="";setActive(current=>current&&current.id===conversationId?{...current,messages:current.messages.map(message=>message.id===assistantId?{...message,content:message.content+chunk}:message)}:current)};const schedule=()=>{if(timer!==null)return;timer=window.setTimeout(flush,document.visibilityState==="hidden"?300:50)};await streamMessage(conversationId,{content:prompt,client_message_id:crypto.randomUUID(),file_ids:attachments.map(item=>item.id)},`workspace:${crypto.randomUUID()}`,({event,data})=>{if(event==="delta"){pending+=String(data.text??"");schedule()}if(event==="recovery")setNote(data.action==="fallback"?"Подключаем резервную модель…":"Повторяем запрос…");if(event==="routing")setNote(String(data.explanation??"AUTO выбрал модель"));if(event==="error")setError(String(data.message??"Не удалось получить ответ. Деньги не списаны."));},controller.signal);flush();}catch(reason){if(!(reason instanceof DOMException&&reason.name==="AbortError"))setError(reason instanceof Error?reason.message:"Соединение прервалось. Черновик сохранён.");}finally{if(conversation){runningRef.current.delete(conversation.id);setRunningIds(current=>{const next=new Set(current);next.delete(conversation!.id);return next});setNote("");await Promise.all([refreshConversation(conversation.id),api<Wallet>("/wallet/").then(setWallet),loadSummaries()]).catch(()=>undefined);setAttachments([]);await trackActivation();}}};
 const stop=()=>{if(!activeId)return;runningRef.current.get(activeId)?.controller.abort();};

 const renameChat=async(id:string,title:string)=>{const result=await api<Conversation>(`/conversations/${id}/`,{method:"PATCH",body:JSON.stringify({title})});setSummaries(current=>current.map(item=>item.id===id?{...item,title:result.title,updated_at:result.updated_at}:item));if(active?.id===id)setActive(current=>current?{...current,title:result.title}:current)};
 const patchUI=async(id:string,changes:{folder?:string|null;is_pinned?:boolean})=>{await api(`/conversation-ui/${id}/`,{method:"PATCH",body:JSON.stringify(changes)});setSummaries(current=>current.map(item=>item.id===id?{...item,...changes}:item));await loadFolders()};
 const deleteChat=async(id:string)=>{if(!window.confirm("Удалить чат? Это действие нельзя отменить."))return;await api(`/conversations/${id}/`,{method:"DELETE"});setSummaries(current=>current.filter(item=>item.id!==id));if(active?.id===id)newChat()};
 const createFolder=async(name:string)=>{await api("/conversation-folders/",{method:"POST",body:JSON.stringify({name})});await loadFolders()};
 const renameFolder=async(id:string,name:string)=>{await api(`/conversation-folders/${id}/`,{method:"PATCH",body:JSON.stringify({name})});await loadFolders()};
 const pinFolder=async(id:string,is_pinned:boolean)=>{await api(`/conversation-folders/${id}/`,{method:"PATCH",body:JSON.stringify({is_pinned})});await loadFolders()};
 const deleteFolder=async(id:string)=>{if(!window.confirm("Удалить папку? Чаты останутся в истории."))return;await api(`/conversation-folders/${id}/`,{method:"DELETE"});setSummaries(current=>current.map(item=>item.folder===id?{...item,folder:null}:item));await loadFolders()};

 const uploadFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;const projectId=active?.project??newProject;if(!projectId){setError("Чтобы прикрепить файл к чату, сначала выберите проект.");return;}setUploading(true);setError("");try{const form=new FormData();form.append("file",file);form.append("project",projectId);const asset=await api<FileAsset>("/files/",{method:"POST",headers:{"Idempotency-Key":`upload:${crypto.randomUUID()}`},body:form});setAttachments(current=>[...current,asset].slice(0,4));void trackProductEvent("file_uploaded",{type:asset.detected_type});}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить файл");}finally{setUploading(false);setToolsOpen(false)}};

 const toggleSidebar=()=>setCollapsed(current=>{const next=!current;localStorage.setItem("aiws:sidebar-collapsed",next?"1":"0");return next});
 const selectorValue=active?(active.routing_mode==="manual"?`model:${active.selected_model}`:`auto:${active.routing_mode}`):(newRouting.mode==="manual"?`model:${newRouting.model}`:`auto:${newRouting.mode}`);
 const projectValue=active?.project??newProject??"";

 if(boot==="loading")return <main className="workspaceLoading"><div className="loader"/><span>Открываем рабочее пространство…</span></main>;
 if(boot==="error")return <main className="workspaceLoading"><h1>Не удалось подключиться</h1><p>{error}</p><button onClick={()=>void load()}>Повторить</button></main>;
 return <main className={`workspaceApp ${collapsed?"sidebarCollapsed":""}`}>
  <ErrorBoundary><Sidebar items={summaries} folders={folders} activeId={activeId} wallet={wallet} collapsed={collapsed} onToggle={toggleSidebar} onCreate={newChat} onSelect={id=>void openChat(id)} onSearch={()=>setSearchOpen(true)} onCreateFolder={createFolder} onRenameFolder={renameFolder} onPinFolder={pinFolder} onDeleteFolder={deleteFolder} onRenameChat={renameChat} onPinChat={(id,pinned)=>patchUI(id,{is_pinned:pinned})} onMoveChat={(id,folder)=>patchUI(id,{folder})} onDeleteChat={deleteChat}/></ErrorBoundary>
  <section className="workspaceMain"><header className="chatHeader"><div className="chatTitle">{active?<button onClick={()=>{const title=window.prompt("Название чата",active.title)?.trim();if(title)void renameChat(active.id,title)}}>{active.title}</button>:<span>Новый чат</span>}</div><div className="headerControls"><label className="selectControl"><select value={selectorValue} onChange={e=>{const[kind,val]=e.target.value.split(":");void(kind==="auto"?updateConversation({routing_mode:val}):updateConversation({routing_mode:"manual",selected_model:val}))}}><optgroup label="Автоматический выбор"><option value="auto:economy">Быстро</option><option value="auto:balanced">Баланс</option><option value="auto:maximum">Максимум</option></optgroup><optgroup label="Выбрать модель вручную">{models.map(model=><option key={model.slug} value={`model:${model.slug}`} disabled={!model.available}>{model.display_name}{!model.available?" · недоступна":""}</option>)}</optgroup></select><Icon name="chevron" size={14}/></label><label className="selectControl projectSelect"><select value={projectValue} onChange={e=>void updateConversation({project:e.target.value||null})}><option value="">Без проекта</option>{projects.filter(project=>!project.archived_at&&project.role!=="viewer").map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select><Icon name="chevron" size={14}/></label><Link className="headerIcon" href="/app/usage" title="Использование"><Icon name="wallet"/></Link></div></header>
   {error&&<div className="topNotice error"><span>{error}</span><button onClick={()=>setError("")}><Icon name="x"/></button></div>}{offline&&<div className="topNotice"><span>Нет соединения. Текст сохраняется на устройстве.</span></div>}{note&&<div className="topNotice subtle"><span>{note}</span></div>}
   <ErrorBoundary><ChatThread conversation={active} hasMore={hasMore} loadingOlder={loadingOlder} onLoadOlder={()=>void loadOlder()} onConversation={mergeConversation} onStarter={setValue}/></ErrorBoundary>
   {attachments.length>0&&<div className="attachmentTray">{attachments.map(item=><div key={item.id} className="attachmentChip"><Icon name="folder" size={15}/><span>{item.original_name}</span><small>{item.status}</small><button onClick={()=>setAttachments(current=>current.filter(x=>x.id!==item.id))}><Icon name="x" size={14}/></button></div>)}</div>}
   <div className="composerWrap"><div className="toolAnchor">{toolsOpen&&<div className="toolMenu"><button disabled={uploading} onClick={()=>fileInput.current?.click()}><Icon name="folderPlus"/>{uploading?"Загружаем…":"Добавить файл"}</button><button onClick={()=>{setValue(current=>current||"Найди актуальную информацию в интернете и укажи источники: ");setToolsOpen(false)}}><Icon name="search"/>Поиск в интернете</button></div>}<input ref={fileInput} type="file" hidden onChange={uploadFile}/></div><ErrorBoundary><Composer value={value} setValue={setValue} sending={runningCurrent} offline={offline} onSend={()=>void send()} onStop={stop} onOpenTools={()=>setToolsOpen(value=>!value)}/></ErrorBoundary></div>
  </section>
  <SearchOverlay open={searchOpen} onClose={()=>setSearchOpen(false)} onOpenConversation={id=>void openChat(id)}/>
 </main>;
}
