"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {ApiError,api,ensureCsrf,streamMessage} from "../../lib/api";
import type {AIModel,ChatMessage,Conversation,Project,User,Wallet} from "../../lib/types";
import {Sidebar} from "./Sidebar";
import {ChatThread} from "./ChatThread";
import {Composer} from "./Composer";

export default function WorkspaceV2(){
  const router=useRouter();
  const [boot,setBoot]=useState<"loading"|"ready"|"error">("loading");const [user,setUser]=useState<User|null>(null);const [items,setItems]=useState<Conversation[]>([]);const [activeId,setActiveId]=useState<string|null>(null);const [models,setModels]=useState<AIModel[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [wallet,setWallet]=useState<Wallet|null>(null);const [value,setValue]=useState("");const [sending,setSending]=useState(false);const [error,setError]=useState("");const [note,setNote]=useState("");const abortRef=useRef<AbortController|null>(null);
  const active=items.find(item=>item.id===activeId)??null;
  const availableModels=useMemo(()=>models.filter(model=>model.available),[models]);
  const replace=(conversation:Conversation)=>setItems(current=>[conversation,...current.filter(item=>item.id!==conversation.id)]);
  const load=useCallback(async()=>{setBoot("loading");setError("");try{await ensureCsrf();const me=await api<User>("/auth/me/");const [conversations,modelList,projectList,walletData]=await Promise.all([api<Conversation[]>("/conversations/"),api<AIModel[]>("/models/"),api<Project[]>("/projects/"),api<Wallet>("/wallet/")]);setUser(me);setItems(conversations);setModels(modelList);setProjects(projectList);setWallet(walletData);setActiveId(current=>current&&conversations.some(item=>item.id===current)?current:conversations[0]?.id??null);setBoot("ready");}catch(reason){if(reason instanceof ApiError&&[401,403].includes(reason.status)){router.replace("/login");return;}setError(reason instanceof Error?reason.message:"Сервис временно недоступен");setBoot("error");}},[router]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const starter=sessionStorage.getItem("starter-prompt");if(starter){setValue(starter);sessionStorage.removeItem("starter-prompt");}},[]);
  const create=async()=>{const model=availableModels[0];const payload:Record<string,string>={title:"Новый чат",routing_mode:"balanced"};if(model)payload.selected_model=model.slug;const conversation=await api<Conversation>("/conversations/",{method:"POST",body:JSON.stringify(payload)});replace(conversation);setActiveId(conversation.id);return conversation;};
  const refresh=async(id:string)=>replace(await api<Conversation>(`/conversations/${id}/`));
  const update=async(changes:Record<string,unknown>)=>{if(!active)return;try{replace(await api<Conversation>(`/conversations/${active.id}/`,{method:"PATCH",body:JSON.stringify(changes)}));}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось изменить чат");}};
  const send=async()=>{const prompt=value.trim();if(!prompt||sending)return;setError("");setNote("");let conversation=active;try{if(!conversation)conversation=await create();if(!conversation)return;const localUser:ChatMessage={id:`local-user-${crypto.randomUUID()}`,branch:conversation.active_branch,role:"user",content:prompt,status:"saved",generation:null,created_at:new Date().toISOString()};const localAssistant:ChatMessage={id:`local-ai-${crypto.randomUUID()}`,branch:conversation.active_branch,role:"assistant",content:"",status:"streaming",generation:null,created_at:new Date().toISOString()};replace({...conversation,messages:[...conversation.messages,localUser,localAssistant]});setValue("");setSending(true);const controller=new AbortController();abortRef.current=controller;await streamMessage(conversation.id,{content:prompt,client_message_id:crypto.randomUUID()},`workspace:${crypto.randomUUID()}`,({event,data})=>{if(event==="recovery")setNote(data.action==="fallback"?"Подключаем резервную модель…":"Повторяем запрос безопасно…");if(event==="routing")setNote(String(data.explanation??"AUTO выбрал модель"));if(event==="error")setError(String(data.message??"Ответ не получен. Деньги не списаны."));},controller.signal);}catch(reason){if(!(reason instanceof DOMException&&reason.name==="AbortError"))setError(reason instanceof Error?reason.message:"Соединение прервано");}finally{setSending(false);setNote("");abortRef.current=null;if(conversation){await Promise.all([refresh(conversation.id),api<Wallet>("/wallet/").then(setWallet)]).catch(()=>undefined);}}};
  if(boot==="loading")return <main className="centerState"><div className="loader"/><h1>Открываем AI Workspace</h1></main>;
  if(boot==="error")return <main className="centerState"><h1>Не удалось подключиться</h1><p>{error}</p><button onClick={()=>void load()}>Повторить</button></main>;
  return <main className="proApp"><Sidebar items={items} activeId={activeId} wallet={wallet} onCreate={()=>void create()} onSelect={setActiveId}/><section className="proMain"><header className="proTopbar"><div className="proSelectors"><select value={active?active.routing_mode==="manual"?`model:${active.selected_model}`:`auto:${active.routing_mode}`:""} disabled={!active||sending} onChange={e=>{const[kind,val]=e.target.value.split(":");void(kind==="auto"?update({routing_mode:val}):update({routing_mode:"manual",selected_model:val}));}}><optgroup label="AUTO Router"><option value="auto:balanced">AUTO · Баланс</option><option value="auto:economy">AUTO · Эконом</option><option value="auto:maximum">AUTO · Максимум</option></optgroup><optgroup label="Модели">{models.map(model=><option key={model.slug} value={`model:${model.slug}`} disabled={!model.available}>{model.display_name}{!model.available?" · недоступна":""}</option>)}</optgroup></select><select value={active?.project??""} disabled={!active||sending} onChange={e=>void update({project:e.target.value||null})}><option value="">Без проекта</option>{projects.filter(project=>!project.archived_at&&project.role!=="viewer").map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></div><div className="proStatus">{user?.username} · системы работают</div></header>{error&&<div className="proBanner">{error}</div>}{note&&<div className="proBanner">{note}</div>}<ChatThread conversation={active} onConversation={replace} onStarter={setValue}/><Composer value={value} setValue={setValue} sending={sending} onSend={()=>void send()} onStop={()=>abortRef.current?.abort()}/></section></main>;
}
