"use client";

import {useEffect,useState} from "react";
import {api} from "../../../lib/api";
import styles from "../admin.module.css";

type Provider={provider:string;enabled:boolean;emergency_disabled:boolean;health:string;customer_ready:boolean;consecutive_failures:number;circuit_opened_until:string|null;last_checked_at:string|null;last_latency_ms:number|null;credential_source:string;keys:Record<string,number>;key_error_codes:Record<string,number>};
type ModelReadiness={model:string;display_name:string;provider:string;enabled:boolean;upstream_configured:boolean;current_version:string|null;provider_health:string;healthy_keys:number;price_configured:boolean;price_error:string;ready:boolean;reasons:string[];warnings:string[]};
type ChatError={generation_id:string;correlation_id:string;state:string;internal_error_code:string;provider:string;routed_model:string;requested_model:string;actual_cost_rub:string|null;created_at:string;completed_at:string|null;attempts:Array<{sequence:number;provider__slug:string;model_slug:string;state:string;error_code:string;retryable:boolean;latency_ms:number|null}>};
type SystemIssue={fingerprint:string;status:string;severity:string;exception_type:string;summary:string;source:string;method:string;task_id:string;correlation_id:string;first_seen_at:string;last_seen_at:string;occurrences:number;resolution_note:string};
type ReleaseStatus={status:string;phase:string;exit_code:number|null;commit:string;occurred_at:string;log_file:string;failures:string[]};
type ChatReadiness={window_hours:number;completed_generations:number;failed_generations:number;cancelled_generations:number;preflight_failed:number;success_rate_percent:number;stuck_generations:number;active_customer_reservations:number;stale_customer_reservations:number;wallets_total:number;wallets_with_positive_balance:number;wallets_without_available_balance:number};
type Diagnostics={schema_version:number;generated_at:string;summary:{open_system_issues:number;recent_failed_generations:number;unhealthy_providers:number;providers_total:number;blocked_models:number;routable_models:number;models_total:number;release_gate_failed:boolean;stuck_generations:number;stale_customer_reservations:number};release_status:ReleaseStatus|null;chat_readiness:ChatReadiness;providers:Provider[];models:ModelReadiness[];recent_chat_errors:ChatError[];system_issues:SystemIssue[];privacy:Record<string,boolean>};

export default function ChatDiagnosticsPage(){
 const[data,setData]=useState<Diagnostics|null>(null);
 const[error,setError]=useState("");
 const[copied,setCopied]=useState(false);
 const[shareUrl,setShareUrl]=useState("");
 const[sharing,setSharing]=useState(false);
 const load=async()=>{try{setData(await api<Diagnostics>("/admin/chat-diagnostics/"));setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить диагностику");}};
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(timer);},[]);
 const copy=async()=>{if(!data)return;await navigator.clipboard.writeText(JSON.stringify(data,null,2));setCopied(true);window.setTimeout(()=>setCopied(false),2000);};
 const share=async()=>{setSharing(true);setError("");try{const result=await api<{url:string;expires_in_seconds:number}>("/admin/chat-diagnostics/share/",{method:"POST",body:"{}"});setShareUrl(result.url);await navigator.clipboard.writeText(result.url);}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось создать диагностическую ссылку");}finally{setSharing(false);}};
 const download=()=>{if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`system-diagnostics-${new Date().toISOString().replace(/[:.]/g,"-")}.json`;a.click();URL.revokeObjectURL(url);};
 return <>
  <header className={styles.header}><div><h1>Диагностический центр</h1><p>Одна точка для release gate, клиентского чата, backend/frontend ошибок, AI-провайдеров, моделей, ключей, зависших резервов и неудачных генераций.</p></div><div className={styles.actions}><button className={styles.button} onClick={()=>void load()}>Обновить</button><button className={styles.button} onClick={()=>void share()} disabled={sharing}>{sharing?"Создаём…":"Сгенерировать ссылку"}</button><button className={styles.button} onClick={()=>void copy()} disabled={!data}>{copied?"Скопировано":"Скопировать JSON"}</button><button className={styles.button} onClick={download} disabled={!data}>Скачать JSON</button></div></header>
  {error&&<div className={`${styles.notice} ${styles.error}`}>{error}</div>}
  {shareUrl&&<section className={styles.section}><h2>Ссылка для диагностики</h2><p>Действует 6 часов. Пришли мне эту ссылку целиком — она открывает актуальный безопасный JSON без API-ключей, паролей, текстов переписки, traceback и персональных данных.</p><code style={{wordBreak:"break-all"}}>{shareUrl}</code><div className={styles.actions}><button className={styles.button} onClick={()=>void navigator.clipboard.writeText(shareUrl)}>Скопировать ссылку</button></div></section>}
  {data&&<>
   <section className={styles.section}><h2>Сводка</h2><table className={styles.table}><tbody><tr><td>Release / deploy</td><td><b>{data.summary.release_gate_failed?"ОШИБКА":data.release_status?.status==="passed"?"PASS":"нет данных"}</b></td></tr><tr><td>Открытые системные ошибки</td><td><b>{data.summary.open_system_issues}</b></td></tr><tr><td>Последние неудачные генерации</td><td><b>{data.summary.recent_failed_generations}</b></td></tr><tr><td>Проблемные провайдеры</td><td><b>{data.summary.unhealthy_providers} / {data.summary.providers_total}</b></td></tr><tr><td>Доступные модели</td><td><b>{data.summary.routable_models} / {data.summary.models_total}</b></td></tr><tr><td>Зависшие генерации</td><td><b>{data.summary.stuck_generations}</b></td></tr><tr><td>Просроченные резервы</td><td><b>{data.summary.stale_customer_reservations}</b></td></tr><tr><td>Снимок</td><td>{new Date(data.generated_at).toLocaleString("ru-RU")}</td></tr></tbody></table></section>
   <section className={styles.section}><h2>Готовность клиентского чата · последние {data.chat_readiness.window_hours} ч</h2><table className={styles.table}><tbody><tr><td>Успешность завершённых запросов</td><td><b>{data.chat_readiness.success_rate_percent}%</b></td></tr><tr><td>Успешные генерации</td><td><b>{data.chat_readiness.completed_generations}</b></td></tr><tr><td>Failed / cancelled</td><td><b>{data.chat_readiness.failed_generations} / {data.chat_readiness.cancelled_generations}</b></td></tr><tr><td>Preflight failed</td><td><b>{data.chat_readiness.preflight_failed}</b></td></tr><tr><td>Зависшие queued/running &gt;10 мин</td><td><b>{data.chat_readiness.stuck_generations}</b></td></tr><tr><td>Активные / просроченные резервы</td><td><b>{data.chat_readiness.active_customer_reservations} / {data.chat_readiness.stale_customer_reservations}</b></td></tr><tr><td>Кошельки с доступным балансом</td><td><b>{data.chat_readiness.wallets_with_positive_balance} / {data.chat_readiness.wallets_total}</b></td></tr><tr><td>Кошельки без доступного баланса</td><td><b>{data.chat_readiness.wallets_without_available_balance}</b></td></tr></tbody></table></section>
   {data.release_status&&<section className={styles.section}><h2>Последнее обновление / release gate / chat smoke</h2><table className={styles.table}><tbody><tr><td>Статус</td><td><b>{data.release_status.status}</b></td></tr><tr><td>Этап</td><td>{data.release_status.phase||"—"}</td></tr><tr><td>Exit code</td><td>{data.release_status.exit_code??"—"}</td></tr><tr><td>Commit</td><td><code>{data.release_status.commit||"—"}</code></td></tr><tr><td>Время</td><td>{data.release_status.occurred_at||"—"}</td></tr><tr><td>Лог</td><td>{data.release_status.log_file||"—"}</td></tr></tbody></table>{data.release_status.failures.length>0&&<div><h3>Краткая выжимка</h3><pre style={{whiteSpace:"pre-wrap",wordBreak:"break-word"}}>{data.release_status.failures.join("\n")}</pre></div>}</section>}
   <section className={styles.section}><h2>AI-провайдеры и ключи</h2><table className={styles.table}><thead><tr><th>Провайдер</th><th>Client ready</th><th>Health</th><th>Сбои</th><th>Ключи</th><th>Ошибки ключей</th><th>Задержка</th></tr></thead><tbody>{data.providers.map((p)=><tr key={p.provider}><td>{p.provider}</td><td><b>{p.customer_ready?"READY":"BLOCKED"}</b></td><td>{p.health}{p.emergency_disabled?" · emergency off":""}</td><td>{p.consecutive_failures}</td><td>healthy {p.keys.healthy??0} · unknown {p.keys.unknown??0} · degraded {p.keys.degraded??0}</td><td>{Object.entries(p.key_error_codes).map(([code,count])=>`${code} ×${count}`).join(" · ")||"—"}</td><td>{p.last_latency_ms==null?"—":`${p.last_latency_ms} мс`}</td></tr>)}</tbody></table></section>
   <section className={styles.section}><h2>Модели / routing readiness</h2><table className={styles.table}><thead><tr><th>Модель</th><th>Провайдер</th><th>Состояние</th><th>Версия</th><th>Ключи</th><th>Цена</th><th>Причины блокировки / предупреждения</th></tr></thead><tbody>{data.models.map(model=><tr key={model.model}><td><b>{model.display_name}</b><br/><code>{model.model}</code></td><td>{model.provider}<br/><small>{model.provider_health}</small></td><td>{model.ready?"READY":"BLOCKED"}</td><td>{model.current_version||"—"}</td><td>{model.healthy_keys}</td><td>{model.price_configured?"OK":model.price_error||"нет"}</td><td>{model.reasons.join(" · ")||"—"}{model.warnings.length>0&&<><br/><small>warning: {model.warnings.join(" · ")}</small></>}</td></tr>)}</tbody></table></section>
   <section className={styles.section}><h2>Системные и frontend ошибки</h2><table className={styles.table}><thead><tr><th>Последняя</th><th>Статус</th><th>Ошибка</th><th>Источник</th><th>Повторов</th><th>Correlation ID</th></tr></thead><tbody>{data.system_issues.length===0?<tr><td colSpan={6}>Ошибок нет</td></tr>:data.system_issues.map((issue)=><tr key={issue.fingerprint}><td>{new Date(issue.last_seen_at).toLocaleString("ru-RU")}</td><td>{issue.severity} · {issue.status}</td><td><b>{issue.exception_type}</b><br/><small>{issue.summary}</small></td><td><code>{issue.source}</code></td><td>{issue.occurrences}</td><td><code>{issue.correlation_id||"—"}</code></td></tr>)}</tbody></table></section>
   <section className={styles.section}><h2>Неудачные генерации</h2><table className={styles.table}><thead><tr><th>Время</th><th>Correlation ID</th><th>Код</th><th>Запрошенная / routed модель</th><th>Провайдер</th><th>Попытки</th></tr></thead><tbody>{data.recent_chat_errors.length===0?<tr><td colSpan={6}>Ошибок нет</td></tr>:data.recent_chat_errors.map((g)=><tr key={g.generation_id}><td>{new Date(g.created_at).toLocaleString("ru-RU")}</td><td><code>{g.correlation_id}</code></td><td><code>{g.internal_error_code||"—"}</code></td><td>{g.requested_model||"—"} / {g.routed_model||"—"}</td><td>{g.provider||"—"}</td><td>{g.attempts.map(a=>`${a.sequence}:${a.provider__slug}:${a.model_slug}:${a.error_code||a.state}`).join(" · ")||"—"}</td></tr>)}</tbody></table></section>
  </>}
 </>;
}
