from django.urls import path

from .views import (
    AuditView,
    BackupActionView,
    BackupView,
    ExecutiveOverviewView,
    FeatureFlagDetailView,
    FeatureFlagView,
    FinanceControlView,
    IncidentControlView,
    LedgerInspectorView,
    PaymentInspectorView,
    PricingControlView,
    ProviderBulkActionView,
    ProviderControlView,
    QualityControlView,
    ReleaseRolloutView,
    ReleaseView,
    RequestInspectorView,
    SecurityEventActionView,
    SecurityEventView,
    SupportControlView,
    SupportStatusView,
    UserOrganizationView,
)

urlpatterns = [
    path("overview/", ExecutiveOverviewView.as_view(), name="admin-overview"),
    path("finance/", FinanceControlView.as_view(), name="admin-finance"),
    path("payments/", PaymentInspectorView.as_view(), name="admin-payments"),
    path("ledger/", LedgerInspectorView.as_view(), name="admin-ledger"),
    path("pricing/", PricingControlView.as_view(), name="admin-pricing"),
    path("quality/", QualityControlView.as_view(), name="admin-quality"),
    path("incidents/", IncidentControlView.as_view(), name="admin-incidents"),
    path("providers/", ProviderControlView.as_view(), name="admin-providers"),
    path(
        "providers/bulk-action/",
        ProviderBulkActionView.as_view(),
        name="admin-provider-bulk-action",
    ),
    path("requests/", RequestInspectorView.as_view(), name="admin-requests"),
    path("users-organizations/", UserOrganizationView.as_view(), name="admin-users-orgs"),
    path("security/", SecurityEventView.as_view(), name="admin-security"),
    path(
        "security/<uuid:event_id>/action/",
        SecurityEventActionView.as_view(),
        name="admin-security-action",
    ),
    path("releases/", ReleaseView.as_view(), name="admin-releases"),
    path(
        "releases/<uuid:release_id>/rollout/",
        ReleaseRolloutView.as_view(),
        name="admin-release-rollout",
    ),
    path("backups/", BackupView.as_view(), name="admin-backups"),
    path(
        "backups/<uuid:backup_id>/action/",
        BackupActionView.as_view(),
        name="admin-backup-action",
    ),
    path("support/", SupportControlView.as_view(), name="admin-support"),
    path(
        "support/<uuid:support_id>/status/",
        SupportStatusView.as_view(),
        name="admin-support-status",
    ),
    path("feature-flags/", FeatureFlagView.as_view(), name="admin-feature-flags"),
    path(
        "feature-flags/<slug:key>/",
        FeatureFlagDetailView.as_view(),
        name="admin-feature-flag-detail",
    ),
    path("audit/", AuditView.as_view(), name="admin-audit"),
]
