"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";
import styles from "./events.module.css";

type Agent={id:string;name:string;status:string;objective:string};
type Team={id:string;name:string;active:boolean;objective:string};
type Hook={id:string;agent:string|null;team:string|null;subject_name:string;subject_type:"agent"|"team";name:string;objective:string;enabled:boolean;endpoint:string;last_used_at:string|null;created_at:string;secret?:string;secret_notice?:string};

export default function EventsPage(){
 const[agents,setAgents]=useState<Agent[]>([]);const[teams,setTeams]=useState<Team[]>([]);const[hooks,setHooks]=useState<Hook[]>([]);
 const[subjectType,setSubjectType]=useState<"agent"|"team">("agent");const[subject,setSubject]=useState("");const[name,setName]=useState("");const[objective,setObjective]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[secret,setSecret]=useState<{id:string;value:string}|null>(null);
 const load=async()=>{try{const[a,t,h]=await Promise.all([api<Agent[]>("/agents/"),api<Team[]>("/agent-teams/"),api<Hook[]>("/agent-webhooks/")]);setAgents(a.filter(x=>x.status==="active"));setTeams(t.filter(x=>x.active));setHooks(h);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить события")}};
 useEffect(()=>{void load()},[]);
 const subjects=useMemo(()=>subjectType==="agent"?agents:teams,[subjectType,agents,teams]);
 useEffect(()=>{if(subject&&!subjects.some(item=>item.id===subject))setSubject("")},[subject,subjects]);
 const absolute=(path:string)=>typeof window==="undefined"?path:`${window.location.origin}${path}`;
 const create=async()=>{if(!subject){setError("Выберите сотрудника или команду");return}setBusy("create");setError("");setSecret(null);try{const payload:Record<string,unknown>={name:name.trim()||"Внешнее событие",objective:objective.trim()};payload[subjectType]=subject;const created=await api<Hook>("/agent-webhooks/",{method:"POST",body:JSON.stringify(payload)});if(created.secret)setSecret({id:created.id,value:created.secret});setName("");setObjective("");setSubject("");await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось создать webhook")}finally{setBusy("")}};
 const toggle=async(item:Hook)=>{setBusy(item.id);setError("");try{await api<Hook>(`/agent-webhooks/${item.id}/`,{method:"PATCH",body:JSON.stringify({enabled:!item.enabled})});await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось изменить webhook")}finally{setBusy("")}};
 const rotate=async(item:Hook)=>{if(!window.confirm("Старый секрет сразу перестанет работать. Продолжить?"))return;setBusy(item.id);setError("");try{const updated=await api<Hook>(`/agent-webhooks/${item.id}/rotate-secret/`,{method:"POST"});if(updated.secret)setSecret({id:item.id,value:updated.secret});await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось заменить секрет")}finally{setBusy("")}};
 const remove=async(item:Hook)=>{if(!window.confirm(`Удалить событие «${item.name}»?`))return;setBusy(item.id);setError("");try{await api(`/agent-webhooks/${item.id}/`,{method:"DELETE"});if(secret?.id===item.id)setSecret(null);await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось удалить webhook")}finally{setBusy("")}};
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value)}catch{setError("Не удалось скопировать автоматически")}};
 const fmt=(value:string|null)=>value?new Date(value).toLocaleString("ru-RU"):"ещё не использовался";
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.top}><div><span className={styles.eyebrow}>AI WORKSPACE · EVENT AUTONOMY</span><h1>Запуск по событию</h1><p>Подключите CRM, форму сайта, интернет-магазин или любой сервис с webhook. Каждое уникальное событие запускает сотрудника или команду один раз; повторная доставка с тем же Event ID не создаст повторное списание.</p></div><div className={styles.topLinks}><Link href="/app/agents">Агенты</Link><Link href="/app/schedules">Расписания</Link></div></header>
  {error&&<div className={styles.notice} role="alert">{error}</div>}
  {secret&&<section className={styles.secretCard}><strong>Сохраните секрет сейчас</strong><p>После закрытия этого блока секрет больше не будет показан. Передавайте его в заголовке <code>X-Agent-Webhook-Secret</code>.</p><div className={styles.secretValue}><code>{secret.value}</code><button className={styles.button} onClick={()=>void copy(secret.value)}>Копировать</button></div><button className={`${styles.button} ${styles.secretDismiss}`} onClick={()=>setSecret(null)}>Я сохранил</button></section>}
  <section className={styles.card}><h2>Новое событие</h2><div className={styles.two}><label className={styles.field}>Кого запускать<select value={subjectType} onChange={e=>setSubjectType(e.target.value as "agent"|"team")}><option value="agent">Сотрудника</option><option value="team">Команду</option></select></label><label className={styles.field}>{subjectType==="agent"?"AI-сотрудник":"Команда"}<select value={subject} onChange={e=>setSubject(e.target.value)}><option value="">Выберите</option>{subjects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><label className={styles.field}>Название<input value={name} onChange={e=>setName(e.target.value)} placeholder="Например: Новая заявка с сайта"/></label><label className={styles.field}>Что делать при событии<textarea rows={4} value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Например: проанализировать заявку, определить приоритет и подготовить ответ менеджеру"/></label><div className={styles.formActions}><button className={styles.primary} disabled={busy==="create"||!subject} onClick={()=>void create()}>{busy==="create"?"Создаём…":"Создать webhook"}</button></div></section>
  <section className={styles.listSection}><h2>Подключённые события</h2>{!hooks.length?<div className={styles.empty}>Webhook-событий пока нет. Создайте первое правило выше — секрет будет показан только один раз.</div>:<div className={styles.list}>{hooks.map(item=><article key={item.id} className={styles.eventCard}><div className={styles.eventGrid}><div><div className={styles.titleRow}><strong>{item.name}</strong><span className={`${styles.status} ${!item.enabled?styles.statusPaused:""}`}>{item.enabled?"Включено":"Пауза"}</span></div><div className={styles.meta}>{item.subject_type==="agent"?"Сотрудник":"Команда"}: {item.subject_name}</div>{item.objective&&<p className={styles.objective}>{item.objective}</p>}<div className={styles.submeta}>Последнее событие: {fmt(item.last_used_at)}</div><div className={styles.endpoint}><code>{absolute(item.endpoint)}</code><button className={styles.button} onClick={()=>void copy(absolute(item.endpoint))}>Копировать URL</button></div><p className={styles.hint}>POST JSON · заголовки: <code>X-Agent-Webhook-Secret</code> и уникальный <code>Idempotency-Key</code> или <code>X-Event-ID</code>.</p></div><div className={styles.actions}><button className={styles.button} disabled={!!busy} onClick={()=>void toggle(item)}>{item.enabled?"Пауза":"Включить"}</button><button className={styles.button} disabled={!!busy} onClick={()=>void rotate(item)}>Новый секрет</button><button className={styles.danger} disabled={!!busy} onClick={()=>void remove(item)}>Удалить</button></div></div></article>)}</div>}</section>
 </div></main>;
}
