"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";

type Agent={id:string;name:string;status:string;objective:string};
type Team={id:string;name:string;active:boolean;objective:string};
type Hook={id:string;agent:string|null;team:string|null;subject_name:string;subject_type:"agent"|"team";name:string;objective:string;enabled:boolean;endpoint:string;last_used_at:string|null;created_at:string;secret?:string;secret_notice?:string};

export default function EventsPage(){
 const[agents,setAgents]=useState<Agent[]>([]);const[teams,setTeams]=useState<Team[]>([]);const[hooks,setHooks]=useState<Hook[]>([]);
 const[subjectType,setSubjectType]=useState<"agent"|"team">("agent");const[subject,setSubject]=useState("");const[name,setName]=useState("");const[objective,setObjective]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[secret,setSecret]=useState<{id:string;value:string}|null>(null);
 const load=async()=>{try{const[a,t,h]=await Promise.all([api<Agent[]>("/agents/"),api<Team[]>("/agent-teams/"),api<Hook[]>("/agent-webhooks/")]);setAgents(a.filter(x=>x.status==="active"));setTeams(t.filter(x=>x.active));setHooks(h);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить события")}};
 useEffect(()=>{void load()},[]);
 const subjects=useMemo(()=>subjectType==="agent"?agents:teams,[subjectType,agents,teams]);
 useEffect(()=>{if(subject&&!subjects.some(item=>item.id===subject))setSubject("")},[subject,subjects]);
 const absolute=(path:string)=>typeof window==="undefined"?path:`${window.location.origin}${path}`;
 const create=async()=>{if(!subject){setError("Выберите сотрудника или команду");return}setBusy("create");setError("");setSecret(null);try{const payload:Record<string,unknown>={name:name.trim()||"Внешнее событие",objective:objective.trim()};payload[subjectType]=subject;const created=await api<Hook>("/agent-webhooks/",{method:"POST",body:JSON.stringify(payload)});if(created.secret)setSecret({id:created.id,value:created.secret});setName("");setObjective("");setSubject("");await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось создать webhook")}finally{setBusy("")}};
 const toggle=async(item:Hook)=>{setBusy(item.id);setError("");try{await api<Hook>(`/agent-webhooks/${item.id}/`,{method:"PATCH",body:JSON.stringify({enabled:!item.enabled})});await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось изменить webhook")}finally{setBusy("")}};
 const rotate=async(item:Hook)=>{if(!window.confirm("Старый секрет сразу перестанет работать. Продолжить?"))return;setBusy(item.id);setError("");try{const updated=await api<Hook>(`/agent-webhooks/${item.id}/rotate-secret/`,{method:"POST"});if(updated.secret)setSecret({id:item.id,value:updated.secret});await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось заменить секрет")}finally{setBusy("")}};
 const remove=async(item:Hook)=>{if(!window.confirm(`Удалить событие «${item.name}»?`))return;setBusy(item.id);setError("");try{await api(`/agent-webhooks/${item.id}/`,{method:"DELETE"});if(secret?.id===item.id)setSecret(null);await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось удалить webhook")}finally{setBusy("")}};
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value)}catch{setError("Не удалось скопировать автоматически")}};
 const fmt=(value:string|null)=>value?new Date(value).toLocaleString("ru-RU"):"ещё не использовался";
 return <main style={{maxWidth:1120,margin:"0 auto",padding:"32px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:30}}><div><div style={{fontSize:13,opacity:.6,marginBottom:8}}>AI WORKSPACE · EVENT AUTONOMY</div><h1 style={{fontSize:38,margin:"0 0 10px"}}>Запуск по событию</h1><p style={{maxWidth:760,opacity:.72,fontSize:17}}>Подключите CRM, форму сайта, интернет-магазин или любой сервис с webhook. Каждое уникальное событие запускает сотрудника или команду один раз; повторная доставка с тем же Event ID не создаст повторное списание.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link href="/app/agents" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Агенты</Link><Link href="/app/schedules" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Расписания</Link></div></header>
  {error&&<div style={{padding:13,border:"1px solid #cb747a",borderRadius:12,marginBottom:16}}>{error}</div>}
  {secret&&<section style={{border:"1px solid #d6b45e",borderRadius:18,padding:18,marginBottom:20}}><strong>Сохраните секрет сейчас</strong><p style={{opacity:.7}}>После закрытия этого блока секрет больше не будет показан. Передавайте его в заголовке <code>X-Agent-Webhook-Secret</code>.</p><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><code style={{padding:12,border:"1px solid #ddd",borderRadius:10,overflow:"auto"}}>{secret.value}</code><button onClick={()=>void copy(secret.value)} style={{padding:"9px 13px",border:"1px solid #ccc",borderRadius:10}}>Копировать</button></div><button onClick={()=>setSecret(null)} style={{marginTop:10,padding:"8px 12px",border:"1px solid #ccc",borderRadius:9,background:"transparent"}}>Я сохранил</button></section>}
  <section style={{border:"1px solid #ddd",borderRadius:22,padding:22,marginBottom:30}}><h2 style={{marginTop:0}}>Новое событие</h2><div style={{display:"grid",gridTemplateColumns:"160px minmax(220px,1fr)",gap:12,marginBottom:12}}><label style={{display:"grid",gap:6}}>Кого запускать<select value={subjectType} onChange={e=>setSubjectType(e.target.value as "agent"|"team")} style={{padding:11,borderRadius:10,border:"1px solid #ccc"}}><option value="agent">Сотрудника</option><option value="team">Команду</option></select></label><label style={{display:"grid",gap:6}}>{subjectType==="agent"?"AI-сотрудник":"Команда"}<select value={subject} onChange={e=>setSubject(e.target.value)} style={{padding:11,borderRadius:10,border:"1px solid #ccc"}}><option value="">Выберите</option>{subjects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><label style={{display:"grid",gap:6,marginBottom:12}}>Название<input value={name} onChange={e=>setName(e.target.value)} placeholder="Например: Новая заявка с сайта" style={{padding:11,borderRadius:10,border:"1px solid #ccc"}}/></label><label style={{display:"grid",gap:6}}>Что делать при событии<textarea rows={4} value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Например: проанализировать заявку, определить приоритет и подготовить ответ менеджеру" style={{padding:12,borderRadius:11,border:"1px solid #ccc",resize:"vertical"}}/></label><div style={{display:"flex",justifyContent:"flex-end",marginTop:12}}><button disabled={busy==="create"||!subject} onClick={()=>void create()} style={{padding:"11px 16px",border:0,borderRadius:11,fontWeight:700}}>{busy==="create"?"Создаём…":"Создать webhook"}</button></div></section>
  <section><h2>Подключённые события</h2>{!hooks.length?<div style={{border:"1px dashed #bbb",borderRadius:18,padding:30,textAlign:"center",opacity:.7}}>Webhook-событий пока нет.</div>:<div style={{display:"grid",gap:12}}>{hooks.map(item=><article key={item.id} style={{border:"1px solid #ddd",borderRadius:17,padding:18}}><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:16}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:19}}>{item.name}</strong><span style={{fontSize:12,padding:"4px 8px",borderRadius:999,border:"1px solid #ddd"}}>{item.enabled?"Включено":"Пауза"}</span></div><div style={{opacity:.65,marginTop:5}}>{item.subject_type==="agent"?"Сотрудник":"Команда"}: {item.subject_name}</div>{item.objective&&<p style={{opacity:.72,margin:"8px 0"}}>{item.objective}</p>}<div style={{fontSize:12,opacity:.58}}>Последнее событие: {fmt(item.last_used_at)}</div><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,marginTop:10}}><code style={{padding:10,border:"1px solid #ddd",borderRadius:9,overflow:"auto"}}>{absolute(item.endpoint)}</code><button onClick={()=>void copy(absolute(item.endpoint))} style={{padding:"8px 11px",border:"1px solid #ccc",borderRadius:9}}>Копировать URL</button></div><p style={{fontSize:12,opacity:.58,marginBottom:0}}>POST JSON · заголовки: <code>X-Agent-Webhook-Secret</code> и уникальный <code>Idempotency-Key</code> или <code>X-Event-ID</code>.</p></div><div style={{display:"flex",gap:8,alignItems:"flex-start",flexWrap:"wrap",justifyContent:"flex-end"}}><button disabled={!!busy} onClick={()=>void toggle(item)} style={{padding:"9px 12px",border:"1px solid #ccc",borderRadius:9,background:"transparent"}}>{item.enabled?"Пауза":"Включить"}</button><button disabled={!!busy} onClick={()=>void rotate(item)} style={{padding:"9px 12px",border:"1px solid #ccc",borderRadius:9,background:"transparent"}}>Новый секрет</button><button disabled={!!busy} onClick={()=>void remove(item)} style={{padding:"9px 12px",border:"1px solid #d99",borderRadius:9,background:"transparent"}}>Удалить</button></div></div></article>)}</div>}</section>
 </main>;
}
