"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {ApiError,api} from "../../../lib/api";
import type {Wallet} from "../../../lib/types";
import {trackProductEvent} from "../../components/ProductAnalytics";
import styles from "./wallet.module.css";

type Payment={id:string;amount_rub:string;currency:string;status:"created"|"pending"|"succeeded"|"canceled";confirmation_url:string;receipt_status:string;credited_at:string|null;created_at:string};
type RefundRequest={id:string;payment_id:string;refund_id:string|null;amount_rub:string;reason:string;status:string;admin_comment:string;held_at:string|null;resolved_at:string|null;created_at:string;updated_at:string};
const money=(value:string|number|null|undefined)=>`${Number(value??0).toFixed(2).replace(".",",")} ₽`;
const paymentStatus:Record<string,string>={created:"Статус уточняется",pending:"Ожидает оплаты",succeeded:"Оплачен",canceled:"Отменён"};
const receiptStatus:Record<string,string>={not_required:"Не требуется",pending:"Ожидается",succeeded:"Сформирован",failed:"Ошибка",legal_review:"Нужна проверка"};
const refundStatus:Record<string,string>={pending:"На рассмотрении",approved:"Одобрен",processing:"Статус уточняется",succeeded:"Возвращён",rejected:"Отклонён",failed:"Ошибка возврата"};
const ledgerKind:Record<string,string>={credit:"Пополнение",reserve:"Резерв",release:"Возврат резерва",debit:"Списание",refund:"Удержание возврата",adjustment:"Корректировка"};
const topupStorageKey=(amount:string)=>`pending-topup-key:${amount}`;
const stableTopupKey=(amount:string)=>{const storageKey=topupStorageKey(amount);const existing=window.sessionStorage.getItem(storageKey);if(existing)return existing;const created=`wallet:${crypto.randomUUID()}`;window.sessionStorage.setItem(storageKey,created);return created;};
const refundRequestStorageKey=(paymentId:string,amount:string)=>`pending-refund-request-key:${paymentId}:${amount}`;
const stableRefundRequestKey=(paymentId:string,amount:string)=>{const storageKey=refundRequestStorageKey(paymentId,amount);const existing=window.sessionStorage.getItem(storageKey);if(existing)return existing;const created=`refund-request:${crypto.randomUUID()}`;window.sessionStorage.setItem(storageKey,created);return created;};
const signedLedger=(kind:string,amount:string)=>{const negative=["reserve","debit","refund"].includes(kind);const positive=["credit","release"].includes(kind);return `${negative?"−":positive?"+":""}${money(amount)}`;};

export default function WalletPage(){
 const router=useRouter();
 const [wallet,setWallet]=useState<Wallet|null>(null);const [payments,setPayments]=useState<Payment[]>([]);const [refunds,setRefunds]=useState<RefundRequest[]>([]);const [amount,setAmount]=useState("500");const [refundPayment,setRefundPayment]=useState("");const [refundAmount,setRefundAmount]=useState("");const [refundReason,setRefundReason]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const load=async()=>{try{const[w,p,r]=await Promise.all([api<Wallet>("/wallet/"),api<Payment[]>("/payments/"),api<RefundRequest[]>("/refund-requests/")]);setWallet(w);setPayments(p);setRefunds(r);if(!refundPayment){const latest=p.find(item=>item.status==="succeeded");if(latest)setRefundPayment(latest.id);}}catch(reason){if(reason instanceof ApiError&&[401,403].includes(reason.status))router.replace("/login");else setError(reason instanceof Error?reason.message:"Не удалось загрузить кошелёк");}};
 useEffect(()=>{void load();},[]);
 const amountNumber=Number(amount);const topupInvalid=!Number.isFinite(amountNumber)||amountNumber<100||amountNumber>100000;
 const successfulPayments=payments.filter(item=>item.status==="succeeded");const selectedPayment=useMemo(()=>successfulPayments.find(item=>item.id===refundPayment)??null,[successfulPayments,refundPayment]);const refundNumber=Number(refundAmount);const refundInvalid=!refundPayment||!Number.isFinite(refundNumber)||refundNumber<1||Boolean(selectedPayment&&refundNumber>Number(selectedPayment.amount_rub));
 const topup=async()=>{if(topupInvalid)return;setBusy(true);setError("");const requestedAmount=amount;const key=stableTopupKey(requestedAmount);try{const payment=await api<Payment>("/payments/",{method:"POST",headers:{"Idempotency-Key":key},body:JSON.stringify({amount_rub:requestedAmount})});sessionStorage.removeItem(topupStorageKey(requestedAmount));void trackProductEvent("payment_started",{amount_rub:requestedAmount,payment_id:payment.id});sessionStorage.setItem("pending-payment-id",payment.id);if(payment.confirmation_url)window.location.assign(payment.confirmation_url);else await load();}catch(reason){void trackProductEvent("payment_failed",{amount_rub:requestedAmount,stage:"create"});setError(`${reason instanceof Error?reason.message:"Не удалось создать платёж"} Повторите попытку: будет продолжена та же операция, второй платёж не создастся.`);}finally{setBusy(false);}};
 const requestRefund=async()=>{if(refundInvalid)return;setBusy(true);setError("");const paymentId=refundPayment;const requestedAmount=refundAmount;const key=stableRefundRequestKey(paymentId,requestedAmount);try{await api<RefundRequest>("/refund-requests/",{method:"POST",headers:{"Idempotency-Key":key},body:JSON.stringify({payment_id:paymentId,amount_rub:requestedAmount,reason:refundReason})});sessionStorage.removeItem(refundRequestStorageKey(paymentId,requestedAmount));setRefundAmount("");setRefundReason("");await load();}catch(reason){setError(`${reason instanceof Error?reason.message:"Не удалось отправить заявку на возврат"} Повторная отправка продолжит ту же заявку.`);}finally{setBusy(false);}};
 const hasUnknownMoneyOperation=payments.some(item=>item.status==="created")||refunds.some(item=>["approved","processing"].includes(item.status));
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.top}><div><h1>Баланс и платежи</h1><p>Пополнение, списания и возвраты в одном месте.</p></div><Link href="/app">← Рабочее пространство</Link></header>
  {error&&<div className={`${styles.notice} ${styles.error}`} role="alert">{error}</div>}
  {hasUnknownMoneyOperation&&<div className={styles.notice}><b>Есть операция со статусом, который уточняется.</b> Не создавайте новую операцию вместо неё: система автоматически сверяется с платёжным провайдером.</div>}
  <div className={styles.notice}><b>Только разовое пополнение.</b> Карта не сохраняется для автосписаний и автопродление не подключается.</div>
  <section className={styles.hero}><div className={styles.balance}><small>Доступно</small><strong>{money(wallet?.available_rub)}</strong><div className={styles.split}><span>Оплачено: {money(wallet?.paid_rub)}</span><span>Промо: {money(wallet?.promo_rub)}</span><span>В резерве: {money(wallet?.reserved_rub)}</span></div><small className={styles.explain}>Перед AI-запросом сумма временно резервируется. После подтверждения расхода списывается фактическая стоимость, остаток возвращается. Без подтверждённого расхода LLM списание равно 0 ₽.</small></div><div className={styles.card}><h2>Пополнить</h2><div className={styles.amounts}>{[300,500,1000,3000].map(item=><button type="button" key={item} className={amount===String(item)?styles.active:""} onClick={()=>setAmount(String(item))}>{item.toLocaleString("ru-RU")} ₽</button>)}</div><label htmlFor="topup-amount">Сумма, ₽</label><input id="topup-amount" className={styles.input} type="number" min="100" max="100000" step="1" value={amount} onChange={e=>setAmount(e.target.value)} aria-invalid={topupInvalid}/>{topupInvalid&&<small className={styles.validation}>Допустимая сумма: от 100 до 100 000 ₽.</small>}<button className={`${styles.button} ${styles.primary}`} disabled={busy||topupInvalid} onClick={topup}>{busy?"Обрабатываем…":`Пополнить на ${money(amount)}`}</button><small className={styles.hint}>Это не подписка. Повторного автоматического списания не будет.</small></div></section>
  <section className={styles.grid}><div className={styles.card}><h2>История платежей</h2><div className={styles.list}>{payments.length===0?<p>Платежей пока нет.</p>:payments.map(item=><div className={styles.row} key={item.id}><div><b>{money(item.amount_rub)}</b><small>{new Date(item.created_at).toLocaleString("ru-RU")} · чек: {receiptStatus[item.receipt_status]??"Проверяется"}</small></div><span className={`${styles.status} ${item.status==="succeeded"?styles.ok:item.status==="canceled"?styles.bad:""}`}>{paymentStatus[item.status]??"Обрабатывается"}</span></div>)}</div></div><div className={styles.card}><h2>Операции баланса</h2><div className={styles.list}>{wallet?.entries.length?wallet.entries.slice(0,30).map(entry=><div className={styles.row} key={entry.id}><div><b>{ledgerKind[entry.kind]??"Операция"}</b><small>{new Date(entry.created_at).toLocaleString("ru-RU")}</small></div><strong>{signedLedger(entry.kind,entry.amount_rub)}</strong></div>):<p>Операций пока нет.</p>}</div></div></section>
  <section className={styles.grid}><div className={styles.card}><h2>Запросить возврат</h2><p>Вернуть можно только неиспользованный оплаченный баланс. Сумма заявки сразу перестаёт быть доступной для новых запросов до решения по возврату.</p>{successfulPayments.length===0?<p>Нет успешных платежей, доступных для возврата.</p>:<><label htmlFor="refund-payment">Платёж</label><select id="refund-payment" className={styles.input} value={refundPayment} onChange={e=>setRefundPayment(e.target.value)}>{successfulPayments.map(item=><option key={item.id} value={item.id}>{money(item.amount_rub)} · {new Date(item.created_at).toLocaleDateString("ru-RU")}</option>)}</select><label htmlFor="refund-amount">Сумма возврата, ₽</label><input id="refund-amount" className={styles.input} type="number" min="1" max={selectedPayment?.amount_rub} step="0.01" value={refundAmount} onChange={e=>setRefundAmount(e.target.value)} placeholder="Например, 500" aria-invalid={Boolean(refundAmount)&&refundInvalid}/>{selectedPayment&&<small className={styles.hint}>Исходный платёж: {money(selectedPayment.amount_rub)}. Фактически доступный к возврату остаток дополнительно проверит сервер.</small>}<label htmlFor="refund-reason">Причина</label><textarea id="refund-reason" className={styles.input} rows={3} value={refundReason} onChange={e=>setRefundReason(e.target.value)} placeholder="Кратко укажите причину"/><button className={`${styles.button} ${styles.primary}`} disabled={busy||refundInvalid} onClick={requestRefund}>Отправить заявку</button></>}</div><div className={styles.card}><h2>Заявки на возврат</h2><div className={styles.list}>{refunds.length===0?<p>Заявок пока нет.</p>:refunds.map(item=><div className={styles.row} key={item.id}><div><b>{money(item.amount_rub)}</b><small>{new Date(item.created_at).toLocaleString("ru-RU")}{item.admin_comment?` · ${item.admin_comment}`:""}</small></div><span className={`${styles.status} ${item.status==="succeeded"?styles.ok:["rejected","failed"].includes(item.status)?styles.bad:""}`}>{refundStatus[item.status]??item.status}</span></div>)}</div></div></section>
 </div></main>;
}
