import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("role", models.CharField(blank=True, max_length=160)),
                ("objective", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("autonomy", models.CharField(choices=[("controlled", "Контролируемый"), ("semi_autonomous", "Полуавтономный"), ("autonomous", "Автономный")], default="controlled", max_length=24)),
                ("status", models.CharField(choices=[("draft", "Черновик"), ("active", "Активен"), ("paused", "Приостановлен"), ("archived", "Архив")], default="draft", max_length=16)),
                ("system_level", models.CharField(default="balanced", max_length=16)),
                ("tool_policy", models.JSONField(blank=True, default=dict)),
                ("graph", models.JSONField(blank=True, default=dict)),
                ("memory_policy", models.JSONField(blank=True, default=dict)),
                ("max_cost_rub_per_run", models.DecimalField(decimal_places=4, default=10, max_digits=12)),
                ("max_cost_rub_per_day", models.DecimalField(decimal_places=4, default=100, max_digits=12)),
                ("max_cost_rub_per_month", models.DecimalField(decimal_places=4, default=1500, max_digits=12)),
                ("max_steps", models.PositiveIntegerField(default=50)),
                ("max_tool_calls", models.PositiveIntegerField(default=50)),
                ("max_handoffs", models.PositiveIntegerField(default=20)),
                ("max_retries_per_step", models.PositiveIntegerField(default=3)),
                ("max_runtime_seconds", models.PositiveIntegerField(default=3600)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agents", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agents", to="projects.project")),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="AgentTeam",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("objective", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("max_cost_rub_per_run", models.DecimalField(decimal_places=4, default=50, max_digits=12)),
                ("max_handoffs", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("director", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="directed_teams", to="agents.agent")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_teams", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_teams", to="projects.project")),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("state", models.CharField(choices=[("queued", "В очереди"), ("planning", "Планирование"), ("running", "Выполняется"), ("waiting_tool", "Ожидает инструмент"), ("waiting_approval", "Ожидает подтверждение"), ("reviewing", "Проверка"), ("completed", "Завершён"), ("failed", "Ошибка"), ("canceled", "Отменён"), ("budget_exceeded", "Лимит бюджета")], default="queued", max_length=24)),
                ("objective", models.TextField()),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("output_payload", models.JSONField(blank=True, default=dict)),
                ("plan", models.JSONField(blank=True, default=list)),
                ("cost_reserved_rub", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("cost_actual_rub", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("step_count", models.PositiveIntegerField(default=0)),
                ("tool_call_count", models.PositiveIntegerField(default=0)),
                ("handoff_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=120)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="agents.agent")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_runs", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_runs", to="projects.project")),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="agents.agentteam")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AgentVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="agents.agent")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_agent_versions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-version"]},
        ),
        migrations.CreateModel(
            name="AgentTeamMember",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=160)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("can_delegate", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="team_memberships", to="agents.agent")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="members", to="agents.agentteam")),
            ],
            options={"ordering": ["priority", "role"]},
        ),
        migrations.CreateModel(
            name="AgentStepRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sequence", models.PositiveIntegerField()),
                ("node_id", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=240)),
                ("action_type", models.CharField(max_length=80)),
                ("state", models.CharField(choices=[("pending", "Ожидает"), ("running", "Выполняется"), ("waiting_approval", "Ожидает подтверждение"), ("completed", "Готово"), ("failed", "Ошибка"), ("skipped", "Пропущено")], default="pending", max_length=24)),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("output_payload", models.JSONField(blank=True, default=dict)),
                ("public_log", models.TextField(blank=True)),
                ("cost_rub", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="step_runs", to="agents.agent")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="agents.agentrun")),
            ],
            options={"ordering": ["sequence", "created_at"]},
        ),
        migrations.CreateModel(
            name="AgentApproval",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("action_payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("pending", "Ожидает"), ("approved", "Одобрено"), ("rejected", "Отклонено"), ("expired", "Истекло")], default="pending", max_length=16)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="agent_approval_decisions", to=settings.AUTH_USER_MODEL)),
                ("requested_by_agent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requested_approvals", to="agents.agent")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="agents.agentrun")),
                ("step", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="agents.agentsteprun")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AgentHandoff",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("task", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("from_agent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="handoffs_sent", to="agents.agent")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="handoffs", to="agents.agentrun")),
                ("to_agent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="handoffs_received", to="agents.agent")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="AgentArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("reference", models.CharField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="agents.agentrun")),
                ("step", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="artifacts", to="agents.agentsteprun")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.AddIndex(model_name="agent", index=models.Index(fields=["owner", "status"], name="agents_agen_owner_i_715d33_idx")),
        migrations.AddIndex(model_name="agent", index=models.Index(fields=["project", "status"], name="agents_agen_project_26194c_idx")),
        migrations.AddIndex(model_name="agentrun", index=models.Index(fields=["owner", "state", "created_at"], name="agents_agen_owner_i_15437f_idx")),
        migrations.AddConstraint(model_name="agentversion", constraint=models.UniqueConstraint(fields=("agent", "version"), name="unique_agent_version")),
        migrations.AddConstraint(model_name="agentteammember", constraint=models.UniqueConstraint(fields=("team", "agent"), name="unique_agent_team_member")),
        migrations.AddConstraint(model_name="agentsteprun", constraint=models.UniqueConstraint(fields=("run", "sequence", "attempt"), name="unique_agent_step_attempt")),
        migrations.AddConstraint(model_name="agentrun", constraint=models.CheckConstraint(condition=models.Q(("agent__isnull", False), ("team__isnull", True), _connector="AND") | models.Q(("agent__isnull", True), ("team__isnull", False), _connector="AND"), name="agent_run_exactly_one_subject")),
    ]
