"use client";

import {useEffect,useState} from "react";
import {api} from "../../../lib/api";
import styles from "../admin.module.css";

type UserRow={id:string;email:string;username:string;role:string;status:string;is_staff:boolean;date_joined:string};
type UsersResponse={users:UserRow[];organizations:{id:string;name:string;slug:string;active:boolean;members:number;active_keys:number;created_at:string}[]};
type Adjustment={id:string;direction:string;amount_rub:string;comment:string;admin_id:string;created_at:string};
type WalletState={available_rub:string;reserved_rub:string;paid_rub:string;promo_rub:string};
type Detail={user:{id:string;username:string;email:string;email_verified:boolean;role:string;status:string;date_joined:string;last_login:string|null};wallet:WalletState|null;balance_adjustments:Adjustment[];payments:{id:string;amount_rub:string;status:string;receipt_status:string;created_at:string}[];generations:{id:string;state:string;routed_model:string;provider_slug:string;actual_cost_rub:string|null;error_code:string;created_at:string}[];support:{id:string;subject:string;status:string;created_at:string}[];security_events:{id:string;category:string;severity:string;status:string;summary:string;created_at:string}[];organizations:{organization_id:string;organization__name:string;role:string}[]};
type PromoCreditResult={ok:boolean;amount_rub:string;wallet:WalletState};
const money=(v:string|number|null|undefined)=>`${Number(v??0).toFixed(2).replace(".",",")} ₽`;
const userStatus:Record<string,string>={active:"Активен",blocked:"Заблокирован",deleted:"Удалён"};
const userRole:Record<string,string>={user:"Пользователь",platform_admin:"Администратор платформы",admin:"Администратор"};
const paymentStatus:Record<string,string>={created:"Создан",pending:"Ожидает оплаты",succeeded:"Оплачен",canceled:"Отменён"};
const generationState:Record<string,string>={queued:"В очереди",running:"Выполняется",completed:"Готово",failed:"Ошибка",cancelled:"Остановлено"};
const idempotencyKey=()=>{
 try{
  const cryptoApi=globalThis.crypto;
  if(cryptoApi&&typeof cryptoApi.randomUUID==="function")return cryptoApi.randomUUID();
  if(cryptoApi&&typeof cryptoApi.getRandomValues==="function"){
   const bytes=new Uint8Array(16);cryptoApi.getRandomValues(bytes);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;
   const h=Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("");return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;
  }
 }catch{}
 return `admin-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
};

export default function UsersAdmin(){
 const[query,setQuery]=useState("");const[data,setData]=useState<UsersResponse|null>(null);const[detail,setDetail]=useState<Detail|null>(null);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);const[promoAmount,setPromoAmount]=useState("");const[promoComment,setPromoComment]=useState("");const[debitAmount,setDebitAmount]=useState("");const[debitComment,setDebitComment]=useState("");
 const load=async(q=query)=>{try{setData(await api<UsersResponse>(`/admin/users-organizations/?limit=200${q?`&query=${encodeURIComponent(q)}`:""}`));setError("");}catch(r){setError(r instanceof Error?r.message:"Не удалось загрузить пользователей");}};
 useEffect(()=>{void load("");},[]);
 const open=async(id:string)=>{setBusy(true);try{setDetail(await api<Detail>(`/admin/users/${id}/`));setError("");}catch(r){setError(r instanceof Error?r.message:"Не удалось загрузить пользователя");}finally{setBusy(false);}};
 const action=async(name:"block"|"unblock"|"logout_all")=>{if(!detail)return;const reason=window.prompt("Причина действия для журнала аудита:","")??"";setBusy(true);try{await api(`/admin/users/${detail.user.id}/action/`,{method:"POST",body:JSON.stringify({action:name,reason})});await open(detail.user.id);await load();}catch(r){setError(r instanceof Error?r.message:"Действие не выполнено");}finally{setBusy(false);}};
 const promoCredit=async()=>{if(!detail)return;const amount=Number(promoAmount);if(!Number.isFinite(amount)||amount<=0){setError("Укажите сумму бонуса больше 0 ₽.");return;}if(promoComment.trim().length<3){setError("Укажите комментарий: за что начислен бонус.");return;}setBusy(true);setError("");setNotice("");try{const result=await api<PromoCreditResult>(`/admin/users/${detail.user.id}/promo-credit/`,{method:"POST",headers:{"Idempotency-Key":idempotencyKey()},body:JSON.stringify({amount_rub:promoAmount,comment:promoComment.trim()})});setDetail(current=>current?{...current,wallet:result.wallet}:current);setPromoAmount("");setPromoComment("");setNotice(`Начислено ${money(result.amount_rub)}. Новый бонусный баланс: ${money(result.wallet.promo_rub)}; доступно: ${money(result.wallet.available_rub)}.`);await open(detail.user.id);}catch(r){setError(r instanceof Error?r.message:"Бонусный баланс не начислен");}finally{setBusy(false);}};
 const debit=async()=>{if(!detail)return;const amount=Number(debitAmount);if(!Number.isFinite(amount)||amount<=0){setError("Укажите сумму списания больше 0 ₽.");return;}if(debitComment.trim().length<3){setError("Укажите комментарий к списанию.");return;}if(!window.confirm(`Списать ${money(amount)} с доступного баланса пользователя?`))return;setBusy(true);setError("");setNotice("");try{await api(`/admin/users/${detail.user.id}/action/`,{method:"POST",headers:{"Idempotency-Key":idempotencyKey()},body:JSON.stringify({action:"balance_debit",amount_rub:debitAmount,comment:debitComment.trim()})});setDebitAmount("");setDebitComment("");setNotice(`Списано ${money(amount)}.`);await open(detail.user.id);}catch(r){setError(r instanceof Error?r.message:"Баланс не скорректирован");}finally{setBusy(false);}};
 return <><header className={styles.header}><div><h1>Пользователи</h1><p>Аккаунты, кошельки, платежи, использование сервиса и поддержка в одной карточке.</p></div></header>{notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={`${styles.notice} ${styles.error}`}>{error}</div>}
 <section className={styles.section}><div className={styles.filters}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Email или логин"/><button className={styles.button} onClick={()=>void load()}>Найти</button></div><table className={styles.table}><thead><tr><th>Email</th><th>Логин</th><th>Роль</th><th>Статус</th><th>Регистрация</th><th></th></tr></thead><tbody>{data?.users.map(user=><tr key={user.id}><td>{user.email}</td><td>{user.username}</td><td>{userRole[user.role]||user.role}</td><td><span className={styles.pill}>{userStatus[user.status]||user.status}</span></td><td>{new Date(user.date_joined).toLocaleString("ru-RU")}</td><td><button className={styles.button} onClick={()=>void open(user.id)}>Открыть</button></td></tr>)}</tbody></table></section>
 {detail&&<section className={styles.section}><div className={styles.header}><div><h2>{detail.user.email}</h2><p>{detail.user.username} · {userRole[detail.user.role]||detail.user.role} · {userStatus[detail.user.status]||detail.user.status}</p></div><div className={styles.actions}>{detail.user.status==="active"?<button className={`${styles.button} ${styles.danger}`} disabled={busy} onClick={()=>void action("block")}>Заблокировать</button>:<button className={`${styles.button} ${styles.primary}`} disabled={busy} onClick={()=>void action("unblock")}>Разблокировать</button>}<button className={styles.button} disabled={busy} onClick={()=>void action("logout_all")}>Завершить все сессии</button></div></div>
 <div className={styles.grid}><div className={styles.card}><small>Доступный баланс</small><strong>{money(detail.wallet?.available_rub)}</strong></div><div className={styles.card}><small>Платный баланс</small><strong>{money(detail.wallet?.paid_rub)}</strong></div><div className={styles.card}><small>Бонусный баланс</small><strong>{money(detail.wallet?.promo_rub)}</strong></div><div className={styles.card}><small>В резерве</small><strong>{money(detail.wallet?.reserved_rub)}</strong></div></div>
 <div className={styles.two} style={{marginBottom:20}}><div className={styles.section}><h3>Начислить бонусные ₽</h3><p>Внутренняя админская операция. Не зависит от YooKassa, PAYMENTS_ENABLED или платёжных лимитов. Бонус нельзя вывести возвратом как реальные деньги.</p><div className={styles.form}><label>Сумма бонуса, ₽<input type="number" min="0.01" step="0.01" value={promoAmount} onChange={e=>setPromoAmount(e.target.value)} placeholder="500"/></label><label>Комментарий<input value={promoComment} onChange={e=>setPromoComment(e.target.value)} placeholder="Компенсация / тест / подарок"/></label><button className={`${styles.button} ${styles.primary}`} disabled={busy} onClick={()=>void promoCredit()}>{busy?"Выполняем…":"Начислить бонус"}</button></div></div><div className={styles.section}><h3>Ручное списание</h3><p>Списание идёт сначала из бонусного остатка, затем из оплаченного. Все действия остаются в неизменяемом журнале.</p><div className={styles.form}><label>Сумма, ₽<input type="number" min="0.01" step="0.01" value={debitAmount} onChange={e=>setDebitAmount(e.target.value)} placeholder="100"/></label><label>Комментарий<input value={debitComment} onChange={e=>setDebitComment(e.target.value)} placeholder="Причина списания"/></label><button className={`${styles.button} ${styles.danger}`} disabled={busy} onClick={()=>void debit()}>{busy?"Выполняем…":"Списать"}</button></div></div></div>
 <div className={styles.two}><div><h3>Последние платежи</h3><table className={styles.table}><tbody>{detail.payments.map(item=><tr key={item.id}><td>{money(item.amount_rub)}</td><td>{paymentStatus[item.status]||item.status}</td><td>{new Date(item.created_at).toLocaleDateString("ru-RU")}</td></tr>)}</tbody></table></div><div><h3>Последние AI-запросы</h3><table className={styles.table}><tbody>{detail.generations.map(item=><tr key={item.id}><td>{item.routed_model||"—"}</td><td>{generationState[item.state]||item.state}</td><td>{money(item.actual_cost_rub)}</td></tr>)}</tbody></table></div></div>
 <div><h3>Ручные корректировки баланса</h3><table className={styles.table}><thead><tr><th>Операция</th><th>Сумма</th><th>Комментарий</th><th>Администратор</th><th>Дата</th></tr></thead><tbody>{detail.balance_adjustments.map(item=><tr key={item.id}><td>{item.direction==="credit"?"Бонусное начисление":"Списание"}</td><td>{money(item.amount_rub)}</td><td>{item.comment}</td><td>{item.admin_id}</td><td>{new Date(item.created_at).toLocaleString("ru-RU")}</td></tr>)}</tbody></table>{detail.balance_adjustments.length===0&&<p>Ручных корректировок нет.</p>}</div>
 </section>}
 {data&&<section className={styles.section}><h2>Организации</h2><table className={styles.table}><thead><tr><th>Название</th><th>Короткое имя</th><th>Участники</th><th>Активные API-ключи</th><th>Статус</th></tr></thead><tbody>{data.organizations.map(org=><tr key={org.id}><td>{org.name}</td><td>{org.slug}</td><td>{org.members}</td><td>{org.active_keys}</td><td>{org.active?"Активна":"Отключена"}</td></tr>)}</tbody></table></section>}</>;
}
