"use client";

import {useEffect,useState} from "react";
import {api} from "../../../lib/api";
import styles from "../admin.module.css";

type Payment={id:string;user_id:string;user_email:string;provider:string;provider_payment_id:string|null;amount_rub:string;status:string;receipt_status:string;last_error:string;created_at:string};
type Refund={id:string;payment_id:string;amount_rub:string;status:string;created_at:string};
type RefundRequest={id:string;payment_id:string;refund_id:string|null;amount_rub:string;reason:string;status:string;admin_comment:string;held_at:string|null;resolved_at:string|null;created_at:string};
type Fee={id:string;provider:string;payment_method:string;percent:string;fixed_rub:string;active:boolean;effective_from:string};
type Payload={fees:Fee[];payments:Payment[];refunds:Refund[]};
const money=(v:string|number|null|undefined)=>`${Number(v??0).toFixed(2).replace(".",",")} ₽`;
const paymentStatus:Record<string,string>={created:"Создан",pending:"Ожидает оплаты",succeeded:"Оплачен",canceled:"Отменён"};
const receiptStatus:Record<string,string>={not_required:"Не требуется",pending:"Ожидается",succeeded:"Сформирован",failed:"Ошибка",legal_review:"Нужна юридическая проверка"};
const refundStatus:Record<string,string>={created:"Создан",pending:"В обработке",succeeded:"Завершён",canceled:"Отменён"};
const requestStatus:Record<string,string>={pending:"На рассмотрении",approved:"Одобрен",processing:"Возврат выполняется",succeeded:"Возвращён",rejected:"Отклонён",failed:"Ошибка"};

export default function PaymentsAdmin(){
 const[data,setData]=useState<Payload|null>(null);const[requests,setRequests]=useState<RefundRequest[]>([]);const[status,setStatus]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 const load=async()=>{try{const[p,r]=await Promise.all([api<Payload>(`/admin/payments/?limit=200${status?`&status=${status}`:""}`),api<RefundRequest[]>("/refund-requests/")]);setData(p);setRequests(r);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить платежи");}};
 useEffect(()=>{void load();},[status]);
 const refund=async(item:Payment)=>{const value=window.prompt(`Сумма возврата для ${item.user_email}`,item.amount_rub);if(!value)return;if(!window.confirm(`Подтвердить возврат ${value} ₽? Действие будет записано в журнал аудита.`))return;setBusy(true);setError("");try{await api(`/payments/${item.id}/refunds/`,{method:"POST",headers:{"Idempotency-Key":`admin-refund:${crypto.randomUUID()}`},body:JSON.stringify({amount_rub:value})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Возврат не выполнен");}finally{setBusy(false);}};
 const review=async(item:RefundRequest,action:"approve"|"reject")=>{const comment=window.prompt(action==="approve"?"Комментарий к одобрению":"Причина отказа","")??"";if(action==="approve"&&!window.confirm(`Одобрить возврат ${money(item.amount_rub)}?`))return;setBusy(true);setError("");try{await api(`/refund-requests/${item.id}/${action}/`,{method:"POST",body:JSON.stringify({admin_comment:comment})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Заявка не обработана");}finally{setBusy(false);}};
 return <><header className={styles.header}><div><h1>Платежи</h1><p>ЮKassa, чеки, ошибки оплаты, комиссии, заявки и возвраты.</p></div><button className={styles.button} onClick={()=>void load()}>Обновить</button></header>{error&&<div className={`${styles.notice} ${styles.error}`}>{error}</div>}
 <section className={styles.section}><h2>Заявки клиентов на возврат</h2><p>Сумма заявки уже удержана из доступного paid-баланса клиента. При отказе или ошибке возврата она автоматически возвращается на баланс.</p><table className={styles.table}><thead><tr><th>Платёж</th><th>Сумма</th><th>Причина</th><th>Статус</th><th>Комментарий</th><th>Дата</th><th></th></tr></thead><tbody>{requests.map(item=><tr key={item.id}><td>{item.payment_id}</td><td><b>{money(item.amount_rub)}</b></td><td>{item.reason||"—"}</td><td><span className={styles.pill}>{requestStatus[item.status]||item.status}</span></td><td>{item.admin_comment||"—"}</td><td>{new Date(item.created_at).toLocaleString("ru-RU")}</td><td>{item.status==="pending"&&<div className={styles.actions}><button className={`${styles.button} ${styles.primary}`} disabled={busy} onClick={()=>void review(item,"approve")}>Одобрить</button><button className={`${styles.button} ${styles.danger}`} disabled={busy} onClick={()=>void review(item,"reject")}>Отказать</button></div>}</td></tr>)}</tbody></table>{requests.length===0&&<p>Новых заявок нет.</p>}</section>
 <section className={styles.section}><div className={styles.filters}><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Все статусы</option><option value="created">Создан</option><option value="pending">Ожидает оплаты</option><option value="succeeded">Оплачен</option><option value="canceled">Отменён</option></select></div><table className={styles.table}><thead><tr><th>Пользователь</th><th>Сумма</th><th>Статус</th><th>Чек</th><th>ID у платёжного провайдера</th><th>Ошибка</th><th>Дата</th><th></th></tr></thead><tbody>{data?.payments.map(item=><tr key={item.id}><td>{item.user_email}</td><td><b>{money(item.amount_rub)}</b></td><td><span className={styles.pill}>{paymentStatus[item.status]||item.status}</span></td><td>{receiptStatus[item.receipt_status]||item.receipt_status}</td><td>{item.provider_payment_id??"—"}</td><td className={item.last_error?styles.bad:""}>{item.last_error||"—"}</td><td>{new Date(item.created_at).toLocaleString("ru-RU")}</td><td>{item.status==="succeeded"&&<button className={`${styles.button} ${styles.danger}`} disabled={busy} onClick={()=>void refund(item)}>Оформить возврат вручную</button>}</td></tr>)}</tbody></table></section>
 <section className={styles.two}><div className={styles.section}><h2>Возвраты</h2><table className={styles.table}><thead><tr><th>Платёж</th><th>Сумма</th><th>Статус</th><th>Дата</th></tr></thead><tbody>{data?.refunds.map(item=><tr key={item.id}><td>{item.payment_id}</td><td>{money(item.amount_rub)}</td><td>{refundStatus[item.status]||item.status}</td><td>{new Date(item.created_at).toLocaleString("ru-RU")}</td></tr>)}</tbody></table></div><div className={styles.section}><h2>Версии комиссий эквайринга</h2><table className={styles.table}><thead><tr><th>Провайдер / метод</th><th>Процент</th><th>Фиксированная часть</th><th>Активна</th></tr></thead><tbody>{data?.fees.map(item=><tr key={item.id}><td>{item.provider}/{item.payment_method}</td><td>{item.percent}%</td><td>{money(item.fixed_rub)}</td><td>{item.active?"Да":"Нет"}</td></tr>)}</tbody></table></div></section></>;
}
