"use client";

import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../../lib/api";
import AgentConnectionsPanel from "../AgentConnectionsPanel";
import type {WorkflowGraph} from "../../../../lib/agent-workflow";
import AgentGraphEditor from "../AgentGraphEditor";
import AgentMemoryPanel from "../AgentMemoryPanel";
import AgentReadinessPanel from "../AgentReadinessPanel";
import AgentSchedulePanel from "../AgentSchedulePanel";
import AgentTestModePanel from "../AgentTestModePanel";
import AgentToolPolicy from "../AgentToolPolicy";
import AgentUsagePanel from "../AgentUsagePanel";
import AgentVersions from "../AgentVersions";

type Graph={version?:number;nodes?:Array<{id:string;title:string;type:string;[key:string]:unknown}>;edges?:Array<{from:string;to:string}>};
type Agent={id:string;name:string;role:string;objective:string;instructions:string;autonomy:string;status:string;system_level:string;tool_policy:Record<string,unknown>;graph:Graph;max_cost_rub_per_run:string;max_cost_rub_per_day:string;max_cost_rub_per_month:string};
type Run={id:string;state:string;objective:string;cost_actual_rub:string;step_count:number;created_at:string};
type Tab="workflow"|"work"|"setup"|"capabilities"|"history";
const activeStates=["queued","planning","running","waiting_tool","waiting_approval","reviewing"];
const stateLabel:Record<string,string>={queued:"В очереди",planning:"Планирует",running:"Выполняет",waiting_tool:"Ждёт инструмент",waiting_approval:"Ждёт решения",reviewing:"Проверяет",completed:"Готово",failed:"Ошибка",canceled:"Остановлен",budget_exceeded:"Лимит бюджета"};
const autonomyOptions=[["controlled","Под контролем"],["semi_autonomous","Самостоятельно, важное согласовывать"],["autonomous","Автономно в заданных пределах"]] as const;
const levelOptions=[["economy","Простой"],["balanced","Средний"],["maximum","Сложный"]] as const;

export default function AgentDetailV2(){
 const params=useParams<{id:string}>();const router=useRouter();const id=String(params.id);const[agent,setAgent]=useState<Agent|null>(null);const[runs,setRuns]=useState<Run[]>([]);const[tab,setTab]=useState<Tab>("work");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[task,setTask]=useState("");const[ready,setReady]=useState<boolean|null>(null);const[refresh,setRefresh]=useState(0);
 const activeRun=useMemo(()=>runs.find(run=>activeStates.includes(run.state))??null,[runs]);
 const load=async()=>{try{const[a,r]=await Promise.all([api<Agent>(`/agents/${id}/`),api<Run[]>(`/agent-runs/?agent=${encodeURIComponent(id)}`)]);setAgent(a);setRuns(r.slice(0,30));setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить сотрудника")}};
 useEffect(()=>{if(new URLSearchParams(window.location.search).get("view")==="workflow")setTab("workflow");void load()},[id]);useEffect(()=>{if(!activeRun)return;const timer=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(timer)},[activeRun?.id,id]);
 const patch=async(body:Partial<Agent>&{expected_graph_version?:number},propagate=false)=>{if(activeRun){setError("Настройки временно заморожены, пока выполняется задача.");return}setBusy("save");setError("");try{const next=await api<Agent>(`/agents/${id}/config/`,{method:"PATCH",body:JSON.stringify(body)});setAgent(next);setRefresh(v=>v+1);setNotice("Изменения сохранены.")}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить");if(propagate)throw e}finally{setBusy("")}};
 const activate=async()=>{setBusy("activate");setError("");try{setAgent(await api<Agent>(`/agents/${id}/activate/`,{method:"POST"}));setRefresh(v=>v+1);setNotice("Сотрудник активирован и готов к задачам.")}catch(e){setError(e instanceof Error?e.message:"Не удалось активировать")}finally{setBusy("")}};
 const run=async()=>{if(!agent)return;if(activeRun){router.push(`/app/runs/${activeRun.id}`);return}if(ready===false){setError("Сначала устраните пункты в проверке готовности.");return}const objective=task.trim()||agent.objective;if(!objective)return;setBusy("run");setError("");try{const started=await api<Run>(`/agents/${id}/run/`,{method:"POST",body:JSON.stringify({objective})});setTask("");router.push(`/app/runs/${started.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось запустить задачу");setRefresh(v=>v+1)}finally{setBusy("")}};
 if(!agent)return <main className="studioPage"><div className="studioEmpty">{error||"Загружаем сотрудника…"}</div></main>;
 return <main className="studioPage agentDetailSimple">
  <header className="studioDetailHero"><div><Link href="/app/agents">← Все сотрудники</Link><h1>{agent.name}</h1><p>{agent.role||"AI-сотрудник"} · {agent.status==="active"?"готов к работе":"черновик"}</p></div>{agent.status!=="active"&&<button className="studioPrimary" onClick={()=>void activate()} disabled={!!busy}>{busy==="activate"?"Активируем…":"Активировать"}</button>}</header>
  {notice&&<div className="studioAlert success">{notice}</div>}{error&&<div className="studioAlert error">{error}</div>}{activeRun&&<div className="studioAlert warning">Сейчас выполняется задача. Настройки временно заморожены. <Link href={`/app/runs/${activeRun.id}`}>Открыть выполнение →</Link></div>}
  <nav className="studioTabs" aria-label="Разделы сотрудника"><button className={tab==="work"?"active":""} onClick={()=>setTab("work")}>Работа</button><button className={tab==="workflow"?"active":""} onClick={()=>setTab("workflow")}>Визуальная схема</button><button className={tab==="setup"?"active":""} onClick={()=>setTab("setup")}>Настройки</button><button className={tab==="capabilities"?"active":""} onClick={()=>setTab("capabilities")}>Возможности</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>История</button></nav>
  {tab==="work"&&<div className="studioDetailGrid"><section className="studioDetailMain"><article className="studioPanel primary"><span className="studioEyebrow">НОВАЯ ЗАДАЧА</span><h2>Что нужно сделать?</h2><textarea className="studioPrompt" rows={5} value={task} onChange={e=>setTask(e.target.value)} disabled={!!activeRun} placeholder={agent.objective||"Опишите результат обычными словами"}/><div className="studioCreateFooter"><span>{activeRun?"Сотрудник уже выполняет задачу.":"Перед запуском система проверит готовность и бюджет."}</span><button className="studioPrimary" onClick={()=>void run()} disabled={!!busy||agent.status!=="active"||ready===false}>{busy==="run"?"Запускаем…":activeRun?"Открыть текущую задачу":ready===false?"Нужна настройка":"Запустить"}</button></div></article><article className="studioPanel"><h2>Цель сотрудника</h2><p className="studioLead">{agent.objective||"Цель пока не описана"}</p></article></section><aside className="studioDetailAside"><AgentReadinessPanel agentId={id} refreshToken={refresh} onChange={setReady}/><AgentUsagePanel agentId={id} refreshToken={runs.length}/></aside></div>}
  {tab==="workflow"&&<article className="studioPanel"><AgentGraphEditor key={`${id}:${agent.graph?.version||1}`} agentId={id} graph={agent.graph||{nodes:[],edges:[]}} disabled={!!activeRun||busy==="save"} onSave={async(graph:WorkflowGraph)=>{const types=new Set(graph.nodes?.map(node=>node.type));const policy={...agent.tool_policy,...(types.has("browser")?{browser:true}:{}),...(types.has("http")?{http:true}:{}),...(["web","search","research"].some(type=>types.has(type))?{web:true}:{}),...(types.has("files")?{files:true}:{}),...(types.has("image")?{images:true}:{})};await patch({graph,tool_policy:policy,expected_graph_version:Number(agent.graph?.version||1)},true)}}/></article>}
  {tab==="setup"&&<div className="studioDetailGrid"><section className="studioDetailMain"><article className="studioPanel"><h2>Роль и инструкции</h2><div className="studioForm"><label><span>Название</span><input value={agent.name} onChange={e=>setAgent({...agent,name:e.target.value})} disabled={!!activeRun}/></label><label><span>Роль</span><input value={agent.role} onChange={e=>setAgent({...agent,role:e.target.value})} disabled={!!activeRun}/></label><label><span>Главная цель</span><textarea rows={4} value={agent.objective} onChange={e=>setAgent({...agent,objective:e.target.value})} disabled={!!activeRun}/></label><label><span>Дополнительные инструкции</span><textarea rows={5} value={agent.instructions} onChange={e=>setAgent({...agent,instructions:e.target.value})} disabled={!!activeRun}/></label></div><button className="studioPrimary small" onClick={()=>void patch({name:agent.name,role:agent.role,objective:agent.objective,instructions:agent.instructions})} disabled={!!activeRun||busy==="save"}>Сохранить</button></article></section><aside className="studioDetailAside"><article className="studioPanel"><h3>Режим работы</h3><label className="studioField"><span>Самостоятельность</span><select value={agent.autonomy} onChange={e=>setAgent({...agent,autonomy:e.target.value})} disabled={!!activeRun}>{autonomyOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="studioField"><span>Сложность</span><select value={agent.system_level} onChange={e=>setAgent({...agent,system_level:e.target.value})} disabled={!!activeRun}>{levelOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="studioBudget"><label><span>На задачу, ₽</span><input inputMode="decimal" value={agent.max_cost_rub_per_run} onChange={e=>setAgent({...agent,max_cost_rub_per_run:e.target.value})}/></label><label><span>В день, ₽</span><input inputMode="decimal" value={agent.max_cost_rub_per_day} onChange={e=>setAgent({...agent,max_cost_rub_per_day:e.target.value})}/></label><label><span>В месяц, ₽</span><input inputMode="decimal" value={agent.max_cost_rub_per_month} onChange={e=>setAgent({...agent,max_cost_rub_per_month:e.target.value})}/></label></div><button className="studioGhost" onClick={()=>void patch({autonomy:agent.autonomy,system_level:agent.system_level,max_cost_rub_per_run:agent.max_cost_rub_per_run,max_cost_rub_per_day:agent.max_cost_rub_per_day,max_cost_rub_per_month:agent.max_cost_rub_per_month})} disabled={!!activeRun||busy==="save"}>Сохранить режим и бюджет</button></article></aside></div>}
  {tab==="capabilities"&&<div className="studioDetailGrid"><section className="studioDetailMain"><AgentMemoryPanel agentId={id}/></section><aside className="studioDetailAside"><article className="studioPanel"><h3>Разрешения</h3><AgentToolPolicy policy={agent.tool_policy||{}} autonomy={agent.autonomy} disabled={!!activeRun||busy==="save"} onSave={async tool_policy=>{await patch({tool_policy})}}/></article><AgentConnectionsPanel agentId={id} onChanged={()=>setRefresh(v=>v+1)}/><AgentSchedulePanel agentId={id} defaultObjective={agent.objective} active={agent.status==="active"}/></aside></div>}
  {tab==="history"&&<div className="studioDetailGrid"><section className="studioDetailMain"><article className="studioPanel"><h2>Последние задачи</h2>{runs.length?<div className="studioRunList">{runs.slice(0,12).map(item=><Link href={`/app/runs/${item.id}`} key={item.id}><span><b>{stateLabel[item.state]||item.state}</b><small>{item.objective}</small></span><em>{Number(item.cost_actual_rub||0).toFixed(2)} ₽</em></Link>)}</div>:<div className="studioEmpty">Запусков пока нет.</div>}</article></section><aside className="studioDetailAside"><AgentTestModePanel agentId={id}/><article className="studioPanel"><h3>Версии</h3><AgentVersions agentId={id} refreshToken={refresh} onRestored={async()=>{await load();setRefresh(v=>v+1)}}/></article></aside></div>}
 </main>;
}
