"use client";

import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../../lib/api";
import AgentConnectionsPanel from "../AgentConnectionsPanel";
import AgentGraphEditor from "../AgentGraphEditor";
import AgentMemoryPanel from "../AgentMemoryPanel";
import AgentReadinessPanel from "../AgentReadinessPanel";
import AgentSchedulePanel from "../AgentSchedulePanel";
import AgentToolPolicy from "../AgentToolPolicy";
import AgentVersions from "../AgentVersions";
import AgentWorkflowRecipes from "../AgentWorkflowRecipes";

type Graph={version?:number;nodes?:Array<{id:string;title:string;type:string;status?:"draft"|"publish";[key:string]:unknown}>;edges?:Array<{from:string;to:string}>};
type Agent={id:string;name:string;role:string;objective:string;instructions:string;autonomy:string;status:string;system_level:string;tool_policy:Record<string,unknown>;graph:Graph;max_cost_rub_per_run:string;max_cost_rub_per_day:string;max_cost_rub_per_month:string;max_steps:number;max_tool_calls:number;max_handoffs:number;max_retries_per_step:number;max_runtime_seconds:number};
type Run={id:string;state:string;objective:string;cost_actual_rub:string;step_count:number;tool_call_count:number;handoff_count:number;created_at:string};

const autonomyOptions=[["controlled","Контролируемый"],["semi_autonomous","Полуавтономный"],["autonomous","Автономный"]] as const;
const levelOptions=[["economy","System Lite"],["balanced","System Pro"],["maximum","System Max"]] as const;
const stateLabel:Record<string,string>={queued:"В очереди",planning:"Планирование",running:"Выполняется",waiting_tool:"Ожидает инструмент",waiting_approval:"Нужно подтверждение",reviewing:"Проверка",completed:"Готово",failed:"Ошибка",canceled:"Отменён",budget_exceeded:"Лимит бюджета"};
const activeStates=["queued","planning","running","waiting_tool","waiting_approval","reviewing"];

export default function AgentDetailPage(){
 const params=useParams<{id:string}>();const router=useRouter();const id=String(params.id);
 const[agent,setAgent]=useState<Agent|null>(null);const[runs,setRuns]=useState<Run[]>([]);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[task,setTask]=useState("");const[versionRefresh,setVersionRefresh]=useState(0);const[readinessRefresh,setReadinessRefresh]=useState(0);const[ready,setReady]=useState<boolean|null>(null);
 const activeRun=useMemo(()=>runs.find(run=>activeStates.includes(run.state))||null,[runs]);
 const load=async()=>{try{const[a,agentRuns]=await Promise.all([api<Agent>(`/agents/${id}/`),api<Run[]>(`/agent-runs/?agent=${encodeURIComponent(id)}`)]);setAgent(a);setRuns(agentRuns.slice(0,30));setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить агента")}};
 useEffect(()=>{void load()},[id]);
 useEffect(()=>{if(!runs.some(run=>activeStates.includes(run.state)))return;const timer=window.setInterval(()=>void load(),2500);return()=>window.clearInterval(timer)},[runs,id]);
 const refreshReadiness=()=>setReadinessRefresh(value=>value+1);
 const patch=async(body:Partial<Agent>)=>{if(activeRun){setError("Настройки заморожены до завершения текущей задачи.");return}setBusy("save");setError("");setNotice("");try{const next=await api<Agent>(`/agents/${id}/config/`,{method:"PATCH",body:JSON.stringify(body)});setAgent(next);setVersionRefresh(value=>value+1);refreshReadiness();setNotice("Настройки сохранены. Предыдущая версия доступна для отката.")}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить");throw e}finally{setBusy("")}};
 const activate=async()=>{setBusy("activate");setError("");try{const next=await api<Agent>(`/agents/${id}/activate/`,{method:"POST"});setAgent(next);refreshReadiness();setNotice("Агент активирован.")}catch(e){setError(e instanceof Error?e.message:"Не удалось активировать")}finally{setBusy("")}};
 const run=async()=>{if(activeRun){router.push(`/app/runs/${activeRun.id}`);return}if(!task.trim()&&!agent?.objective)return;if(ready===false){setError("Сначала устраните блокирующие пункты в проверке готовности.");return}setBusy("run");setError("");try{const started=await api<Run>(`/agents/${id}/run/`,{method:"POST",body:JSON.stringify({objective:task.trim()||agent?.objective})});setTask("");router.push(`/app/runs/${started.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось запустить агента");refreshReadiness()}finally{setBusy("")}};
 if(!agent)return <main style={{padding:32}}>{error||"Загрузка…"}</main>;
 return <main style={{maxWidth:1220,margin:"0 auto",padding:"28px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",marginBottom:24}}><div><Link href="/app/agents" style={{textDecoration:"none",opacity:.65}}>← Все агенты</Link><h1 style={{fontSize:36,margin:"10px 0 6px"}}>{agent.name}</h1><div style={{opacity:.65}}>{agent.role||"AI-сотрудник"} · {agent.status}</div></div>{agent.status!=="active"&&<button onClick={()=>void activate()} disabled={!!busy} style={{padding:"10px 14px",borderRadius:10,border:0,fontWeight:700}}>Активировать</button>}</header>
  {activeRun&&<div style={{padding:12,border:"1px solid #d8b16a",borderRadius:11,marginBottom:14}}>Сотрудник сейчас выполняет задачу. Настройки временно заморожены, чтобы запуск не изменился в процессе. <Link href={`/app/runs/${activeRun.id}`}>Открыть текущий run →</Link></div>}
  {notice&&<div style={{padding:12,border:"1px solid #7da78a",borderRadius:11,marginBottom:14}}>{notice}</div>}{error&&<div style={{padding:12,border:"1px solid #c96d74",borderRadius:11,marginBottom:14}}>{error}</div>}
  <div style={{display:"grid",gridTemplateColumns:"minmax(0,1.2fr) minmax(300px,.8fr)",gap:18}}>
   <section style={{display:"grid",gap:16}}>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><h2 style={{marginTop:0}}>Роль и задача</h2><label style={{display:"grid",gap:6,marginBottom:12}}>Название<input value={agent.name} onChange={e=>setAgent({...agent,name:e.target.value})} disabled={!!activeRun} style={{padding:11,border:"1px solid #ccc",borderRadius:10}}/></label><label style={{display:"grid",gap:6,marginBottom:12}}>Роль<input value={agent.role} onChange={e=>setAgent({...agent,role:e.target.value})} disabled={!!activeRun} style={{padding:11,border:"1px solid #ccc",borderRadius:10}}/></label><label style={{display:"grid",gap:6,marginBottom:12}}>Главная цель<textarea rows={4} value={agent.objective} onChange={e=>setAgent({...agent,objective:e.target.value})} disabled={!!activeRun} style={{padding:11,border:"1px solid #ccc",borderRadius:10,resize:"vertical"}}/></label><label style={{display:"grid",gap:6}}>Дополнительные инструкции<textarea rows={5} value={agent.instructions} onChange={e=>setAgent({...agent,instructions:e.target.value})} disabled={!!activeRun} style={{padding:11,border:"1px solid #ccc",borderRadius:10,resize:"vertical"}}/></label><button onClick={()=>void patch({name:agent.name,role:agent.role,objective:agent.objective,instructions:agent.instructions})} disabled={busy==="save"||!!activeRun} style={{marginTop:12,padding:"10px 14px",border:0,borderRadius:10,fontWeight:700}}>Сохранить</button></article>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start"}}><div><h2 style={{margin:"0 0 5px"}}>Карта действий</h2><p style={{opacity:.62,margin:"0 0 16px"}}>Начните с готовой схемы или соберите процесс из блоков. Код и технические настройки не нужны.</p></div><span style={{fontSize:12,opacity:.5}}>v{agent.graph?.version||1}</span></div><AgentWorkflowRecipes disabled={busy==="save"||!!activeRun} currentNodeCount={agent.graph?.nodes?.length||0} onApply={async graph=>{await patch({graph});}}/><AgentGraphEditor key={`${id}:${agent.graph?.version||1}:${versionRefresh}`} graph={agent.graph||{nodes:[],edges:[]}} disabled={busy==="save"||!!activeRun} onSave={async graph=>{await patch({graph});}}/></article>
    <AgentMemoryPanel agentId={id}/>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><h2 style={{marginTop:0}}>Запустить задачу</h2><textarea rows={4} value={task} onChange={e=>setTask(e.target.value)} disabled={!!activeRun} placeholder={agent.objective||"Что должен сделать агент?"} style={{width:"100%",boxSizing:"border-box",padding:12,border:"1px solid #ccc",borderRadius:11,resize:"vertical"}}/><button onClick={()=>void run()} disabled={!!busy||agent.status!=="active"||ready===false} style={{marginTop:10,padding:"11px 15px",border:0,borderRadius:10,fontWeight:700}}>{busy==="run"?"Запускаем…":activeRun?"Открыть текущую задачу":ready===false?"Сначала завершите настройку":"Запустить"}</button></article>
   </section>
   <aside style={{display:"grid",gap:16,alignContent:"start"}}>
    <AgentReadinessPanel agentId={id} refreshToken={readinessRefresh} onChange={setReady}/>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><h3 style={{marginTop:0}}>Автономность</h3><select value={agent.autonomy} onChange={e=>setAgent({...agent,autonomy:e.target.value})} disabled={!!activeRun} style={{width:"100%",padding:10,borderRadius:10}}>{autonomyOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><h3>Мощность</h3><select value={agent.system_level} onChange={e=>setAgent({...agent,system_level:e.target.value})} disabled={!!activeRun} style={{width:"100%",padding:10,borderRadius:10}}>{levelOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><h3>Бюджет</h3><p style={{fontSize:12,opacity:.62,marginTop:-5}}>Система не должна начинать новый платный шаг, если он может превысить любой из этих лимитов.</p><div style={{display:"grid",gap:8}}><label style={{display:"grid",gap:5,fontSize:13}}>На один запуск, ₽<input inputMode="decimal" value={agent.max_cost_rub_per_run} onChange={e=>setAgent({...agent,max_cost_rub_per_run:e.target.value})} disabled={!!activeRun} style={{width:"100%",boxSizing:"border-box",padding:10,borderRadius:10,border:"1px solid #ccc"}}/></label><label style={{display:"grid",gap:5,fontSize:13}}>В день, ₽<input inputMode="decimal" value={agent.max_cost_rub_per_day} onChange={e=>setAgent({...agent,max_cost_rub_per_day:e.target.value})} disabled={!!activeRun} style={{width:"100%",boxSizing:"border-box",padding:10,borderRadius:10,border:"1px solid #ccc"}}/></label><label style={{display:"grid",gap:5,fontSize:13}}>В месяц, ₽<input inputMode="decimal" value={agent.max_cost_rub_per_month} onChange={e=>setAgent({...agent,max_cost_rub_per_month:e.target.value})} disabled={!!activeRun} style={{width:"100%",boxSizing:"border-box",padding:10,borderRadius:10,border:"1px solid #ccc"}}/></label></div><button onClick={()=>void patch({autonomy:agent.autonomy,system_level:agent.system_level,max_cost_rub_per_run:agent.max_cost_rub_per_run,max_cost_rub_per_day:agent.max_cost_rub_per_day,max_cost_rub_per_month:agent.max_cost_rub_per_month})} disabled={busy==="save"||!!activeRun} style={{marginTop:12,padding:"9px 12px",borderRadius:9,border:"1px solid #ccc"}}>Сохранить режим и бюджет</button></article>
    <AgentSchedulePanel agentId={id} defaultObjective={agent.objective} active={agent.status==="active"}/>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><h3 style={{marginTop:0}}>Разрешения и инструменты</h3><p style={{fontSize:13,opacity:.62,marginTop:-4}}>Агент не сможет использовать инструмент, который здесь выключен. Внешние публикации и merge требуют подтверждения, если вы явно не включили автопубликацию для автономного сотрудника.</p><AgentToolPolicy policy={agent.tool_policy||{}} autonomy={agent.autonomy} disabled={busy==="save"||!!activeRun} onSave={async tool_policy=>{await patch({tool_policy});}}/></article>
    <AgentConnectionsPanel agentId={id} onChanged={refreshReadiness}/>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><h3 style={{marginTop:0}}>Версии</h3><AgentVersions agentId={id} refreshToken={versionRefresh} onRestored={async()=>{await load();setVersionRefresh(value=>value+1);refreshReadiness();setNotice("Версия восстановлена.")}}/></article>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><h3 style={{marginTop:0}}>Последние запуски</h3>{runs.length?runs.slice(0,8).map(item=><Link key={item.id} href={`/app/runs/${item.id}`} style={{display:"block",padding:"9px 0",borderBottom:"1px solid #eee",textDecoration:"none",color:"inherit"}}><strong>{stateLabel[item.state]||item.state}</strong><div style={{fontSize:12,opacity:.6,marginTop:3}}>{item.step_count} шагов · {Number(item.cost_actual_rub||0).toFixed(2)} ₽</div></Link>):<p style={{opacity:.65}}>Запусков пока нет.</p>}</article>
   </aside>
  </div>
 </main>;
}
