# Generated by Django 5.2.5 on 2026-08-23 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_rub', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('reserved_rub', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('credit', 'Пополнение'), ('reserve', 'Резерв'), ('release', 'Освобождение'), ('debit', 'Списание'), ('adjustment', 'Корректировка')], max_length=16)),
                ('amount_rub', models.DecimalField(decimal_places=4, max_digits=14)),
                ('available_delta_rub', models.DecimalField(decimal_places=4, max_digits=14)),
                ('reserved_delta_rub', models.DecimalField(decimal_places=4, max_digits=14)),
                ('available_after_rub', models.DecimalField(decimal_places=4, max_digits=14)),
                ('reserved_after_rub', models.DecimalField(decimal_places=4, max_digits=14)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='billing.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_rub', models.DecimalField(decimal_places=4, max_digits=14)),
                ('actual_rub', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('state', models.CharField(choices=[('active', 'Активен'), ('settled', 'Закрыт'), ('released', 'Освобождён')], default='active', max_length=16)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='billing.wallet')),
            ],
        ),
    ]
