# Generated by Django 5.2.5 on 2026-08-23 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("model_slug", models.SlugField()),
                ("input_rub_per_million", models.DecimalField(decimal_places=4, max_digits=14)),
                ("output_rub_per_million", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "markup_percent",
                    models.DecimalField(decimal_places=2, default=100, max_digits=7),
                ),
                ("active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RequestCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("generation_id", models.UUIDField(unique=True)),
                ("estimated_rub", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "provider_cost_rub",
                    models.DecimalField(decimal_places=4, max_digits=14, null=True),
                ),
                ("charged_rub", models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="billing.priceversion"
                    ),
                ),
            ],
        ),
    ]
