# Generated by Django 5.2.5 on 2026-08-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_priceversion_requestcost"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancereservation",
            name="paid_amount_rub",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="balancereservation",
            name="promo_amount_rub",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="paid_delta_rub",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="promo_delta_rub",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="wallet",
            name="paid_rub",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="wallet",
            name="promo_rub",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("credit", "Пополнение"),
                    ("reserve", "Резерв"),
                    ("release", "Освобождение"),
                    ("debit", "Списание"),
                    ("refund", "Возврат пополнения"),
                    ("adjustment", "Корректировка"),
                ],
                max_length=16,
            ),
        ),
    ]
