import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import styles from "../../commercial.module.css";

const cases={
  marketing:{title:"AI для маркетинга",description:"Тексты, исследования, анализ документов, сравнение идей и работа с актуальными источниками в одном AI-пространстве.",headline:"AI для маркетолога: от исследования до готового материала",points:[["Исследования","Собирайте информацию, сравнивайте варианты и при необходимости подключайте web-поиск с источниками."],["Контент","Готовьте структуры, тексты, варианты объявлений и редактуру, сохраняя контекст в проектах."],["Документы","Анализируйте PDF, DOCX, таблицы и возвращайтесь к источникам внутри проекта."]]},
  coding:{title:"AI для программирования",description:"Работа с кодом, архитектурой, анализом ошибок и сравнением моделей с прозрачной стоимостью каждого запроса.",headline:"AI для разработки: код, архитектура и проверка решений",points:[["Код","Получайте ответы с форматированными code blocks и сохраняйте технический контекст в отдельных проектах."],["Сложность задачи","AUTO Router может учитывать тип задачи и выбирать подходящую доступную модель."],["Сравнение","Отправляйте один вопрос нескольким моделям и сравнивайте подходы, стоимость и результат."]]},
  documents:{title:"AI для работы с документами",description:"Анализ PDF, DOCX, XLSX, CSV и текстовых файлов с проектным контекстом и привязкой к источникам.",headline:"Задавайте вопросы своим документам и сохраняйте контекст",points:[["PDF","Текстовые PDF обрабатываются постранично, чтобы ответ можно было связать с исходным фрагментом."],["Таблицы и документы","Поддерживаются DOCX, XLSX, CSV, TXT и Markdown в безопасном файловом pipeline."],["Проекты","Объединяйте документы, инструкции и связанные чаты в одном рабочем пространстве."]]},
} as const;

type Slug=keyof typeof cases;
export function generateStaticParams(){return Object.keys(cases).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const item=cases[slug as Slug];if(!item)return{};return{title:`${item.title} | AI Workspace`,description:item.description,alternates:{canonical:`/use-cases/${slug}`}};}
export default async function UseCasePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const item=cases[slug as Slug];if(!item)notFound();return <main className={styles.page}><div className={styles.shell}><header className={styles.top}><div className={styles.brand}>AI Workspace</div><nav className={styles.nav}><Link href="/">Главная</Link><Link href="/pricing">Стоимость</Link><Link href="/faq">FAQ</Link><Link href="/login">Войти</Link></nav></header><section className={styles.hero}><p>{item.title.toUpperCase()}</p><h1>{item.headline}</h1><p>{item.description}</p><div className={styles.actions}><Link className={styles.cta} href="/register">Попробовать</Link><Link className={styles.secondary} href="/getting-started">Как начать</Link></div></section><section className={styles.grid}>{item.points.map(([title,text])=><article className={styles.card} key={title}><h2>{title}</h2><p>{text}</p></article>)}</section><section className={styles.card} style={{marginTop:24}}><h2>Как это работает</h2><ol><li>Создайте аккаунт и подтвердите email.</li><li>Создайте чат или проект под задачу.</li><li>Оставьте AUTO Router или выберите модель вручную.</li><li>Получите результат и посмотрите модель, usage и стоимость операции.</li></ol></section><section className={styles.hero} style={{marginTop:30}}><h2>Начните с одного запроса</h2><div className={styles.actions}><Link className={styles.cta} href="/register">Создать аккаунт</Link><Link className={styles.secondary} href="/pricing">Стоимость</Link></div></section></div></main>}
