"use client";

import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";
import TeamReadinessBadge from "./TeamReadinessBadge";
import styles from "./teams.module.css";

type Member={id:string;agent:string;agent_name:string;role:string;priority:number;can_delegate:boolean;enabled:boolean};
type Team={id:string;project:string|null;name:string;objective:string;kind:string;director:string;director_name:string;active:boolean;max_cost_rub_per_run:string;members:Member[];updated_at:string};
type Run={id:string;team:string|null;state:string;objective:string;cost_actual_rub:string;step_count:number;created_at:string};

const kindLabel:Record<string,string>={generic:"Универсальная",marketing:"Маркетинг",content:"Контент",sales:"Продажи",development:"Разработка"};
const stateLabel:Record<string,string>={queued:"В очереди",planning:"Планирование",running:"Выполняется",waiting_tool:"Ожидает инструмент",waiting_approval:"Нужно подтверждение",reviewing:"Проверка",completed:"Готово",failed:"Ошибка",canceled:"Отменён",budget_exceeded:"Лимит бюджета"};

export default function TeamsPage(){
 const router=useRouter();
 const[teams,setTeams]=useState<Team[]>([]);const[runs,setRuns]=useState<Run[]>([]);const[readiness,setReadiness]=useState<Record<string,boolean>>({});const[goal,setGoal]=useState("");const[context,setContext]=useState("");const[independence,setIndependence]=useState("Обычные внутренние задачи выполнять самостоятельно");const[approvalRule,setApprovalRule]=useState("Публикации, отправки и другие внешние действия подтверждать у меня");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const genericTeams=useMemo(()=>teams.filter(team=>team.kind!=="development"),[teams]);
 const description=useMemo(()=>[goal.trim(),context.trim()?`Контекст бизнеса: ${context.trim()}.`:"",`Режим работы: ${independence}.`,`Правило подтверждений: ${approvalRule}.`].filter(Boolean).join(" "),[goal,context,independence,approvalRule]);
 const load=async()=>{try{const[t,r]=await Promise.all([api<Team[]>("/agent-teams/"),api<Run[]>("/agent-runs/")]);setTeams(t);setRuns(r);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить команды")}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!runs.some(run=>["queued","planning","running","reviewing","waiting_tool"].includes(run.state)))return;const timer=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(timer)},[runs]);
 const createTeam=async()=>{if(goal.trim().length<12){setError("Опишите, какой результат должна давать команда");return}setBusy("create");setError("");setNotice("");try{const team=await api<Team>("/agent-teams/from-description/",{method:"POST",body:JSON.stringify({description})});setTeams(current=>[team,...current]);setGoal("");setContext("");setNotice(`Команда «${team.name}» создана. Система назначила руководителя и роли.`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать команду")}finally{setBusy("")}};
 const runTeam=async(team:Team)=>{if(readiness[team.id]===false){setError("Сначала завершите настройку команды.");return}setBusy(`run:${team.id}`);setError("");try{const run=await api<Run>(`/agent-teams/${team.id}/run/`,{method:"POST",body:JSON.stringify({objective:team.objective})});router.push(`/app/runs/${run.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось запустить команду")}finally{setBusy("")}};
 const teamRuns=(teamId:string)=>runs.filter(run=>run.team===teamId).slice(0,3);
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.top}><div><span className={styles.eyebrow}>AI WORKSPACE · AGENT STUDIO</span><h1>Команды AI-сотрудников</h1><p>Опишите отдел простыми словами. Система сама создаст руководителя, распределит роли и соберёт последовательность работы. Для программирования используйте отдельный Dev Studio.</p></div><div className={styles.topLinks}><Link href="/app/agents">Одиночные агенты</Link><Link href="/app/schedules">Автономность</Link><Link href="/app/dev">Dev Studio</Link></div></header>
  {notice&&<div className={styles.notice} role="status">{notice}</div>}{error&&<div className={styles.error} role="alert">{error}</div>}
  <section className={styles.builder}><span className={styles.builderEyebrow}>Новый отдел</span><h2>Соберите команду без ручной настройки ролей</h2><div className={styles.builderFields}><label className={styles.field}><strong>1. Что должна делать команда?</strong><textarea rows={4} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Например: анализировать конкурентов, составлять контент-план, писать посты и проверять факты"/></label><label className={styles.field}><strong>2. Для какого бизнеса?</strong><textarea rows={3} value={context} onChange={e=>setContext(e.target.value)} placeholder="Например: сеть стоматологий в Москве, аудитория — взрослые 30–55 лет"/></label><label className={styles.field}><strong>3. Что команда может делать сама?</strong><select value={independence} onChange={e=>setIndependence(e.target.value)}><option>Только готовить материалы и рекомендации</option><option>Обычные внутренние задачи выполнять самостоятельно</option><option>Работать максимально автономно в рамках бюджета и разрешений</option></select></label><label className={styles.field}><strong>4. Какие действия всегда спрашивать у вас?</strong><select value={approvalRule} onChange={e=>setApprovalRule(e.target.value)}><option>Все действия подтверждать у меня</option><option>Публикации, отправки и другие внешние действия подтверждать у меня</option><option>Только необратимые и финансовые действия подтверждать у меня</option></select></label></div><div className={styles.builderFooter}><span>Система создаст директора и специалистов автоматически. Настройки можно изменить до первого запуска.</span><button className={styles.primary} onClick={()=>void createTeam()} disabled={!!busy||goal.trim().length<12}>{busy==="create"?"Создаём…":"Создать отдел"}</button></div></section>
  <section><div className={styles.sectionHead}><div><h2>Мои команды</h2><p>Руководитель передаёт результат между специалистами, общий расход ограничен бюджетом команды.</p></div></div>{!genericTeams.length?<div className={styles.empty}>Команд пока нет. Соберите первый отдел выше.</div>:<div className={styles.teamList}>{genericTeams.map(team=>{const recent=teamRuns(team.id);return <article key={team.id} className={styles.teamCard}><div className={styles.teamGrid}><div><div className={styles.teamTitle}><Link href={`/app/teams/${team.id}`}>{team.name}</Link><span className={styles.kind}>{kindLabel[team.kind]||team.kind}</span></div><p className={styles.objective}>{team.objective}</p><div className={styles.members}>{team.members.map(member=><span key={member.id} className={styles.member}>{member.can_delegate?"★ ":""}{member.role}</span>)}</div><div className={styles.meta}>Руководитель: {team.director_name} · лимит запуска {Number(team.max_cost_rub_per_run||0).toFixed(2)} ₽</div><TeamReadinessBadge teamId={team.id} onChange={ready=>setReadiness(current=>({...current,[team.id]:ready}))}/></div><div className={styles.actions}><Link className={styles.secondaryLink} href={`/app/teams/${team.id}`}>Настроить</Link><button className={styles.primary} disabled={!!busy||!team.active||readiness[team.id]===false} onClick={()=>void runTeam(team)}>{busy===`run:${team.id}`?"Запускаем…":readiness[team.id]===false?"Настройте":"Запустить"}</button></div></div>{recent.length>0&&<div className={styles.runs}>{recent.map(run=><Link key={run.id} href={`/app/runs/${run.id}`} className={styles.runLink}><span><strong>{stateLabel[run.state]||run.state}</strong> · {run.objective.slice(0,90)}</span><span className={styles.runMeta}>{run.step_count} шагов · {Number(run.cost_actual_rub||0).toFixed(2)} ₽</span></Link>)}</div>}</article>})}</div>}</section>
 </div></main>;
}
