"use client";

import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";

type Member={id:string;agent:string;agent_name:string;role:string;priority:number;can_delegate:boolean;enabled:boolean};
type Team={id:string;project:string|null;name:string;objective:string;kind:string;director:string;director_name:string;active:boolean;max_cost_rub_per_run:string;members:Member[];updated_at:string};
type Run={id:string;team:string|null;state:string;objective:string;cost_actual_rub:string;step_count:number;created_at:string};

const kindLabel:Record<string,string>={generic:"Универсальная",marketing:"Маркетинг",content:"Контент",sales:"Продажи",development:"Разработка"};
const stateLabel:Record<string,string>={queued:"В очереди",planning:"Планирование",running:"Выполняется",waiting_tool:"Ожидает инструмент",waiting_approval:"Нужно подтверждение",reviewing:"Проверка",completed:"Готово",failed:"Ошибка",canceled:"Отменён",budget_exceeded:"Лимит бюджета"};

export default function TeamsPage(){
 const router=useRouter();
 const[teams,setTeams]=useState<Team[]>([]);const[runs,setRuns]=useState<Run[]>([]);const[description,setDescription]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const genericTeams=useMemo(()=>teams.filter(team=>team.kind!=="development"),[teams]);
 const load=async()=>{try{const[t,r]=await Promise.all([api<Team[]>("/agent-teams/"),api<Run[]>("/agent-runs/")]);setTeams(t);setRuns(r);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить команды")}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!runs.some(run=>["queued","planning","running","reviewing","waiting_tool"].includes(run.state)))return;const timer=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(timer)},[runs]);
 const createTeam=async()=>{if(description.trim().length<12){setError("Опишите, что должна делать команда, чуть подробнее");return}setBusy("create");setError("");setNotice("");try{const team=await api<Team>("/agent-teams/from-description/",{method:"POST",body:JSON.stringify({description:description.trim()})});setTeams(current=>[team,...current]);setDescription("");setNotice(`Команда «${team.name}» создана. Система назначила руководителя и роли.`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать команду")}finally{setBusy("")}};
 const runTeam=async(team:Team)=>{setBusy(`run:${team.id}`);setError("");try{const run=await api<Run>(`/agent-teams/${team.id}/run/`,{method:"POST",body:JSON.stringify({objective:team.objective})});router.push(`/app/runs/${run.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось запустить команду")}finally{setBusy("")}};
 const teamRuns=(teamId:string)=>runs.filter(run=>run.team===teamId).slice(0,3);
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"32px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:30}}><div><div style={{fontSize:13,opacity:.6,marginBottom:8}}>AI WORKSPACE · AGENT STUDIO</div><h1 style={{fontSize:38,margin:"0 0 10px"}}>Команды AI-сотрудников</h1><p style={{maxWidth:780,opacity:.72,fontSize:17}}>Опишите отдел обычными словами. Система сама создаст руководителя, распределит роли и соберёт команду. Для программирования используйте отдельный Dev Studio.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link href="/app/agents" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Одиночные агенты</Link><Link href="/app/dev" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Dev Studio</Link></div></header>
  {notice&&<div style={{padding:13,border:"1px solid #7aa78b",borderRadius:12,marginBottom:16}}>{notice}</div>}{error&&<div style={{padding:13,border:"1px solid #cb747a",borderRadius:12,marginBottom:16}}>{error}</div>}
  <section style={{border:"1px solid #ddd",borderRadius:22,padding:22,marginBottom:32}}><div style={{fontSize:12,opacity:.55,textTransform:"uppercase"}}>Новый отдел</div><h2 style={{margin:"8px 0"}}>Какую команду вы хотите создать?</h2><p style={{opacity:.68,marginTop:0}}>Например: «Нужен маркетинговый отдел: анализировать конкурентов, делать контент-план, писать посты и проверять факты».</p><textarea rows={6} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Опишите результат, обязанности и ограничения команды..." style={{width:"100%",boxSizing:"border-box",padding:14,border:"1px solid #ccc",borderRadius:13,resize:"vertical",font:"inherit"}}/><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginTop:12}}><span style={{fontSize:13,opacity:.62}}>Маркетинг, контент, продажи или универсальная команда определятся автоматически.</span><button onClick={()=>void createTeam()} disabled={!!busy||description.trim().length<12} style={{padding:"11px 16px",border:0,borderRadius:11,fontWeight:700,cursor:"pointer"}}>{busy==="create"?"Создаём…":"Создать команду"}</button></div></section>
  <section><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,marginBottom:14}}><div><h2 style={{margin:0}}>Мои команды</h2><p style={{opacity:.65,margin:"6px 0 0"}}>Руководитель передаёт результат между специалистами, общий расход ограничен бюджетом команды.</p></div></div>{!genericTeams.length?<div style={{border:"1px dashed #bbb",borderRadius:18,padding:34,textAlign:"center",opacity:.7}}>Команд пока нет. Опишите первый отдел выше.</div>:<div style={{display:"grid",gap:14}}>{genericTeams.map(team=><article key={team.id} style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:18}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><Link href={`/app/teams/${team.id}`} style={{fontSize:22,fontWeight:700,textDecoration:"none",color:"inherit"}}>{team.name}</Link><span style={{fontSize:12,border:"1px solid #ddd",borderRadius:999,padding:"4px 8px"}}>{kindLabel[team.kind]||team.kind}</span></div><p style={{opacity:.7,margin:"8px 0 12px"}}>{team.objective}</p><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{team.members.map(member=><span key={member.id} style={{fontSize:12,border:"1px solid #ddd",borderRadius:999,padding:"5px 8px"}}>{member.can_delegate?"★ ":""}{member.role}</span>)}</div><div style={{fontSize:13,opacity:.58,marginTop:12}}>Руководитель: {team.director_name} · лимит запуска {Number(team.max_cost_rub_per_run||0).toFixed(2)} ₽</div></div><div style={{display:"flex",gap:8,alignItems:"flex-start"}}><Link href={`/app/teams/${team.id}`} style={{padding:"10px 13px",border:"1px solid #ddd",borderRadius:10,textDecoration:"none",color:"inherit",whiteSpace:"nowrap"}}>Настроить</Link><button disabled={!!busy||!team.active} onClick={()=>void runTeam(team)} style={{padding:"10px 14px",borderRadius:10,border:0,fontWeight:700,height:42,whiteSpace:"nowrap"}}>{busy===`run:${team.id}`?"Запускаем…":"Запустить"}</button></div></div>{teamRuns(team.id).length>0&&<div style={{marginTop:14,borderTop:"1px solid #eee",paddingTop:10}}>{teamRuns(team.id).map(run=><Link key={run.id} href={`/app/runs/${run.id}`} style={{display:"flex",justifyContent:"space-between",gap:12,padding:"7px 0",textDecoration:"none",color:"inherit",fontSize:13}}><span><strong>{stateLabel[run.state]||run.state}</strong> · {run.objective.slice(0,90)}</span><span style={{opacity:.6}}>{run.step_count} шагов · {Number(run.cost_actual_rub||0).toFixed(2)} ₽</span></Link>)}</div>}</article>)}</div>}</section>
 </main>
}
