"use client";

import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";
import TeamReadinessBadge from "./TeamReadinessBadge";

type Member={id:string;agent:string;agent_name:string;role:string;priority:number;can_delegate:boolean;enabled:boolean};
type Team={id:string;project:string|null;name:string;objective:string;kind:string;director:string;director_name:string;active:boolean;max_cost_rub_per_run:string;members:Member[];updated_at:string};
type Run={id:string;team:string|null;state:string;objective:string;cost_actual_rub:string;step_count:number;created_at:string};

const kindLabel:Record<string,string>={generic:"Универсальная",marketing:"Маркетинг",content:"Контент",sales:"Продажи",development:"Разработка"};
const stateLabel:Record<string,string>={queued:"В очереди",planning:"Планирование",running:"Выполняется",waiting_tool:"Ожидает инструмент",waiting_approval:"Нужно подтверждение",reviewing:"Проверка",completed:"Готово",failed:"Ошибка",canceled:"Отменён",budget_exceeded:"Лимит бюджета"};

export default function TeamsPage(){
 const router=useRouter();
 const[teams,setTeams]=useState<Team[]>([]);const[runs,setRuns]=useState<Run[]>([]);const[readiness,setReadiness]=useState<Record<string,boolean>>({});const[goal,setGoal]=useState("");const[context,setContext]=useState("");const[independence,setIndependence]=useState("Обычные внутренние задачи выполнять самостоятельно");const[approvalRule,setApprovalRule]=useState("Публикации, отправки и другие внешние действия подтверждать у меня");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const genericTeams=useMemo(()=>teams.filter(team=>team.kind!=="development"),[teams]);
 const description=useMemo(()=>[goal.trim(),context.trim()?`Контекст бизнеса: ${context.trim()}.`:"",`Режим работы: ${independence}.`,`Правило подтверждений: ${approvalRule}.`].filter(Boolean).join(" "),[goal,context,independence,approvalRule]);
 const load=async()=>{try{const[t,r]=await Promise.all([api<Team[]>("/agent-teams/"),api<Run[]>("/agent-runs/")]);setTeams(t);setRuns(r);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить команды")}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!runs.some(run=>["queued","planning","running","reviewing","waiting_tool"].includes(run.state)))return;const timer=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(timer)},[runs]);
 const createTeam=async()=>{if(goal.trim().length<12){setError("Опишите, какой результат должна давать команда");return}setBusy("create");setError("");setNotice("");try{const team=await api<Team>("/agent-teams/from-description/",{method:"POST",body:JSON.stringify({description})});setTeams(current=>[team,...current]);setGoal("");setContext("");setNotice(`Команда «${team.name}» создана. Система назначила руководителя и роли.`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать команду")}finally{setBusy("")}};
 const runTeam=async(team:Team)=>{if(readiness[team.id]===false){setError("Сначала завершите настройку команды.");return}setBusy(`run:${team.id}`);setError("");try{const run=await api<Run>(`/agent-teams/${team.id}/run/`,{method:"POST",body:JSON.stringify({objective:team.objective})});router.push(`/app/runs/${run.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось запустить команду")}finally{setBusy("")}};
 const teamRuns=(teamId:string)=>runs.filter(run=>run.team===teamId).slice(0,3);
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"32px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:30}}><div><div style={{fontSize:13,opacity:.6,marginBottom:8}}>AI WORKSPACE · AGENT STUDIO</div><h1 style={{fontSize:38,margin:"0 0 10px"}}>Команды AI-сотрудников</h1><p style={{maxWidth:780,opacity:.72,fontSize:17}}>Опишите отдел простыми словами. Система сама создаст руководителя, распределит роли и соберёт последовательность работы. Для программирования используйте отдельный Dev Studio.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link href="/app/agents" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Одиночные агенты</Link><Link href="/app/schedules" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Автономность</Link><Link href="/app/dev" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Dev Studio</Link></div></header>
  {notice&&<div style={{padding:13,border:"1px solid #7aa78b",borderRadius:12,marginBottom:16}}>{notice}</div>}{error&&<div style={{padding:13,border:"1px solid #cb747a",borderRadius:12,marginBottom:16}}>{error}</div>}
  <section style={{border:"1px solid #ddd",borderRadius:22,padding:22,marginBottom:32}}><div style={{fontSize:12,opacity:.55,textTransform:"uppercase"}}>Новый отдел</div><h2 style={{margin:"8px 0"}}>Соберите команду без настройки ролей вручную</h2><div style={{display:"grid",gap:14,marginTop:16}}><label style={{display:"grid",gap:7}}><strong>1. Что должна делать команда?</strong><textarea rows={4} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Например: анализировать конкурентов, составлять контент-план, писать посты и проверять факты" style={{width:"100%",boxSizing:"border-box",padding:13,border:"1px solid #ccc",borderRadius:12,resize:"vertical",font:"inherit"}}/></label><label style={{display:"grid",gap:7}}><strong>2. Для какого бизнеса?</strong><textarea rows={3} value={context} onChange={e=>setContext(e.target.value)} placeholder="Например: сеть стоматологий в Москве, аудитория — взрослые 30–55 лет" style={{width:"100%",boxSizing:"border-box",padding:13,border:"1px solid #ccc",borderRadius:12,resize:"vertical",font:"inherit"}}/></label><label style={{display:"grid",gap:7}}><strong>3. Что команда может делать сама?</strong><select value={independence} onChange={e=>setIndependence(e.target.value)} style={{padding:11,border:"1px solid #ccc",borderRadius:10}}><option>Только готовить материалы и рекомендации</option><option>Обычные внутренние задачи выполнять самостоятельно</option><option>Работать максимально автономно в рамках бюджета и разрешений</option></select></label><label style={{display:"grid",gap:7}}><strong>4. Какие действия всегда спрашивать у вас?</strong><select value={approvalRule} onChange={e=>setApprovalRule(e.target.value)} style={{padding:11,border:"1px solid #ccc",borderRadius:10}}><option>Все действия подтверждать у меня</option><option>Публикации, отправки и другие внешние действия подтверждать у меня</option><option>Только необратимые и финансовые действия подтверждать у меня</option></select></label></div><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginTop:16}}><span style={{fontSize:13,opacity:.62}}>Система создаст директора и специалистов автоматически. Настройки можно изменить до запуска.</span><button onClick={()=>void createTeam()} disabled={!!busy||goal.trim().length<12} style={{padding:"11px 16px",border:0,borderRadius:11,fontWeight:700,cursor:"pointer"}}>{busy==="create"?"Создаём…":"Создать отдел"}</button></div></section>
  <section><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,marginBottom:14}}><div><h2 style={{margin:0}}>Мои команды</h2><p style={{opacity:.65,margin:"6px 0 0"}}>Руководитель передаёт результат между специалистами, общий расход ограничен бюджетом команды.</p></div></div>{!genericTeams.length?<div style={{border:"1px dashed #bbb",borderRadius:18,padding:34,textAlign:"center",opacity:.7}}>Команд пока нет. Соберите первый отдел выше.</div>:<div style={{display:"grid",gap:14}}>{genericTeams.map(team=><article key={team.id} style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:18}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><Link href={`/app/teams/${team.id}`} style={{fontSize:22,fontWeight:700,textDecoration:"none",color:"inherit"}}>{team.name}</Link><span style={{fontSize:12,border:"1px solid #ddd",borderRadius:999,padding:"4px 8px"}}>{kindLabel[team.kind]||team.kind}</span></div><p style={{opacity:.7,margin:"8px 0 12px"}}>{team.objective}</p><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{team.members.map(member=><span key={member.id} style={{fontSize:12,border:"1px solid #ddd",borderRadius:999,padding:"5px 8px"}}>{member.can_delegate?"★ ":""}{member.role}</span>)}</div><div style={{fontSize:13,opacity:.58,marginTop:12}}>Руководитель: {team.director_name} · лимит запуска {Number(team.max_cost_rub_per_run||0).toFixed(2)} ₽</div><TeamReadinessBadge teamId={team.id} onChange={ready=>setReadiness(current=>({...current,[team.id]:ready}))}/></div><div style={{display:"flex",gap:8,alignItems:"flex-start"}}><Link href={`/app/teams/${team.id}`} style={{padding:"10px 13px",border:"1px solid #ddd",borderRadius:10,textDecoration:"none",color:"inherit",whiteSpace:"nowrap"}}>Настроить</Link><button disabled={!!busy||!team.active||readiness[team.id]===false} onClick={()=>void runTeam(team)} style={{padding:"10px 14px",borderRadius:10,border:0,fontWeight:700,height:42,whiteSpace:"nowrap"}}>{busy===`run:${team.id}`?"Запускаем…":readiness[team.id]===false?"Настройте":"Запустить"}</button></div></div>{teamRuns(team.id).length>0&&<div style={{marginTop:14,borderTop:"1px solid #eee",paddingTop:10}}>{teamRuns(team.id).map(run=><Link key={run.id} href={`/app/runs/${run.id}`} style={{display:"flex",justifyContent:"space-between",gap:12,padding:"7px 0",textDecoration:"none",color:"inherit",fontSize:13}}><span><strong>{stateLabel[run.state]||run.state}</strong> · {run.objective.slice(0,90)}</span><span style={{opacity:.6}}>{run.step_count} шагов · {Number(run.cost_actual_rub||0).toFixed(2)} ₽</span></Link>)}</div>}</article>)}</div>}</section>
 </main>;
}
