"use client";

import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";
import styles from "./schedules.module.css";

type Agent={id:string;name:string;status:string;objective:string};
type Team={id:string;name:string;kind:string;active:boolean;objective:string};
type Cadence="interval"|"daily"|"weekdays"|"weekly";
type Schedule={id:string;agent:string|null;team:string|null;subject_name:string;subject_type:string;name:string;objective:string;enabled:boolean;cadence:Cadence;interval_minutes:number;local_time:string|null;timezone_name:string;weekdays:number[];next_run_at:string;last_run_at:string|null;last_run:string|null;skip_if_running:boolean};
type Run={id:string;state:string;objective:string;cost_actual_rub:string;created_at:string;finished_at:string|null;error_code?:string};

const intervals=[
 {value:60,label:"Каждый час"},
 {value:180,label:"Каждые 3 часа"},
 {value:360,label:"Каждые 6 часов"},
 {value:720,label:"Каждые 12 часов"},
 {value:1440,label:"Каждые 24 часа"},
 {value:10080,label:"Каждые 7 дней"},
];
const days=["Пн","Вт","Ср","Чт","Пт","Сб","Вс"];
const stateLabel:Record<string,string>={queued:"В очереди",planning:"Планирование",running:"Выполняется",waiting_tool:"Ожидает инструмент",waiting_approval:"Нужно подтверждение",reviewing:"Проверка",completed:"Готово",failed:"Ошибка",canceled:"Отменён",budget_exceeded:"Лимит бюджета"};

function scheduleText(item:Schedule){
 if(item.cadence==="daily")return `Каждый день в ${String(item.local_time||"").slice(0,5)} · ${item.timezone_name}`;
 if(item.cadence==="weekdays")return `По будням в ${String(item.local_time||"").slice(0,5)} · ${item.timezone_name}`;
 if(item.cadence==="weekly")return `${(item.weekdays||[]).map(day=>days[day]).join(", ")} в ${String(item.local_time||"").slice(0,5)} · ${item.timezone_name}`;
 return intervals.find(row=>row.value===item.interval_minutes)?.label||`Каждые ${item.interval_minutes} мин`;
}

export default function SchedulesPage(){
 const router=useRouter();
 const[agents,setAgents]=useState<Agent[]>([]);const[teams,setTeams]=useState<Team[]>([]);const[schedules,setSchedules]=useState<Schedule[]>([]);const[subjectType,setSubjectType]=useState<"agent"|"team">("agent");const[subject,setSubject]=useState("");const[name,setName]=useState("");const[objective,setObjective]=useState("");const[cadence,setCadence]=useState<Cadence>("daily");const[interval,setInterval]=useState(1440);const[localTime,setLocalTime]=useState("09:00");const[timezoneName,setTimezoneName]=useState("Europe/Moscow");const[weekdays,setWeekdays]=useState<number[]>([0,1,2,3,4]);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[history,setHistory]=useState<Record<string,Run[]>>({});const[historyOpen,setHistoryOpen]=useState<Record<string,boolean>>({});
 const load=async()=>{try{const[a,t,s]=await Promise.all([api<Agent[]>("/agents/"),api<Team[]>("/agent-teams/"),api<Schedule[]>("/agent-schedules/")]);setAgents(a.filter(x=>x.status==="active"));setTeams(t.filter(x=>x.active));setSchedules(s);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить расписания")}};
 useEffect(()=>{void load()},[]);
 const subjects=useMemo(()=>subjectType==="agent"?agents:teams,[subjectType,agents,teams]);
 useEffect(()=>{if(subject&&!subjects.some(x=>x.id===subject))setSubject("")},[subjectType,subjects,subject]);
 const toggleDay=(day:number)=>setWeekdays(current=>current.includes(day)?current.filter(x=>x!==day):[...current,day].sort());
 const create=async()=>{if(!subject){setError("Выберите агента или команду");return}if(cadence==="weekly"&&!weekdays.length){setError("Выберите хотя бы один день недели");return}setBusy("create");setError("");setNotice("");try{const payload:Record<string,unknown>={name:name.trim()||"Автономный запуск",objective:objective.trim(),cadence,interval_minutes:interval,timezone_name:timezoneName,skip_if_running:true};if(cadence!=="interval")payload.local_time=localTime;if(cadence==="weekly")payload.weekdays=weekdays;payload[subjectType]=subject;const created=await api<Schedule>("/agent-schedules/",{method:"POST",body:JSON.stringify(payload)});setName("");setObjective("");setSubject("");setNotice(`Автономная работа включена. Следующий запуск: ${new Date(created.next_run_at).toLocaleString("ru-RU")}.`);await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось создать расписание")}finally{setBusy("")}};
 const runNow=async(item:Schedule)=>{setBusy(`run:${item.id}`);setError("");setNotice("");try{const run=await api<Run>(`/agent-schedules/${item.id}/run-now/`,{method:"POST"});setHistory(current=>({...current,[item.id]:[run,...(current[item.id]||[]).filter(row=>row.id!==run.id)].slice(0,10)}));router.push(`/app/runs/${run.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось запустить задачу");setBusy("")}};
 const toggle=async(item:Schedule)=>{setBusy(item.id);setError("");try{await api<Schedule>(`/agent-schedules/${item.id}/`,{method:"PATCH",body:JSON.stringify({enabled:!item.enabled})});await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось изменить расписание")}finally{setBusy("")}};
 const remove=async(item:Schedule)=>{if(!window.confirm(`Удалить расписание «${item.name}»?`))return;setBusy(item.id);setError("");try{await api(`/agent-schedules/${item.id}/`,{method:"DELETE"});setHistory(current=>{const next={...current};delete next[item.id];return next});await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось удалить расписание")}finally{setBusy("")}};
 const toggleHistory=async(item:Schedule)=>{const open=!historyOpen[item.id];setHistoryOpen(current=>({...current,[item.id]:open}));if(!open||history[item.id])return;setBusy(`history:${item.id}`);setError("");try{const rows=await api<Run[]>(`/agent-schedules/${item.id}/history/?limit=10`);setHistory(current=>({...current,[item.id]:rows}))}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить историю запусков")}finally{setBusy("")}};
 const fmt=(value:string|null)=>value?new Date(value).toLocaleString("ru-RU"):"—";
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.top}><div><span className={styles.eyebrow}>AI WORKSPACE · AUTONOMY</span><h1>Когда сотрудник должен работать сам?</h1><p>Выберите понятное расписание. Агент или команда будут запускаться автоматически, без открытой вкладки браузера. Если предыдущая задача ещё выполняется, дубль не создаётся.</p></div><div className={styles.topLinks}><Link href="/app/agents">Агенты</Link><Link href="/app/teams">Команды</Link></div></header>
  {notice&&<div className={styles.notice} role="status">{notice}</div>}{error&&<div className={styles.error} role="alert">{error}</div>}
  <section className={styles.card}><h2>Новое расписание</h2><div className={styles.two}><label className={styles.field}>Кого запускать<select value={subjectType} onChange={e=>setSubjectType(e.target.value as "agent"|"team")}><option value="agent">Сотрудника</option><option value="team">Команду</option></select></label><label className={styles.field}>{subjectType==="agent"?"AI-сотрудник":"Команда"}<select value={subject} onChange={e=>setSubject(e.target.value)}><option value="">Выберите</option>{subjects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>
   <div className={styles.three}><label className={styles.field}>Как часто<select value={cadence} onChange={e=>setCadence(e.target.value as Cadence)}><option value="daily">Каждый день</option><option value="weekdays">По будням</option><option value="weekly">По выбранным дням</option><option value="interval">Через интервал</option></select></label>{cadence==="interval"?<label className={styles.field}>Интервал<select value={interval} onChange={e=>setInterval(Number(e.target.value))}>{intervals.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label>:<label className={styles.field}>Время<input type="time" value={localTime} onChange={e=>setLocalTime(e.target.value)}/></label>}<label className={styles.field}>Часовой пояс<select value={timezoneName} onChange={e=>setTimezoneName(e.target.value)} disabled={cadence==="interval"}><option value="Europe/Moscow">Москва</option><option value="Europe/Amsterdam">Амстердам / Центральная Европа</option><option value="Asia/Yekaterinburg">Екатеринбург</option><option value="Asia/Novosibirsk">Новосибирск</option><option value="Asia/Krasnoyarsk">Красноярск</option><option value="Asia/Irkutsk">Иркутск</option><option value="Asia/Vladivostok">Владивосток</option></select></label></div>
   {cadence==="weekly"&&<div className={styles.days}>{days.map((day,index)=><button type="button" key={day} className={`${styles.day} ${weekdays.includes(index)?styles.dayActive:""}`} aria-pressed={weekdays.includes(index)} onClick={()=>toggleDay(index)}>{day}</button>)}</div>}
   <label className={styles.field}>Название<input value={name} onChange={e=>setName(e.target.value)} placeholder="Например: Контент каждое утро"/></label><label className={styles.field}>Задача на каждый запуск<textarea rows={4} value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Если оставить пустым, будет использоваться постоянная цель агента или команды."/></label><div className={styles.formActions}><span>Расходы ограничены бюджетом самого агента или команды.</span><button className={styles.primary} disabled={busy==="create"||!subject} onClick={()=>void create()}>{busy==="create"?"Сохраняем…":"Включить автономную работу"}</button></div></section>
  <section className={styles.listSection}><h2>Расписания</h2>{!schedules.length?<div className={styles.empty}>Автономных запусков пока нет. Создайте расписание выше — повторный запуск не будет создан, пока предыдущая задача ещё выполняется.</div>:<div className={styles.list}>{schedules.map(item=>{const rows=history[item.id]||[];const open=!!historyOpen[item.id];return <article key={item.id} className={styles.schedule}><div className={styles.scheduleGrid}><div><div className={styles.titleRow}><strong>{item.name}</strong><span className={`${styles.status} ${!item.enabled?styles.statusPaused:""}`}>{item.enabled?"Включено":"Пауза"}</span></div><div className={styles.meta}>{item.subject_type==="agent"?"Сотрудник":"Команда"}: {item.subject_name}</div>{item.objective&&<p className={styles.objective}>{item.objective}</p>}<div className={styles.scheduleText}>{scheduleText(item)}</div><div className={styles.submeta}>Следующий запуск: {fmt(item.next_run_at)} · последний реальный запуск: {fmt(item.last_run_at)}</div></div><div className={styles.actions}><button className={styles.primary} disabled={!!busy} onClick={()=>void runNow(item)}>{busy===`run:${item.id}`?"Запускаем…":"Запустить сейчас"}</button><button className={styles.button} disabled={!!busy} onClick={()=>void toggleHistory(item)}>{busy===`history:${item.id}`?"Загрузка…":open?"Скрыть историю":"История"}</button><button className={styles.button} disabled={!!busy} onClick={()=>void toggle(item)}>{item.enabled?"Пауза":"Включить"}</button><button className={styles.danger} disabled={!!busy} onClick={()=>void remove(item)}>Удалить</button></div></div>{open&&<div className={styles.history}>{rows.length?<div className={styles.historyList}>{rows.map(run=><Link key={run.id} href={`/app/runs/${run.id}`} className={styles.historyRow}><span><strong>{stateLabel[run.state]||run.state}</strong> · {run.objective.slice(0,90)}</span><span>{Number(run.cost_actual_rub||0).toFixed(2)} ₽</span><span>{fmt(run.created_at)}</span></Link>)}</div>:<div className={styles.historyEmpty}>Запусков по этому расписанию ещё нет.</div>}</div>}</article>})}</div>}</section>
 </div></main>;
}
