"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";

type Agent={id:string;name:string;status:string;objective:string};
type Team={id:string;name:string;kind:string;active:boolean;objective:string};
type Schedule={id:string;agent:string|null;team:string|null;subject_name:string;subject_type:string;name:string;objective:string;enabled:boolean;interval_minutes:number;next_run_at:string;last_run_at:string|null;last_run:string|null;skip_if_running:boolean};

const intervals=[
 {value:60,label:"Каждый час"},
 {value:180,label:"Каждые 3 часа"},
 {value:360,label:"Каждые 6 часов"},
 {value:720,label:"Каждые 12 часов"},
 {value:1440,label:"Каждый день"},
 {value:10080,label:"Раз в неделю"},
];

export default function SchedulesPage(){
 const[agents,setAgents]=useState<Agent[]>([]);const[teams,setTeams]=useState<Team[]>([]);const[schedules,setSchedules]=useState<Schedule[]>([]);const[subjectType,setSubjectType]=useState<"agent"|"team">("agent");const[subject,setSubject]=useState("");const[name,setName]=useState("");const[objective,setObjective]=useState("");const[interval,setInterval]=useState(1440);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const load=async()=>{try{const[a,t,s]=await Promise.all([api<Agent[]>("/agents/"),api<Team[]>("/agent-teams/"),api<Schedule[]>("/agent-schedules/")]);setAgents(a.filter(x=>x.status==="active"));setTeams(t.filter(x=>x.active));setSchedules(s);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить расписания")}};
 useEffect(()=>{void load()},[]);
 const subjects=useMemo(()=>subjectType==="agent"?agents:teams,[subjectType,agents,teams]);
 useEffect(()=>{if(subject&&!subjects.some(x=>x.id===subject))setSubject("")},[subjectType,subjects,subject]);
 const create=async()=>{if(!subject){setError("Выберите агента или команду");return}setBusy("create");setError("");setNotice("");try{const payload:Record<string,unknown>={name:name.trim()||"Автономный запуск",objective:objective.trim(),interval_minutes:interval,skip_if_running:true};payload[subjectType]=subject;await api<Schedule>("/agent-schedules/",{method:"POST",body:JSON.stringify(payload)});setName("");setObjective("");setSubject("");setNotice("Расписание включено. Первый запуск произойдёт через выбранный интервал.");await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось создать расписание")}finally{setBusy("")}};
 const toggle=async(item:Schedule)=>{setBusy(item.id);try{await api<Schedule>(`/agent-schedules/${item.id}/`,{method:"PATCH",body:JSON.stringify({enabled:!item.enabled})});await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось изменить расписание")}finally{setBusy("")}};
 const remove=async(item:Schedule)=>{if(!window.confirm(`Удалить расписание «${item.name}»?`))return;setBusy(item.id);try{await api(`/agent-schedules/${item.id}/`,{method:"DELETE"});await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось удалить расписание")}finally{setBusy("")}};
 const fmt=(value:string|null)=>value?new Date(value).toLocaleString("ru-RU"):"—";
 return <main style={{maxWidth:1120,margin:"0 auto",padding:"32px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:30}}><div><div style={{fontSize:13,opacity:.6,marginBottom:8}}>AI WORKSPACE · AUTONOMY</div><h1 style={{fontSize:38,margin:"0 0 10px"}}>Автономные запуски</h1><p style={{maxWidth:760,opacity:.72,fontSize:17}}>Настройте, когда AI-сотрудник или команда должны работать сами. Параллельный дубль по умолчанию блокируется, а расходы всё равно ограничены бюджетами агента и команды.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link href="/app/agents" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Агенты</Link><Link href="/app/teams" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Команды</Link></div></header>
  {notice&&<div style={{padding:13,border:"1px solid #7aa78b",borderRadius:12,marginBottom:16}}>{notice}</div>}{error&&<div style={{padding:13,border:"1px solid #cb747a",borderRadius:12,marginBottom:16}}>{error}</div>}
  <section style={{border:"1px solid #ddd",borderRadius:22,padding:22,marginBottom:30}}><h2 style={{marginTop:0}}>Новое расписание</h2><div style={{display:"grid",gridTemplateColumns:"160px minmax(220px,1fr) minmax(180px,.7fr)",gap:12,marginBottom:12}}><label style={{display:"grid",gap:6}}>Кого запускать<select value={subjectType} onChange={e=>setSubjectType(e.target.value as "agent"|"team")} style={{padding:11,borderRadius:10,border:"1px solid #ccc"}}><option value="agent">Сотрудника</option><option value="team">Команду</option></select></label><label style={{display:"grid",gap:6}}>{subjectType==="agent"?"AI-сотрудник":"Команда"}<select value={subject} onChange={e=>setSubject(e.target.value)} style={{padding:11,borderRadius:10,border:"1px solid #ccc"}}><option value="">Выберите</option>{subjects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label style={{display:"grid",gap:6}}>Период<select value={interval} onChange={e=>setInterval(Number(e.target.value))} style={{padding:11,borderRadius:10,border:"1px solid #ccc"}}>{intervals.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label></div><label style={{display:"grid",gap:6,marginBottom:12}}>Название<input value={name} onChange={e=>setName(e.target.value)} placeholder="Например: Ежедневный контент" style={{padding:11,borderRadius:10,border:"1px solid #ccc"}}/></label><label style={{display:"grid",gap:6}}>Задача на каждый запуск<textarea rows={4} value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Если оставить пустым, будет использоваться постоянная цель агента или команды." style={{padding:12,borderRadius:11,border:"1px solid #ccc",resize:"vertical"}}/></label><div style={{display:"flex",justifyContent:"flex-end",marginTop:12}}><button disabled={busy==="create"||!subject} onClick={()=>void create()} style={{padding:"11px 16px",border:0,borderRadius:11,fontWeight:700}}>{busy==="create"?"Сохраняем…":"Включить автономную работу"}</button></div></section>
  <section><h2>Активные расписания</h2>{!schedules.length?<div style={{border:"1px dashed #bbb",borderRadius:18,padding:30,textAlign:"center",opacity:.7}}>Автономных запусков пока нет.</div>:<div style={{display:"grid",gap:12}}>{schedules.map(item=><article key={item.id} style={{border:"1px solid #ddd",borderRadius:17,padding:18}}><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:16}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:19}}>{item.name}</strong><span style={{fontSize:12,padding:"4px 8px",borderRadius:999,border:"1px solid #ddd"}}>{item.enabled?"Включено":"Пауза"}</span></div><div style={{opacity:.65,marginTop:5}}>{item.subject_type==="agent"?"Сотрудник":"Команда"}: {item.subject_name}</div>{item.objective&&<p style={{opacity:.72,margin:"8px 0"}}>{item.objective}</p>}<div style={{fontSize:13,opacity:.6}}>Интервал: {item.interval_minutes} мин · следующий запуск: {fmt(item.next_run_at)} · последний: {fmt(item.last_run_at)}</div></div><div style={{display:"flex",gap:8,alignItems:"flex-start"}}><button disabled={busy===item.id} onClick={()=>void toggle(item)} style={{padding:"9px 12px",border:"1px solid #ccc",borderRadius:9,background:"transparent"}}>{item.enabled?"Пауза":"Включить"}</button><button disabled={busy===item.id} onClick={()=>void remove(item)} style={{padding:"9px 12px",border:"1px solid #d99",borderRadius:9,background:"transparent"}}>Удалить</button></div></div></article>)}</div>}</section>
 </main>
}
