# Generated by Django 5.2.5 on 2026-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_supportrequest_userpreference_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="memory_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
