# Generated by Django 5.2.5 on 2026-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_userpreference_memory_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="auto_memory_default_scope",
            field=models.CharField(
                choices=[
                    ("global", "Все чаты"),
                    ("project", "Проект"),
                    ("conversation", "Только чат"),
                ],
                default="conversation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="auto_memory_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
