"use client";

import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../../lib/api";

type Member={id:string;role:string;enabled:boolean};
type Team={id:string;project:string|null;name:string;objective:string;kind:string;director_name:string;active:boolean;max_cost_rub_per_run:string;members:Member[]};
type Step={id:string;sequence:number;title:string;state:string;agent_name:string;public_log:string;cost_rub:string};
type Approval={id:string;title:string;status:string};
type Run={id:string;state:string;objective:string;cost_actual_rub:string;step_count:number;tool_call_count:number;created_at:string;steps:Step[];approvals:Approval[];output_payload?:{working_branch?:string;text?:string}};
type Binding={id:string;full_name:string;default_branch:string;write_enabled:boolean;private:boolean};
type Readiness={ready:boolean;blockers:string[];warnings:string[];actions:Array<{code:string;label:string;href?:string}>;models:Array<{role:string;level:string;model:string}>};
type Tab="work"|"settings";
const stateLabel:Record<string,string>={queued:"В очереди",planning:"Планирует",running:"Разрабатывает",waiting_tool:"Ждёт инструмент",waiting_approval:"Ждёт решения",reviewing:"Проверяет",completed:"Готово",failed:"Ошибка",canceled:"Остановлен",budget_exceeded:"Лимит бюджета"};
const activeStates=["queued","planning","running","waiting_tool","waiting_approval","reviewing"];

export default function DevDetailV2(){
 const params=useParams<{id:string}>();const router=useRouter();const id=String(params.id);const[team,setTeam]=useState<Team|null>(null);const[runs,setRuns]=useState<Run[]>([]);const[binding,setBinding]=useState<Binding|null>(null);const[readiness,setReadiness]=useState<Readiness|null>(null);const[tab,setTab]=useState<Tab>("work");const[task,setTask]=useState("");const[budget,setBudget]=useState("100.00");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const latest=useMemo(()=>runs[0]??null,[runs]);const activeRun=useMemo(()=>runs.find(item=>activeStates.includes(item.state))??null,[runs]);
 const loadReadiness=async()=>{try{const value=await api<Readiness>(`/agent-teams/${id}/readiness/`);setReadiness(value);return value}catch(e){const fallback={ready:false,blockers:[e instanceof Error?e.message:"Не удалось проверить готовность"],warnings:[],actions:[],models:[]};setReadiness(fallback);return fallback}};
 const load=async()=>{try{const[t,r,ready]=await Promise.all([api<Team>(`/agent-teams/${id}/`),api<Run[]>(`/agent-runs/?team=${encodeURIComponent(id)}`),loadReadiness()]);setTeam(t);setRuns(r);setReadiness(ready);setBudget(String(t.max_cost_rub_per_run||"100.00"));if(t.project){try{setBinding(await api<Binding>(`/projects/${t.project}/github/`))}catch{setBinding(null)}}setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить Dev-проект")}};
 useEffect(()=>{void load()},[id]);useEffect(()=>{if(!activeRun)return;const timer=window.setInterval(()=>void load(),3500);return()=>window.clearInterval(timer)},[activeRun?.id,id]);
 const run=async()=>{if(!team)return;if(activeRun){router.push(`/app/runs/${activeRun.id}`);return}setBusy("run");setError("");try{const fresh=await loadReadiness();if(!fresh.ready){setError("Перед запуском нужно исправить: "+fresh.blockers.join("; "));return}const started=await api<Run>(`/agent-teams/${id}/run/`,{method:"POST",body:JSON.stringify({objective:task.trim()||team.objective})});setTask("");router.push(`/app/runs/${started.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось запустить задачу")}finally{setBusy("")}};
 const saveBudget=async()=>{if(!team)return;const value=Number(budget.replace(",","."));if(!Number.isFinite(value)||value<=0){setError("Лимит должен быть больше нуля");return}setBusy("budget");setError("");try{const updated=await api<Team>(`/agent-teams/${id}/`,{method:"PATCH",body:JSON.stringify({max_cost_rub_per_run:value.toFixed(4)})});setTeam(updated);setBudget(String(updated.max_cost_rub_per_run));setNotice("Лимит сохранён.");await loadReadiness()}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить лимит")}finally{setBusy("")}};
 const toggleActive=async()=>{if(!team)return;if(team.active&&activeRun){setError("Сначала завершите активную задачу.");return}setBusy("active");try{const updated=await api<Team>(`/agent-teams/${id}/`,{method:"PATCH",body:JSON.stringify({active:!team.active})});setTeam(updated);setNotice(updated.active?"Команда снова активна.":"Команда поставлена на паузу.");await loadReadiness()}catch(e){setError(e instanceof Error?e.message:"Не удалось изменить состояние")}finally{setBusy("")}};
 if(!team)return <main className="studioPage"><div className="studioEmpty">{error||"Загружаем Dev-проект…"}</div></main>;
 return <main className="studioPage devDetailSimple"><header className="studioDetailHero"><div><Link href="/app/dev">← Dev Studio</Link><h1>{team.name}</h1><p>{binding?.full_name||"Проект разработки"} · {team.active?"готов к задачам":"на паузе"}</p></div>{latest&&<Link className="studioGhostLink" href={`/app/runs/${latest.id}`}>Последний запуск</Link>}</header>
  {notice&&<div className="studioAlert success">{notice}</div>}{error&&<div className="studioAlert error">{error}</div>}{activeRun&&<div className="studioAlert warning">Команда сейчас работает. <Link href={`/app/runs/${activeRun.id}`}>Открыть выполнение →</Link></div>}
  <nav className="studioTabs"><button className={tab==="work"?"active":""} onClick={()=>setTab("work")}>Работа</button><button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}>Настройки</button></nav>
  {tab==="work"&&<div className="studioDetailGrid"><section className="studioDetailMain"><article className="studioPanel primary"><span className="studioEyebrow">НОВАЯ ЗАДАЧА</span><h2>Что нужно изменить в проекте?</h2><textarea className="studioPrompt" rows={5} value={task} onChange={e=>setTask(e.target.value)} disabled={!!activeRun} placeholder={team.objective||"Опишите задачу обычными словами"}/><div className="studioCreateFooter"><span>{readiness?.ready?`Готово к запуску · лимит до ${Number(team.max_cost_rub_per_run||0).toFixed(2)} ₽`:"Перед запуском нужна проверка готовности."}</span><button className="studioPrimary" onClick={()=>void run()} disabled={!!busy||!team.active||readiness?.ready===false}>{busy==="run"?"Запускаем…":activeRun?"Открыть текущую задачу":readiness?.ready===false?"Нужна настройка":"Запустить команду"}</button></div></article>{latest&&<article className="studioPanel"><div className="studioPanelHead"><div><span className="studioEyebrow">ПОСЛЕДНЯЯ ЗАДАЧА</span><h2>{stateLabel[latest.state]||latest.state}</h2></div><Link href={`/app/runs/${latest.id}`}>Открыть →</Link></div><p className="studioLead">{latest.objective}</p><div className="studioMiniStats"><span>Шагов <b>{latest.step_count}</b></span><span>Инструментов <b>{latest.tool_call_count}</b></span><span>Расход <b>{Number(latest.cost_actual_rub||0).toFixed(2)} ₽</b></span></div>{latest.approvals?.some(item=>item.status==="pending")&&<div className="studioInlineWarning">Нужно ваше подтверждение. <Link href={`/app/runs/${latest.id}`}>Открыть запрос →</Link></div>}{latest.steps?.length>0&&<details className="studioDetails"><summary>Показать ход разработки</summary><div className="studioRunList">{latest.steps.map(step=><div className="studioStep" key={step.id}><span>{step.sequence}</span><div><b>{step.title}</b><small>{step.agent_name} · {stateLabel[step.state]||step.state}</small>{step.public_log&&<p>{step.public_log}</p>}</div><em>{Number(step.cost_rub||0).toFixed(2)} ₽</em></div>)}</div></details>}</article>}</section><aside className="studioDetailAside"><article className={`studioPanel ${readiness?.ready?"ready":"warning"}`}><span className="studioEyebrow">ГОТОВНОСТЬ</span><h3>{readiness?.ready?"Можно запускать":"Нужна настройка"}</h3>{readiness?.ready?<p className="studioMuted">Модели, доступ к коду и рабочая среда проверены.</p>:<><ul className="studioBlockers">{(readiness?.blockers||[]).map(item=><li key={item}>{item}</li>)}</ul>{readiness?.actions?.filter(item=>item.href).map(item=><Link key={item.code} href={item.href||"#"}>{item.label} →</Link>)}</>}</article></aside></div>}
  {tab==="settings"&&<div className="studioDetailGrid"><section className="studioDetailMain"><article className="studioPanel"><h2>Проект и GitHub</h2>{binding?<><div className="studioConnectionLine"><span>Репозиторий</span><b>{binding.full_name}</b></div><div className="studioConnectionLine"><span>Основная ветка</span><b>{binding.default_branch}</b></div><div className="studioConnectionLine"><span>Доступ</span><b>{binding.write_enabled?"Чтение и запись":"Только чтение"}</b></div></>:<div className="studioEmpty">GitHub не привязан. <Link href="/app/projects">Открыть проекты →</Link></div>}</article><article className="studioPanel"><h2>Команда</h2><div className="studioRoleRow">{team.members.filter(item=>item.enabled).map(item=><span key={item.id}>{item.role}</span>)}</div><p className="studioMuted">Состав команды управляется системой разработки; на основном экране показываются только роли, необходимые для выполнения задачи.</p></article></section><aside className="studioDetailAside"><article className="studioPanel"><h3>Расход на одну задачу</h3><label className="studioField"><span>Максимум, ₽</span><input inputMode="decimal" value={budget} onChange={e=>setBudget(e.target.value)}/></label><button className="studioGhost" onClick={()=>void saveBudget()} disabled={busy==="budget"}>{busy==="budget"?"Сохраняем…":"Сохранить лимит"}</button></article><article className="studioPanel"><h3>Состояние команды</h3><p className="studioMuted">Пауза запрещает новые задачи, но не удаляет проект и историю.</p><button className="studioGhost" onClick={()=>void toggleActive()} disabled={busy==="active"||Boolean(activeRun)}>{team.active?"Поставить на паузу":"Возобновить работу"}</button></article></aside></div>}
 </main>;
}
