"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {api} from "../../../../../lib/api";
import styles from "../../projects.module.css";

type Binding={id:string;repository_id:number;full_name:string;default_branch:string;private:boolean;write_enabled:boolean;last_synced_at:string|null};
type TreeItem={name:string;path:string;type:"file"|"dir";size:number;sha:string};
type Directory={path:string;ref:string;items:TreeItem[]};
type FilePayload={path:string;sha:string;size:number;content:string;ref:string};
type WriteResult={path:string;branch:string;content_sha:string;commit_sha:string};

export default function ProjectGitHubPage(){
 const params=useParams<{projectId:string}>();const projectId=params.projectId;
 const[binding,setBinding]=useState<Binding|null>(null);const[directory,setDirectory]=useState<Directory|null>(null);const[currentPath,setCurrentPath]=useState("");const[file,setFile]=useState<FilePayload|null>(null);const[content,setContent]=useState("");const[message,setMessage]=useState("AI Workspace update");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[saved,setSaved]=useState("");
 const loadDirectory=async(path="")=>{setBusy(true);setError("");setSaved("");try{const value=await api<Directory>(`/projects/${projectId}/github/tree/?path=${encodeURIComponent(path)}`);setDirectory(value);setCurrentPath(value.path);setFile(null);setContent("");}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось открыть каталог GitHub")}finally{setBusy(false)}};
 const openFile=async(path:string)=>{setBusy(true);setError("");setSaved("");try{const value=await api<FilePayload>(`/projects/${projectId}/github/file/?path=${encodeURIComponent(path)}`);setFile(value);setContent(value.content);}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось открыть файл GitHub")}finally{setBusy(false)}};
 useEffect(()=>{void(async()=>{try{const value=await api<Binding>(`/projects/${projectId}/github/`);setBinding(value);await loadDirectory("");}catch(reason){setError(reason instanceof Error?reason.message:"GitHub-репозиторий не подключён")}})()},[projectId]);
 const breadcrumbs=useMemo(()=>{const parts=currentPath?currentPath.split("/"):[];return parts.map((name,index)=>({name,path:parts.slice(0,index+1).join("/")}))},[currentPath]);
 const parentPath=useMemo(()=>currentPath.split("/").filter(Boolean).slice(0,-1).join("/"),[currentPath]);
 const save=async()=>{if(!binding?.write_enabled||!file)return;if(!window.confirm(`Записать изменения в ${file.path} ветки ${file.ref}?`))return;setBusy(true);setError("");setSaved("");try{const result=await api<WriteResult>(`/projects/${projectId}/github/file/`,{method:"PUT",body:JSON.stringify({path:file.path,content,expected_sha:file.sha,message:message.trim()||"AI Workspace update",branch:file.ref,confirm_write:true})});setFile({...file,sha:result.content_sha,content});setSaved(`Коммит ${result.commit_sha.slice(0,12)} создан`);}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось записать изменения. Возможно, файл уже изменился в GitHub — откройте его заново.")}finally{setBusy(false)}};
 return <main className={styles.page}><div className={styles.shell}><header className={styles.top}><div><h1>GitHub проекта</h1><p>{binding?`${binding.full_name} · ${binding.default_branch} · ${binding.write_enabled?"запись разрешена":"только чтение"}`:"Подключение репозитория"}</p></div><div className={styles.actions}><Link className={styles.button} href="/app/projects">← Проекты</Link><Link className={styles.button} href={`/app?project=${encodeURIComponent(projectId)}`}>Чаты проекта</Link></div></header>{error&&<div className={styles.notice}>{error}</div>}{saved&&<div className={styles.notice}>{saved}</div>}{binding&&<section className={styles.card}><div className={styles.actions} style={{marginBottom:12,flexWrap:"wrap"}}><button className={styles.button} onClick={()=>void loadDirectory("")} disabled={busy}>Корень</button>{breadcrumbs.map(item=><button key={item.path} className={styles.button} onClick={()=>void loadDirectory(item.path)} disabled={busy}>{item.name}</button>)}{currentPath&&<button className={styles.button} onClick={()=>void loadDirectory(parentPath)} disabled={busy}>↑ Выше</button>}<span style={{marginLeft:"auto"}}>{directory?.ref??binding.default_branch}</span></div>{!file?<div>{busy&&!directory?<p>Загружаем…</p>:directory?.items.length===0?<p>Папка пуста.</p>:directory?.items.map(item=><button key={item.path} type="button" className={styles.file} style={{width:"100%",textAlign:"left",display:"flex",justifyContent:"space-between",border:0,cursor:"pointer"}} onClick={()=>void(item.type==="dir"?loadDirectory(item.path):openFile(item.path))} disabled={busy}><span>{item.type==="dir"?"📁":"📄"} {item.name}</span><small>{item.type==="file"?`${(item.size/1024).toFixed(1)} КБ`:"папка"}</small></button>)}</div>:<div><div className={styles.actions} style={{marginBottom:8}}><button className={styles.button} onClick={()=>{setFile(null);setContent("")}}>← К списку</button><b>{file.path}</b><small>{(file.size/1024).toFixed(1)} КБ · SHA {file.sha.slice(0,12)}</small></div><textarea value={content} onChange={event=>setContent(event.target.value)} readOnly={!binding.write_enabled} spellCheck={false} style={{width:"100%",minHeight:"60vh",fontFamily:"ui-monospace, SFMono-Regular, Menlo, monospace",fontSize:13,lineHeight:1.5,padding:12,boxSizing:"border-box"}}/>{binding.write_enabled?<div className={styles.actions} style={{marginTop:10}}><input value={message} maxLength={240} onChange={event=>setMessage(event.target.value)} placeholder="Сообщение коммита" style={{flex:1,minWidth:260}}/><button className={`${styles.button} ${styles.primary}`} disabled={busy||content===file.content} onClick={()=>void save()}>{busy?"Сохраняем…":"Подтвердить и закоммитить"}</button></div>:<p>Редактирование отключено. Разрешить запись можно на странице проекта; чтение репозитория остаётся доступным.</p>}</div>}</section>}</div></main>;
}
