# Generated by Django 5.2.5 on 2026-08-23 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('context_window', models.PositiveIntegerField(default=8192)),
                ('max_output_tokens', models.PositiveIntegerField(default=2048)),
                ('input_price_rub_per_million', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('output_price_rub_per_million', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ai_registry.provider')),
            ],
        ),
    ]
