# Generated by Django 5.2.5 on 2026-08-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="upstream_model",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="provider",
            name="adapter_type",
            field=models.CharField(
                choices=[("echo", "Тестовый"), ("openai_responses", "OpenAI Responses API")],
                default="echo",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="api_base_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="credential_env",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
