# Generated by Django 5.2.5 on 2026-08-23 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_registry', '0002_aimodel_upstream_model_provider_adapter_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.AddField(
            model_name='aimodel',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='fallback_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_for', to='ai_registry.aimodel'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='routing_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='provider',
            name='circuit_opened_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='emergency_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='health_state',
            field=models.CharField(choices=[('unknown', 'Не проверен'), ('healthy', 'Работает'), ('degraded', 'Нестабилен'), ('open', 'Circuit открыт'), ('disabled', 'Отключён')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='provider',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='last_latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='priority',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='provider',
            name='region',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='provider',
            name='adapter_type',
            field=models.CharField(choices=[('echo', 'Тестовый'), ('openai_responses', 'OpenAI Responses API'), ('anthropic_messages', 'Anthropic Messages API'), ('deepseek_chat', 'DeepSeek Chat API')], default='echo', max_length=32),
        ),
        migrations.CreateModel(
            name='ReliabilityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('state', models.CharField(choices=[('open', 'Открыт'), ('recovered', 'Восстановлен')], default='open', max_length=16)),
                ('error_code', models.CharField(max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='ai_registry.provider')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('healthy', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='ai_registry.provider')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['provider', '-checked_at'], name='ai_registry_provide_3f3ba5_idx')],
            },
        ),
    ]
