"use client";

import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {api} from "../../../lib/api";
import styles from "./help.module.css";

type SupportItem={id:string;subject:string;category:string;status:string;admin_reply:string;replied_at:string|null;created_at:string};

const statusLabel:Record<string,string>={open:"Открыто",in_progress:"В работе",resolved:"Решено"};
const categoryLabel:Record<string,string>={billing:"Оплата и баланс",generation:"Ответы AI",files:"Файлы и проекты",account:"Аккаунт",other:"Другое"};
const faq=[
 ["Как выбрать режим AI?","Для большинства задач оставьте «Средний». «Простой» быстрее и экономнее, «Сложный» предназначен для анализа, кода и трудных задач. Если нужна конкретная нейросеть, откройте тот же переключатель рядом с полем сообщения и выберите модель вручную."],
 ["Как использовать фото и изображения?","В панели сообщения нажмите кнопку изображения или «+». Можно приложить PNG, JPEG или WebP для анализа и сравнения, а через ✨ — создать новое или изменить изображение с помощью OpenAI Images."],
 ["Как работает поиск в интернете?","Для актуальных запросов сервис использует web-search и показывает раскрываемый блок источников под ответом. Поиск имеет резервный канал: отказ одного поискового провайдера не должен обрывать чат."],
 ["Почему ответ остановился?","Если соединение с моделью оборвалось, уже полученный текст сохраняется. Сервис пытается переключиться на резервный AI-канал, а незавершённый денежный резерв освобождается автоматически."],
 ["Куда пропал мой текст?","Черновик сохраняется на устройстве и для существующего чата синхронизируется с сервером. После сбоя откройте тот же чат — повторно вводить длинный запрос обычно не нужно."],
 ["Нужно ли создавать проект, чтобы прикрепить файл?","Нет. В обычном чате можно приложить файл сразу — сервис автоматически создаст или переиспользует служебное пространство «Файлы чата». Проект нужен только когда вы хотите хранить общий контекст и материалы как отдельную рабочую область."],
 ["Где посмотреть списания?","Откройте «Баланс» для финансовой истории или «Использование» для расходов по моделям и периодам. Перед дорогими операциями сервис показывает максимальный резерв."],
];

export default function HelpPage(){
 const[items,setItems]=useState<SupportItem[]>([]);const[notice,setNotice]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 const load=async()=>{try{setItems(await api<SupportItem[]>("/auth/support/"));setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить обращения")}};
 useEffect(()=>{void load()},[]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setBusy(true);setError("");try{await api("/auth/support/",{method:"POST",body:JSON.stringify({subject:String(data.get("subject")||"").trim(),category:String(data.get("category")||"other"),message:String(data.get("message")||"").trim()})});form.reset();setNotice("Обращение отправлено. Оно появилось в истории ниже.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось отправить обращение")}finally{setBusy(false)}};
 return <main className={styles.page}><div className={styles.shell}><header className={styles.top}><div><span className={styles.eyebrow}>AI WORKSPACE · SUPPORT</span><h1>Помощь</h1><p>Быстрые ответы по работе сервиса и связь с поддержкой, если автоматическое восстановление не помогло.</p></div><Link href="/app">Вернуться в чат</Link></header>{notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={`${styles.notice} ${styles.error}`} role="alert"><span>{error}</span><button type="button" onClick={()=>void load()}>Повторить</button></div>}<div className={styles.grid}><section className={styles.card}><div className={styles.cardTitle}><span>САМОПОМОЩЬ</span><h2>Частые вопросы</h2></div>{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}<div className={styles.links}><Link href="/status">Статус сервиса</Link><Link href="/faq">Все вопросы и ответы</Link></div></section><section className={styles.card}><div className={styles.cardTitle}><span>ПОДДЕРЖКА</span><h2>Написать нам</h2></div><p className={styles.muted}>Опишите, что хотели сделать и что произошло. Не отправляйте пароли, API-ключи и платёжные данные.</p><form onSubmit={submit} className={styles.form}><label>Тема<input name="subject" maxLength={160} placeholder="Коротко о проблеме" required/></label><label>Категория<select name="category" defaultValue="other"><option value="billing">Оплата и баланс</option><option value="generation">Ответы AI</option><option value="files">Файлы и проекты</option><option value="account">Аккаунт</option><option value="other">Другое</option></select></label><label>Что произошло<textarea name="message" rows={6} maxLength={5000} placeholder="Например: выбрала Сложный режим, приложила PDF, после отправки…" required/></label><button disabled={busy}>{busy?"Отправляем…":"Отправить обращение"}</button></form></section></div><section className={styles.card}><div className={styles.cardTitle}><span>ИСТОРИЯ</span><h2>Мои обращения</h2></div>{items.length===0?<p className={styles.muted}>Обращений пока нет.</p>:<div className={styles.list}>{items.map(item=><div className={styles.row} key={item.id}><div className={styles.rowMain}><b>{item.subject}</b><small>{categoryLabel[item.category]??"Другое"} · {new Date(item.created_at).toLocaleString("ru-RU")}</small>{item.admin_reply&&<div className={styles.reply}><b>Ответ поддержки</b>{item.replied_at&&<small>{new Date(item.replied_at).toLocaleString("ru-RU")}</small>}<div>{item.admin_reply}</div></div>}</div><span className={styles.status}>{statusLabel[item.status]??item.status}</span></div>)}</div>}</section></div></main>;
}
