"use client";

import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {useEffect,useState} from "react";
import {api} from "../../../../lib/api";

type Member={id:string;agent:string;agent_name:string;role:string;priority:number;can_delegate:boolean;enabled:boolean};
type Team={id:string;name:string;objective:string;kind:string;director:string;director_name:string;active:boolean;max_cost_rub_per_run:string;max_handoffs:number;members:Member[]};
type Run={id:string;state:string;objective:string;cost_actual_rub:string;step_count:number;created_at:string};

const stateLabel:Record<string,string>={queued:"В очереди",planning:"Планирование",running:"Выполняется",waiting_tool:"Ожидает инструмент",waiting_approval:"Нужно подтверждение",reviewing:"Проверка",completed:"Готово",failed:"Ошибка",canceled:"Отменён",budget_exceeded:"Лимит бюджета"};

export default function TeamDetailPage(){
 const params=useParams<{id:string}>();const router=useRouter();const id=String(params.id);
 const[team,setTeam]=useState<Team|null>(null);const[runs,setRuns]=useState<Run[]>([]);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[objective,setObjective]=useState("");
 const load=async()=>{try{const[t,r]=await Promise.all([api<Team>(`/agent-teams/${id}/`),api<Run[]>(`/agent-runs/?team=${encodeURIComponent(id)}`)]);setTeam(t);setRuns(r.slice(0,30));setObjective(current=>current||t.objective);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить команду")}};
 useEffect(()=>{void load()},[id]);
 const patchTeam=async(body:Partial<Team>)=>{setBusy("team");setError("");setNotice("");try{const next=await api<Team>(`/agent-teams/${id}/`,{method:"PATCH",body:JSON.stringify(body)});setTeam(next);setNotice("Настройки команды сохранены.")}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить команду")}finally{setBusy("")}};
 const patchMember=async(member:Member,body:Partial<Member>)=>{setBusy(member.id);setError("");try{const next=await api<Team>(`/agent-teams/${id}/members/${member.id}/`,{method:"PATCH",body:JSON.stringify(body)});setTeam(next)}catch(e){setError(e instanceof Error?e.message:"Не удалось изменить участника")}finally{setBusy("")}};
 const removeMember=async(member:Member)=>{if(!window.confirm(`Удалить «${member.agent_name}» из команды?`))return;setBusy(member.id);setError("");try{const next=await api<Team>(`/agent-teams/${id}/members/${member.id}/`,{method:"DELETE"});setTeam(next)}catch(e){setError(e instanceof Error?e.message:"Не удалось удалить участника")}finally{setBusy("")}};
 const setDirector=async(member:Member)=>{setBusy(`director:${member.id}`);setError("");try{const next=await api<Team>(`/agent-teams/${id}/director/`,{method:"POST",body:JSON.stringify({agent:member.agent})});setTeam(next);setNotice(`${member.agent_name} назначен руководителем команды.`)}catch(e){setError(e instanceof Error?e.message:"Не удалось назначить руководителя")}finally{setBusy("")}};
 const run=async()=>{if(!team)return;setBusy("run");setError("");try{const started=await api<Run>(`/agent-teams/${id}/run/`,{method:"POST",body:JSON.stringify({objective:objective.trim()||team.objective})});router.push(`/app/runs/${started.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось запустить команду")}finally{setBusy("")}};
 if(!team)return <main style={{padding:32}}>{error||"Загрузка…"}</main>;
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"30px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",marginBottom:24}}><div><Link href="/app/teams" style={{textDecoration:"none",opacity:.65}}>← Все команды</Link><h1 style={{fontSize:36,margin:"10px 0 6px"}}>{team.name}</h1><div style={{opacity:.62}}>Руководитель: {team.director_name} · {team.active?"работает":"пауза"}</div></div><button onClick={()=>void patchTeam({active:!team.active})} disabled={!!busy} style={{padding:"10px 13px",border:"1px solid #ccc",borderRadius:10,background:"transparent"}}>{team.active?"Поставить на паузу":"Включить команду"}</button></header>
  {notice&&<div style={{padding:12,border:"1px solid #7da78a",borderRadius:11,marginBottom:14}}>{notice}</div>}{error&&<div style={{padding:12,border:"1px solid #c96d74",borderRadius:11,marginBottom:14}}>{error}</div>}
  <div style={{display:"grid",gridTemplateColumns:"minmax(0,1.2fr) minmax(300px,.8fr)",gap:18}}>
   <section style={{display:"grid",gap:16}}>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><h2 style={{marginTop:0}}>Цель команды</h2><textarea rows={5} value={team.objective} onChange={e=>setTeam({...team,objective:e.target.value})} style={{width:"100%",boxSizing:"border-box",padding:12,border:"1px solid #ccc",borderRadius:10,resize:"vertical"}}/><button disabled={busy==="team"} onClick={()=>void patchTeam({objective:team.objective})} style={{marginTop:10,padding:"9px 12px",border:0,borderRadius:9,fontWeight:700}}>Сохранить цель</button></article>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><h2 style={{marginTop:0}}>Состав и роли</h2><div style={{display:"grid",gap:10}}>{team.members.map(member=><div key={member.id} style={{border:"1px solid #ddd",borderRadius:13,padding:12}}><div style={{display:"grid",gridTemplateColumns:"minmax(150px,.8fr) minmax(180px,1fr) auto",gap:10,alignItems:"center"}}><div><strong>{member.agent_name}</strong><div style={{fontSize:12,opacity:.55}}>{member.agent===team.director?"★ Руководитель":"Участник"}</div></div><input value={member.role} onChange={e=>setTeam({...team,members:team.members.map(x=>x.id===member.id?{...x,role:e.target.value}:x)})} style={{padding:9,border:"1px solid #ccc",borderRadius:8}}/><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button disabled={busy===member.id} onClick={()=>void patchMember(member,{role:member.role,enabled:member.enabled})}>Сохранить</button>{member.agent!==team.director&&<button disabled={!!busy} onClick={()=>void setDirector(member)}>Сделать руководителем</button>}{member.agent!==team.director&&<button disabled={!!busy} onClick={()=>void patchMember(member,{enabled:!member.enabled})}>{member.enabled?"Пауза":"Включить"}</button>}{member.agent!==team.director&&<button disabled={!!busy} onClick={()=>void removeMember(member)}>Удалить</button>}</div></div></div>)}</div></article>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><h2 style={{marginTop:0}}>Запустить команду</h2><textarea rows={4} value={objective} onChange={e=>setObjective(e.target.value)} placeholder={team.objective} style={{width:"100%",boxSizing:"border-box",padding:12,border:"1px solid #ccc",borderRadius:10,resize:"vertical"}}/><button disabled={!!busy||!team.active} onClick={()=>void run()} style={{marginTop:10,padding:"11px 15px",border:0,borderRadius:10,fontWeight:700}}>{busy==="run"?"Запускаем…":"Запустить команду"}</button></article>
   </section>
   <aside style={{display:"grid",gap:16,alignContent:"start"}}>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><h3 style={{marginTop:0}}>Бюджет и координация</h3><label style={{display:"grid",gap:5,marginBottom:10}}>Лимит на запуск, ₽<input inputMode="decimal" value={team.max_cost_rub_per_run} onChange={e=>setTeam({...team,max_cost_rub_per_run:e.target.value})} style={{padding:9,border:"1px solid #ccc",borderRadius:8}}/></label><label style={{display:"grid",gap:5}}>Максимум передач между агентами<input type="number" min={1} max={500} value={team.max_handoffs} onChange={e=>setTeam({...team,max_handoffs:Number(e.target.value)})} style={{padding:9,border:"1px solid #ccc",borderRadius:8}}/></label><button disabled={busy==="team"} onClick={()=>void patchTeam({max_cost_rub_per_run:team.max_cost_rub_per_run,max_handoffs:team.max_handoffs})} style={{marginTop:10,padding:"9px 12px",border:"1px solid #ccc",borderRadius:9,background:"transparent"}}>Сохранить лимиты</button></article>
    <article style={{border:"1px solid #ddd",borderRadius:18,padding:20}}><h3 style={{marginTop:0}}>Последние запуски</h3>{runs.length?runs.slice(0,10).map(item=><Link key={item.id} href={`/app/runs/${item.id}`} style={{display:"block",padding:"9px 0",borderBottom:"1px solid #eee",textDecoration:"none",color:"inherit"}}><strong>{stateLabel[item.state]||item.state}</strong><div style={{fontSize:12,opacity:.6,marginTop:3}}>{item.step_count} шагов · {Number(item.cost_actual_rub||0).toFixed(2)} ₽</div></Link>):<p style={{opacity:.65}}>Запусков пока нет.</p>}</article>
    <Link href="/app/schedules" style={{display:"block",textDecoration:"none",border:"1px solid #ddd",borderRadius:14,padding:14,color:"inherit"}}><strong>Автономное расписание →</strong><div style={{fontSize:13,opacity:.6,marginTop:4}}>Запускайте эту команду автоматически.</div></Link>
   </aside>
  </div>
 </main>;
}
