# Generated by Django 5.2.5 on 2026-08-24 15:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0006_conversation_memory_enabled_and_more"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Пользователь"),
                            ("project", "Проект"),
                            ("conversation", "Чат"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("fact", "Факт"),
                            ("preference", "Предпочтение"),
                            ("instruction", "Инструкция"),
                            ("decision", "Решение"),
                        ],
                        default="fact",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(max_length=4000)),
                ("normalized_content", models.TextField(max_length=4000)),
                (
                    "importance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.50",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.00",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("source_kind", models.CharField(default="user_explicit", max_length=24)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активно"),
                            ("archived", "В архиве"),
                            ("superseded", "Заменено"),
                            ("deleted", "Удалено"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_items",
                        to="chat.conversation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_items",
                        to="projects.project",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memories",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-pinned", "-importance_score", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationMemoryUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content_snapshot", models.TextField(max_length=4000)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Пользователь"),
                            ("project", "Проект"),
                            ("conversation", "Чат"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_usages",
                        to="chat.generation",
                    ),
                ),
                (
                    "memory_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_usages",
                        to="memory_store.memoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="MemoryRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField(max_length=4000)),
                ("normalized_content", models.TextField(max_length=4000)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Пользователь"),
                            ("project", "Проект"),
                            ("conversation", "Чат"),
                        ],
                        max_length=20,
                    ),
                ),
                ("project_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("conversation_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="memory_store.memoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(
                fields=["owner", "scope", "status"], name="memory_stor_owner_i_b49f64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(fields=["project", "status"], name="memory_stor_project_154013_idx"),
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(
                fields=["conversation", "status"], name="memory_stor_convers_7997c5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("conversation__isnull", True),
                        ("project__isnull", True),
                        ("scope", "global"),
                    ),
                    models.Q(
                        ("conversation__isnull", True),
                        ("project__isnull", False),
                        ("scope", "project"),
                    ),
                    models.Q(
                        ("conversation__isnull", False),
                        ("project__isnull", True),
                        ("scope", "conversation"),
                    ),
                    _connector="OR",
                ),
                name="valid_memory_scope_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="generationmemoryusage",
            constraint=models.UniqueConstraint(
                fields=("generation", "position"), name="unique_generation_memory_position"
            ),
        ),
    ]
