# Generated by Django 5.2.5 on 2026-08-24 17:45

import django.core.validators
import django.db.models.deletion
import re
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_subject_keys(apps, _schema_editor):
    memory_item = apps.get_model("memory_store", "MemoryItem")
    rules = (
        (r"\bбюджет\b", "fact:budget"),
        (r"\b(?:ответ|отвечай|ответы)\b", "preference:answer_style"),
        (r"\b(?:язык|русск|английск)\b", "preference:language"),
        (r"\b(?:тон|стиль общения)\b", "preference:tone"),
        (r"\b(?:формат|таблиц|список)\b", "preference:format"),
        (r"\b(?:живу|город|локаци)\b", "fact:location"),
        (r"\b(?:работаю|роль|должност)\b", "fact:work_context"),
        (r"\b(?:использую|инструмент|стек)\b", "fact:tools"),
    )
    changed = []
    for item in memory_item.objects.filter(subject_key="").iterator():
        normalized = " ".join(item.content.strip().lower().split())
        item.subject_key = next(
            (key for pattern, key in rules if re.search(pattern, normalized)), ""
        )
        if item.subject_key:
            changed.append(item)
    if changed:
        memory_item.objects.bulk_update(changed, ["subject_key"])


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_conversation_memory_enabled_and_more"),
        ("memory_store", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryitem",
            name="subject_key",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.RunPython(backfill_subject_keys, migrations.RunPython.noop),
        migrations.AddField(
            model_name="memoryitem",
            name="trust_level",
            field=models.DecimalField(
                decimal_places=2,
                default="1.00",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.CreateModel(
            name="MemoryCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "suggested_scope",
                    models.CharField(
                        choices=[
                            ("global", "Пользователь"),
                            ("project", "Проект"),
                            ("conversation", "Чат"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("fact", "Факт"),
                            ("preference", "Предпочтение"),
                            ("instruction", "Инструкция"),
                            ("decision", "Решение"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("normalized_content", models.TextField(max_length=1000)),
                ("subject_key", models.CharField(max_length=160)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "trust_level",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.00",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("source_kind", models.CharField(default="direct_user", max_length=24)),
                ("extraction_version", models.CharField(default="rules-v1", max_length=32)),
                ("reason", models.CharField(max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("conflict", "Есть конфликт"),
                            ("duplicate", "Дубликат"),
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                            ("dismissed", "Скрыто"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_candidate",
                        to="memory_store.memoryitem",
                    ),
                ),
                (
                    "conflicts_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflicting_candidates",
                        to="memory_store.memoryitem",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_candidates",
                        to="chat.conversation",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicate_candidates",
                        to="memory_store.memoryitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_candidates",
                        to="projects.project",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_candidates",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "status", "created_at"],
                        name="memory_stor_owner_i_8507fa_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_message", "subject_key"),
                        name="unique_memory_candidate_subject_per_message",
                    )
                ],
            },
        ),
    ]
