# Generated by Django 5.2.5 on 2026-08-23 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Новый чат', max_length=200)),
                ('selected_model', models.CharField(default='echo-v1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент'), ('system', 'Система')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('saved', 'Сохранено'), ('streaming', 'Генерируется'), ('completed', 'Готово'), ('partial', 'Частично'), ('failed', 'Ошибка')], default='saved', max_length=16)),
                ('client_message_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('completed', 'Готово'), ('failed', 'Ошибка'), ('cancelled', 'Остановлено')], default='queued', max_length=16)),
                ('model', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('reservation_id', models.UUIDField(null=True)),
                ('provider_request_id', models.CharField(blank=True, max_length=200)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('actual_cost_rub', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('assistant_message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generation_response', to='chat.message')),
                ('user_message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generation_request', to='chat.message')),
            ],
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('conversation', 'client_message_id'), name='unique_client_message_per_conversation'),
        ),
    ]
