# Generated by Django 5.2.5 on 2026-08-23 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_registry', '0003_alter_provider_options_aimodel_capabilities_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='correlation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='generation',
            name='provider_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generation',
            name='routed_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='GenerationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_slug', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('running', 'Выполняется'), ('completed', 'Готово'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='running', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('retryable', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='chat.generation')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_attempts', to='ai_registry.provider')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('generation', 'sequence'), name='unique_generation_attempt_sequence')],
            },
        ),
    ]
