# Generated by Django 5.2.5 on 2026-08-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_generation_correlation_id_generation_provider_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='route_price_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
