# Generated by Django 5.2.5 on 2026-08-23 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_generation_route_price_snapshot'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='projects.project'),
        ),
    ]
