# Generated by Django 5.2.5 on 2026-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_conversationdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="memory_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="generation",
            name="context_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
