# Generated by Django 5.2.5 on 2026-08-25 18:52

import hashlib
import math
import re

import pgvector.django.vector
from django.db import migrations, models
from django.utils import timezone

WORD_RE = re.compile(r"[a-zа-яё0-9]{2,}", re.IGNORECASE)


def features(value):
    words = WORD_RE.findall(value.casefold())
    yield from (f"w:{word}" for word in words)
    yield from (f"b:{left}_{right}" for left, right in zip(words, words[1:], strict=False))
    for word in words:
        padded = f"^{word}$"
        yield from (f"c:{padded[index : index + 3]}" for index in range(len(padded) - 2))


def backfill_messages(apps, _schema_editor):
    Message = apps.get_model("chat", "Message")
    for message in Message.objects.exclude(content="").iterator():
        vector = [0.0] * 384
        for feature in features(message.content):
            digest = hashlib.sha256(feature.encode()).digest()
            vector[int.from_bytes(digest[:4], "big") % 384] += 1.0 if digest[4] & 1 else -1.0
        norm = math.sqrt(sum(value * value for value in vector))
        if norm:
            vector = [value / norm for value in vector]
        message.content_sha256 = hashlib.sha256(message.content.encode()).hexdigest()
        message.embedding = vector
        message.embedding_model = "local-history-hash-v1"
        message.indexed_at = timezone.now()
        message.save(update_fields=["content_sha256", "embedding", "embedding_model", "indexed_at"])


def create_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "CREATE INDEX chat_message_embedding_hnsw ON chat_message "
            "USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL"
        )


def drop_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP INDEX IF EXISTS chat_message_embedding_hnsw")


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_conversation_routing_mode_routingdecision"),
        ("files", "0002_rag_vector_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="content_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="message",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="embedding_model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="message",
            name="indexed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["role", "created_at"], name="message_role_created_idx"),
        ),
        migrations.RunPython(backfill_messages, migrations.RunPython.noop),
        migrations.RunPython(create_hnsw_index, drop_hnsw_index),
    ]
