# Generated by Django 5.2.5 on 2026-08-25 19:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_root_branches(apps, _schema_editor):
    Conversation = apps.get_model("chat", "Conversation")
    ConversationBranch = apps.get_model("chat", "ConversationBranch")
    Message = apps.get_model("chat", "Message")
    for conversation in Conversation.objects.iterator():
        branch = ConversationBranch.objects.create(
            conversation_id=conversation.id,
            title="Основная ветка",
            created_by_id=conversation.owner_id,
        )
        Message.objects.filter(conversation_id=conversation.id).update(branch_id=branch.id)
        conversation.active_branch_id = branch.id
        conversation.save(update_fields=["active_branch"])


class Migration(migrations.Migration):
    dependencies = [
        ("ai_registry", "0005_modelversion_and_provider_families"),
        ("chat", "0009_semantic_history_search"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(default="Основная ветка", max_length=160)),
                ("inherited_message_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="chat.conversation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "forked_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forked_branches",
                        to="chat.message",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="chat.conversationbranch",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompareRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("prompt", models.TextField()),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("previewed", "Ожидает подтверждения"),
                            ("running", "Выполняется"),
                            ("completed", "Готово"),
                            ("partial", "Частично"),
                            ("failed", "Ошибка"),
                        ],
                        default="previewed",
                        max_length=16,
                    ),
                ),
                ("model_slugs", models.JSONField(default=list)),
                ("expected_min_rub", models.DecimalField(decimal_places=4, max_digits=14)),
                ("expected_max_rub", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "actual_cost_rub",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("reservation_id", models.UUIDField(blank=True, null=True)),
                ("synthesis_model_slug", models.CharField(blank=True, max_length=100)),
                ("synthesis_output", models.TextField(blank=True)),
                (
                    "synthesis_cost_rub",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("synthesis_reservation_id", models.UUIDField(blank=True, null=True)),
                ("synthesis_pricing_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compare_runs",
                        to="chat.conversation",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compare_runs",
                        to="chat.message",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compare_runs",
                        to="chat.conversationbranch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="active_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_conversations",
                to="chat.conversationbranch",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.conversationbranch",
            ),
        ),
        migrations.RunPython(create_root_branches, migrations.RunPython.noop),
        migrations.CreateModel(
            name="CompareVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Выполняется"),
                            ("completed", "Готово"),
                            ("failed", "Ошибка"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("provider_request_id", models.CharField(blank=True, max_length=200)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("expected_min_rub", models.DecimalField(decimal_places=4, max_digits=14)),
                ("expected_max_rub", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "actual_cost_rub",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "provider_cost_rub",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("pricing_snapshot", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "compare_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="chat.comparerun",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compare_variants",
                        to="ai_registry.aimodel",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("compare_run", "model"), name="unique_compare_run_model"
                    )
                ],
            },
        ),
    ]
