"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";

type Connection={id:string;kind:string;name:string;base_url:string;username:string;secret_configured:boolean;enabled:boolean;health_state:string;last_error:string;last_checked_at:string|null;metadata:Record<string,unknown>};
type Agent={id:string;name:string;role:string;status:string;tool_policy:Record<string,unknown>};
type Binding={id:string;agent:string;connection:string;connection_name:string;connection_kind:string;connection_health:string;purpose:string;enabled:boolean};

const health:Record<string,string>={unknown:"Не проверено",healthy:"Работает",degraded:"Ошибка",disabled:"Отключено"};

export default function ConnectionsPage(){
 const[items,setItems]=useState<Connection[]>([]);const[agents,setAgents]=useState<Agent[]>([]);const[bindings,setBindings]=useState<Binding[]>([]);const[agentChoice,setAgentChoice]=useState<Record<string,string>>({});const[name,setName]=useState("Мой WordPress");const[url,setUrl]=useState("");const[username,setUsername]=useState("");const[secret,setSecret]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const load=async()=>{try{const[c,a,b]=await Promise.all([api<Connection[]>("/connections/"),api<Agent[]>("/agents/"),api<Binding[]>("/agent-connections/")]);setItems(c);setAgents(a.filter(x=>x.status!=="archived"));setBindings(b);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить подключения")}};
 useEffect(()=>{void load()},[]);
 const bindingByConnection=useMemo(()=>{const map:Record<string,Binding[]>= {};for(const item of bindings)(map[item.connection]??=[]).push(item);return map},[bindings]);
 const create=async()=>{if(!url.trim()||!username.trim()||!secret.trim()){setError("Укажите URL, пользователя и Application Password");return}setBusy("create");setError("");setNotice("");try{const item=await api<Connection>("/connections/",{method:"POST",body:JSON.stringify({kind:"wordpress",name:name.trim()||"WordPress",base_url:url.trim(),username:username.trim(),secret:secret.trim(),enabled:true})});setSecret("");setItems(current=>[...current,item]);setNotice("WordPress сохранён. Нажмите «Проверить», затем разрешите нужному AI-сотруднику использовать сайт.")}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить WordPress")}finally{setBusy("")}};
 const check=async(item:Connection)=>{setBusy(`check:${item.id}`);setError("");setNotice("");try{const next=await api<Connection>(`/connections/${item.id}/check/`,{method:"POST"});setItems(current=>current.map(x=>x.id===item.id?next:x));setNotice(`${item.name}: подключение работает.`)}catch(e){setError(e instanceof Error?e.message:"Проверка подключения не прошла");await load()}finally{setBusy("")}};
 const toggle=async(item:Connection)=>{setBusy(`toggle:${item.id}`);setError("");try{const next=await api<Connection>(`/connections/${item.id}/`,{method:"PATCH",body:JSON.stringify({enabled:!item.enabled})});setItems(current=>current.map(x=>x.id===item.id?next:x))}catch(e){setError(e instanceof Error?e.message:"Не удалось изменить подключение")}finally{setBusy("")}};
 const remove=async(item:Connection)=>{if(!window.confirm(`Удалить подключение «${item.name}»? Агенты больше не смогут его использовать.`))return;setBusy(`delete:${item.id}`);setError("");try{await api(`/connections/${item.id}/`,{method:"DELETE"});setItems(current=>current.filter(x=>x.id!==item.id));setBindings(current=>current.filter(x=>x.connection!==item.id))}catch(e){setError(e instanceof Error?e.message:"Не удалось удалить подключение")}finally{setBusy("")}};
 const bind=async(item:Connection)=>{const agent=agentChoice[item.id];if(!agent){setError("Выберите AI-сотрудника");return}if(item.health_state!=="healthy"){setError("Сначала нажмите «Проверить» и убедитесь, что WordPress работает");return}setBusy(`bind:${item.id}`);setError("");setNotice("");try{await api<Binding>("/agent-connections/",{method:"POST",body:JSON.stringify({agent,connection:item.id,purpose:"publish",enabled:true})});setNotice("Готово. Этот AI-сотрудник теперь может использовать WordPress в узле «Публикация» согласно своей политике подтверждений.");await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось привязать WordPress к агенту")}finally{setBusy("")}};
 const unbind=async(binding:Binding)=>{setBusy(`unbind:${binding.id}`);setError("");try{await api(`/agent-connections/${binding.id}/`,{method:"DELETE"});setBindings(current=>current.filter(x=>x.id!==binding.id))}catch(e){setError(e instanceof Error?e.message:"Не удалось убрать доступ агента")}finally{setBusy("")}};
 const agentName=(id:string)=>agents.find(x=>x.id===id)?.name||"AI-сотрудник";
 return <main style={{maxWidth:1120,margin:"0 auto",padding:"32px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:28}}><div><div style={{fontSize:13,opacity:.58}}>AI WORKSPACE · CONNECTIONS</div><h1 style={{fontSize:38,margin:"8px 0"}}>Подключения</h1><p style={{maxWidth:760,opacity:.7,fontSize:17}}>Подключите сервис один раз, проверьте соединение и выберите, какому AI-сотруднику разрешено его использовать. Пароли хранятся зашифрованно и никогда не передаются в промпт модели.</p></div><Link href="/app/agents" style={{padding:"10px 13px",border:"1px solid #ddd",borderRadius:11,textDecoration:"none",color:"inherit"}}>Agent Studio</Link></header>
  {notice&&<div style={{padding:12,border:"1px solid #7da78a",borderRadius:11,marginBottom:14}}>{notice}</div>}{error&&<div style={{padding:12,border:"1px solid #c96d74",borderRadius:11,marginBottom:14}}>{error}</div>}
  <section style={{border:"1px solid #ddd",borderRadius:20,padding:22,marginBottom:30}}><div style={{fontSize:12,opacity:.5,textTransform:"uppercase"}}>Новое подключение</div><h2 style={{margin:"7px 0"}}>WordPress</h2><p style={{opacity:.66}}>Нужен Application Password WordPress, а не основной пароль. Обычно его можно создать в профиле пользователя WordPress → Application Passwords.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><label style={{display:"grid",gap:5}}>Название<input value={name} onChange={e=>setName(e.target.value)} style={{padding:10,border:"1px solid #ccc",borderRadius:9}}/></label><label style={{display:"grid",gap:5}}>URL сайта<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.ru" style={{padding:10,border:"1px solid #ccc",borderRadius:9}}/></label><label style={{display:"grid",gap:5}}>Пользователь WordPress<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" style={{padding:10,border:"1px solid #ccc",borderRadius:9}}/></label><label style={{display:"grid",gap:5}}>Application Password<input value={secret} onChange={e=>setSecret(e.target.value)} type="password" autoComplete="new-password" style={{padding:10,border:"1px solid #ccc",borderRadius:9}}/></label></div><button disabled={!!busy} onClick={()=>void create()} style={{marginTop:12,padding:"10px 14px",border:0,borderRadius:10,fontWeight:700}}>{busy==="create"?"Сохраняем…":"Сохранить WordPress"}</button></section>
  <section><h2>Мои подключения</h2>{items.length?<div style={{display:"grid",gap:12}}>{items.map(item=>{const linked=bindingByConnection[item.id]||[];const availableAgents=agents.filter(agent=>!linked.some(binding=>binding.agent===agent.id));return <article key={item.id} style={{border:"1px solid #ddd",borderRadius:17,padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start"}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:20}}>{item.name}</strong><span style={{fontSize:12,border:"1px solid #ddd",borderRadius:999,padding:"4px 8px"}}>{health[item.health_state]||item.health_state}</span></div><div style={{fontSize:13,opacity:.62,marginTop:5}}>{item.base_url} · {item.username}</div><div style={{fontSize:12,opacity:.5,marginTop:4}}>Секрет: {item.secret_configured?"сохранён":"не задан"}{item.last_checked_at?` · проверено ${new Date(item.last_checked_at).toLocaleString("ru-RU")}`:""}</div>{item.last_error&&<div style={{color:"#b33140",fontSize:13,marginTop:6}}>{item.last_error}</div>}</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button disabled={!!busy||!item.enabled} onClick={()=>void check(item)}>Проверить</button><button disabled={!!busy} onClick={()=>void toggle(item)}>{item.enabled?"Отключить":"Включить"}</button><button disabled={!!busy} onClick={()=>void remove(item)}>Удалить</button></div></div>
    <div style={{borderTop:"1px solid #eee",marginTop:16,paddingTop:14}}><strong>Кто может публиковать</strong>{linked.length?<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:9}}>{linked.map(binding=><span key={binding.id} style={{display:"inline-flex",gap:7,alignItems:"center",border:"1px solid #ddd",borderRadius:999,padding:"6px 9px"}}>{agentName(binding.agent)}<button aria-label="Убрать доступ" disabled={!!busy} onClick={()=>void unbind(binding)} style={{border:0,background:"transparent",cursor:"pointer"}}>×</button></span>)}</div>:<div style={{fontSize:13,opacity:.6,marginTop:7}}>Пока ни один агент не имеет доступа.</div>}
    <div style={{display:"flex",gap:8,marginTop:12,flexWrap:"wrap"}}><select value={agentChoice[item.id]||""} onChange={e=>setAgentChoice(current=>({...current,[item.id]:e.target.value}))} disabled={!availableAgents.length} style={{minWidth:240,padding:"9px 10px",border:"1px solid #ccc",borderRadius:9}}><option value="">Выберите AI-сотрудника</option>{availableAgents.map(agent=><option value={agent.id} key={agent.id}>{agent.name}{agent.role?` · ${agent.role}`:""}</option>)}</select><button disabled={!!busy||!agentChoice[item.id]||item.health_state!=="healthy"} onClick={()=>void bind(item)}>{busy===`bind:${item.id}`?"Разрешаем…":"Разрешить публикацию"}</button></div>{item.health_state!=="healthy"&&<div style={{fontSize:12,opacity:.55,marginTop:7}}>Сначала проверьте подключение. Доступ к непроверенному сайту не выдаётся.</div>}</div>
   </article>})}</div>:<div style={{border:"1px dashed #bbb",borderRadius:16,padding:28,opacity:.65}}>Подключений пока нет.</div>}</section>
 </main>;
}
