"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";
import styles from "./connections.module.css";

type Connection={id:string;kind:string;name:string;base_url:string;username:string;secret_configured:boolean;enabled:boolean;health_state:string;last_error:string;last_checked_at:string|null;metadata:Record<string,unknown>};
type Agent={id:string;name:string;role:string;status:string;tool_policy:Record<string,unknown>};
type Binding={id:string;agent:string;connection:string;connection_name:string;connection_kind:string;connection_health:string;purpose:string;enabled:boolean};

const health:Record<string,string>={unknown:"Не проверено",healthy:"Работает",degraded:"Ошибка",disabled:"Отключено"};
const healthClass=(state:string)=>state==="healthy"?styles.healthHealthy:state==="degraded"?styles.healthDegraded:state==="disabled"?styles.healthDisabled:"";

export default function ConnectionsPage(){
 const[items,setItems]=useState<Connection[]>([]);const[agents,setAgents]=useState<Agent[]>([]);const[bindings,setBindings]=useState<Binding[]>([]);const[agentChoice,setAgentChoice]=useState<Record<string,string>>({});const[kind,setKind]=useState("wordpress");const[name,setName]=useState("Мой WordPress");const[url,setUrl]=useState("");const[username,setUsername]=useState("");const[secret,setSecret]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const load=async()=>{try{const[c,a,b]=await Promise.all([api<Connection[]>("/connections/"),api<Agent[]>("/agents/"),api<Binding[]>("/agent-connections/")]);setItems(c);setAgents(a.filter(x=>x.status!=="archived"));setBindings(b);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить подключения")}};
 useEffect(()=>{void load()},[]);
 const bindingByConnection=useMemo(()=>{const map:Record<string,Binding[]>= {};for(const item of bindings)(map[item.connection]??=[]).push(item);return map},[bindings]);
 const create=async()=>{if(!url.trim()||(kind==="wordpress"&&(!username.trim()||!secret.trim()))){setError("Укажите URL, пользователя и Application Password");return}setBusy("create");setError("");setNotice("");try{const item=await api<Connection>("/connections/",{method:"POST",body:JSON.stringify({kind,name:name.trim()||(kind==="http"?"HTTP API":"WordPress"),base_url:url.trim(),username:username.trim(),...(secret.trim()?{secret:secret.trim()}:{}),enabled:true})});setSecret("");setItems(current=>[...current,item]);setNotice("Подключение сохранено. Проверьте соединение и разрешите его нужному агенту.")}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить WordPress")}finally{setBusy("")}};
 const check=async(item:Connection)=>{setBusy(`check:${item.id}`);setError("");setNotice("");try{const next=await api<Connection>(`/connections/${item.id}/check/`,{method:"POST"});setItems(current=>current.map(x=>x.id===item.id?next:x));setNotice(`${item.name}: подключение работает.`)}catch(e){setError(e instanceof Error?e.message:"Проверка подключения не прошла");await load()}finally{setBusy("")}};
 const toggle=async(item:Connection)=>{setBusy(`toggle:${item.id}`);setError("");try{const next=await api<Connection>(`/connections/${item.id}/`,{method:"PATCH",body:JSON.stringify({enabled:!item.enabled})});setItems(current=>current.map(x=>x.id===item.id?next:x))}catch(e){setError(e instanceof Error?e.message:"Не удалось изменить подключение")}finally{setBusy("")}};
 const remove=async(item:Connection)=>{if(!window.confirm(`Удалить подключение «${item.name}»? Агенты больше не смогут его использовать.`))return;setBusy(`delete:${item.id}`);setError("");try{await api(`/connections/${item.id}/`,{method:"DELETE"});setItems(current=>current.filter(x=>x.id!==item.id));setBindings(current=>current.filter(x=>x.connection!==item.id))}catch(e){setError(e instanceof Error?e.message:"Не удалось удалить подключение")}finally{setBusy("")}};
 const bind=async(item:Connection)=>{const agent=agentChoice[item.id];if(!agent){setError("Выберите AI-сотрудника");return}if(item.health_state!=="healthy"){setError("Сначала проверьте подключение и убедитесь, что WordPress работает");return}setBusy(`bind:${item.id}`);setError("");setNotice("");try{await api<Binding>("/agent-connections/",{method:"POST",body:JSON.stringify({agent,connection:item.id,purpose:item.kind==="http"?"http":"publish",enabled:true})});setNotice("Агенту разрешено использовать подключение в визуальной схеме.");await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось привязать WordPress к агенту")}finally{setBusy("")}};
 const unbind=async(binding:Binding)=>{setBusy(`unbind:${binding.id}`);setError("");try{await api(`/agent-connections/${binding.id}/`,{method:"DELETE"});setBindings(current=>current.filter(x=>x.id!==binding.id))}catch(e){setError(e instanceof Error?e.message:"Не удалось убрать доступ агента")}finally{setBusy("")}};
 const agentName=(id:string)=>agents.find(x=>x.id===id)?.name||"AI-сотрудник";
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.top}><div><span className={styles.eyebrow}>AI WORKSPACE · CONNECTIONS</span><h1>Подключения</h1><p>Подключите сервис один раз, проверьте соединение и выберите, какому AI-сотруднику разрешено его использовать. Секреты хранятся зашифрованно и не передаются в промпт модели.</p></div><Link href="/app/agents">Agent Studio</Link></header>
  {notice&&<div className={styles.notice} role="status">{notice}</div>}{error&&<div className={`${styles.notice} ${styles.error}`} role="alert">{error}</div>}
  <section className={styles.card}><span className={styles.cardEyebrow}>Новое подключение</span><h2>Подключить сервис</h2><label className={styles.field}>Тип сервиса<select value={kind} onChange={e=>{setKind(e.target.value);setName(e.target.value==="http"?"Мой HTTP API":"Мой WordPress");setSecret("")}}><option value="wordpress">WordPress</option><option value="http">HTTP API · любой сервис с REST API</option></select></label><p>{kind==="http"?"Укажите HTTPS-адрес API. Если сервис использует Bearer-токен, добавьте его. Проверка выполняет GET по этому адресу; перенаправления не разрешены.":"Используйте Application Password WordPress из профиля пользователя сайта."}</p><div className={styles.formGrid}><label className={styles.field}>Название<input value={name} onChange={e=>setName(e.target.value)} placeholder="Мой WordPress"/></label><label className={styles.field}>URL сайта<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.ru" inputMode="url"/></label>{kind==="wordpress"&&<label className={styles.field}>Пользователь WordPress<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/></label>}<label className={styles.field}>{kind==="http"?"Bearer-токен · необязательно":"Application Password"}<input value={secret} onChange={e=>setSecret(e.target.value)} type="password" autoComplete="new-password"/></label></div><button className={styles.primary} disabled={!!busy} onClick={()=>void create()}>{busy==="create"?"Сохраняем…":"Сохранить подключение"}</button></section>
  <section className={styles.listSection}><h2>Мои подключения</h2>{items.length?<div className={styles.list}>{items.map(item=>{const linked=bindingByConnection[item.id]||[];const availableAgents=agents.filter(agent=>!linked.some(binding=>binding.agent===agent.id));return <article key={item.id} className={styles.connection}><div className={styles.connectionHead}><div className={styles.identity}><div className={styles.titleRow}><strong>{item.name}</strong><span className={`${styles.health} ${healthClass(item.health_state)}`}>{health[item.health_state]||item.health_state}</span></div><div className={styles.meta}>{item.base_url} · {item.username}</div><div className={styles.submeta}>Секрет: {item.secret_configured?"сохранён":"не задан"}{item.last_checked_at?` · проверено ${new Date(item.last_checked_at).toLocaleString("ru-RU")}`:""}</div>{item.last_error&&<div className={styles.lastError}>{item.last_error}</div>}</div><div className={styles.actions}><button className={styles.secondary} disabled={!!busy||!item.enabled} onClick={()=>void check(item)}>{busy===`check:${item.id}`?"Проверяем…":"Проверить"}</button><button className={styles.secondary} disabled={!!busy} onClick={()=>void toggle(item)}>{busy===`toggle:${item.id}`?"Сохраняем…":item.enabled?"Отключить":"Включить"}</button><button className={styles.danger} disabled={!!busy} onClick={()=>void remove(item)}>{busy===`delete:${item.id}`?"Удаляем…":"Удалить"}</button></div></div>
    <div className={styles.permissions}><strong>Доступ агентов</strong>{linked.length?<div className={styles.boundList}>{linked.map(binding=><span key={binding.id} className={styles.boundChip}>{agentName(binding.agent)}<button aria-label={`Убрать доступ: ${agentName(binding.agent)}`} disabled={!!busy} onClick={()=>void unbind(binding)}>×</button></span>)}</div>:<div className={styles.emptyInline}>Пока ни один агент не имеет доступа.</div>}
    <div className={styles.bindRow}><select value={agentChoice[item.id]||""} onChange={e=>setAgentChoice(current=>({...current,[item.id]:e.target.value}))} disabled={!availableAgents.length} aria-label={`AI-сотрудник для ${item.name}`}><option value="">Выберите AI-сотрудника</option>{availableAgents.map(agent=><option value={agent.id} key={agent.id}>{agent.name}{agent.role?` · ${agent.role}`:""}</option>)}</select><button className={styles.bindButton} disabled={!!busy||!agentChoice[item.id]||item.health_state!=="healthy"} onClick={()=>void bind(item)}>{busy===`bind:${item.id}`?"Разрешаем…":"Разрешить доступ"}</button></div>{item.health_state!=="healthy"&&<div className={styles.guardHint}>Сначала проверьте подключение. Доступ к непроверенному сайту не выдаётся.</div>}</div>
   </article>})}</div>:<div className={styles.emptyState}>Подключений пока нет. Добавьте WordPress выше — после проверки его можно безопасно привязать к нужному AI-сотруднику.</div>}</section>
 </div></main>;
}
