"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {api} from "../../../lib/api";

type Connection={id:string;kind:string;name:string;base_url:string;username:string;secret_configured:boolean;enabled:boolean;health_state:string;last_error:string;last_checked_at:string|null;metadata:Record<string,unknown>};

const health:Record<string,string>={unknown:"Не проверено",healthy:"Работает",degraded:"Ошибка",disabled:"Отключено"};

export default function ConnectionsPage(){
 const[items,setItems]=useState<Connection[]>([]);const[name,setName]=useState("Мой WordPress");const[url,setUrl]=useState("");const[username,setUsername]=useState("");const[secret,setSecret]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const load=async()=>{try{setItems(await api<Connection[]>("/connections/"));setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить подключения")}};
 useEffect(()=>{void load()},[]);
 const create=async()=>{if(!url.trim()||!username.trim()||!secret.trim()){setError("Укажите URL, пользователя и Application Password");return}setBusy("create");setError("");setNotice("");try{const item=await api<Connection>("/connections/",{method:"POST",body:JSON.stringify({kind:"wordpress",name:name.trim()||"WordPress",base_url:url.trim(),username:username.trim(),secret:secret.trim(),enabled:true})});setSecret("");setItems(current=>[...current,item]);setNotice("WordPress сохранён. Теперь проверьте соединение.")}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить WordPress")}finally{setBusy("")}};
 const check=async(item:Connection)=>{setBusy(`check:${item.id}`);setError("");setNotice("");try{const next=await api<Connection>(`/connections/${item.id}/check/`,{method:"POST"});setItems(current=>current.map(x=>x.id===item.id?next:x));setNotice(`${item.name}: подключение работает.`)}catch(e){setError(e instanceof Error?e.message:"Проверка подключения не прошла");await load()}finally{setBusy("")}};
 const toggle=async(item:Connection)=>{setBusy(`toggle:${item.id}`);setError("");try{const next=await api<Connection>(`/connections/${item.id}/`,{method:"PATCH",body:JSON.stringify({enabled:!item.enabled})});setItems(current=>current.map(x=>x.id===item.id?next:x))}catch(e){setError(e instanceof Error?e.message:"Не удалось изменить подключение")}finally{setBusy("")}};
 const remove=async(item:Connection)=>{if(!window.confirm(`Удалить подключение «${item.name}»? Агенты больше не смогут его использовать.`))return;setBusy(`delete:${item.id}`);setError("");try{await api(`/connections/${item.id}/`,{method:"DELETE"});setItems(current=>current.filter(x=>x.id!==item.id))}catch(e){setError(e instanceof Error?e.message:"Не удалось удалить подключение")}finally{setBusy("")}};
 return <main style={{maxWidth:1120,margin:"0 auto",padding:"32px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:28}}><div><div style={{fontSize:13,opacity:.58}}>AI WORKSPACE · CONNECTIONS</div><h1 style={{fontSize:38,margin:"8px 0"}}>Подключения</h1><p style={{maxWidth:760,opacity:.7,fontSize:17}}>Подключайте сервисы один раз, затем разрешайте конкретным AI-сотрудникам использовать их. Пароли хранятся зашифрованно и никогда не показываются агенту.</p></div><Link href="/app/agents" style={{padding:"10px 13px",border:"1px solid #ddd",borderRadius:11,textDecoration:"none",color:"inherit"}}>Agent Studio</Link></header>
  {notice&&<div style={{padding:12,border:"1px solid #7da78a",borderRadius:11,marginBottom:14}}>{notice}</div>}{error&&<div style={{padding:12,border:"1px solid #c96d74",borderRadius:11,marginBottom:14}}>{error}</div>}
  <section style={{border:"1px solid #ddd",borderRadius:20,padding:22,marginBottom:30}}><div style={{fontSize:12,opacity:.5,textTransform:"uppercase"}}>Новое подключение</div><h2 style={{margin:"7px 0"}}>WordPress</h2><p style={{opacity:.66}}>Используйте Application Password WordPress, а не основной пароль аккаунта. URL должен быть публичным HTTPS/HTTP адресом сайта.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><label style={{display:"grid",gap:5}}>Название<input value={name} onChange={e=>setName(e.target.value)} style={{padding:10,border:"1px solid #ccc",borderRadius:9}}/></label><label style={{display:"grid",gap:5}}>URL сайта<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.ru" style={{padding:10,border:"1px solid #ccc",borderRadius:9}}/></label><label style={{display:"grid",gap:5}}>Пользователь WordPress<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" style={{padding:10,border:"1px solid #ccc",borderRadius:9}}/></label><label style={{display:"grid",gap:5}}>Application Password<input value={secret} onChange={e=>setSecret(e.target.value)} type="password" autoComplete="new-password" style={{padding:10,border:"1px solid #ccc",borderRadius:9}}/></label></div><button disabled={!!busy} onClick={()=>void create()} style={{marginTop:12,padding:"10px 14px",border:0,borderRadius:10,fontWeight:700}}>{busy==="create"?"Сохраняем…":"Сохранить WordPress"}</button></section>
  <section><h2>Мои подключения</h2>{items.length?<div style={{display:"grid",gap:12}}>{items.map(item=><article key={item.id} style={{border:"1px solid #ddd",borderRadius:17,padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start"}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:20}}>{item.name}</strong><span style={{fontSize:12,border:"1px solid #ddd",borderRadius:999,padding:"4px 8px"}}>{health[item.health_state]||item.health_state}</span></div><div style={{fontSize:13,opacity:.62,marginTop:5}}>{item.base_url} · {item.username}</div><div style={{fontSize:12,opacity:.5,marginTop:4}}>Секрет: {item.secret_configured?"сохранён":"не задан"}{item.last_checked_at?` · проверено ${new Date(item.last_checked_at).toLocaleString("ru-RU")}`:""}</div>{item.last_error&&<div style={{color:"#b33140",fontSize:13,marginTop:6}}>{item.last_error}</div>}</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button disabled={!!busy||!item.enabled} onClick={()=>void check(item)}>Проверить</button><button disabled={!!busy} onClick={()=>void toggle(item)}>{item.enabled?"Отключить":"Включить"}</button><button disabled={!!busy} onClick={()=>void remove(item)}>Удалить</button></div></div></article>)}</div>:<div style={{border:"1px dashed #bbb",borderRadius:16,padding:28,opacity:.65}}>Подключений пока нет.</div>}</section>
 </main>;
}
