"use client";

import {useEffect,useState} from "react";
import {api} from "../../../lib/api";
import styles from "../admin.module.css";

type Evidence={passed_at:string;evidence_reference:string;checksum_sha256:string;fresh:boolean};
type DrillStatus={max_age_hours:number;ready:boolean;restore:{fresh:boolean;restored_at:string|null;evidence_reference:string};rollback:{fresh:boolean;created_at:string|null;evidence_reference:string};drills:Record<string,Evidence|null>};
const label:Record<string,string>={load:"Load smoke",chaos:"Chaos restart",commercial_e2e:"Commercial E2E",provider_outage:"Provider outage",duplicate_webhook:"Duplicate webhook",payment_failure:"Payment failure",refund:"Refund flow",stale_recovery:"Stale recovery"};
export default function DrillsAdmin(){const[data,setData]=useState<DrillStatus|null>(null);const[error,setError]=useState("");const load=async()=>{try{setData(await api<DrillStatus>("/admin/drills/"));setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить drills");}};useEffect(()=>{void load();},[]);return <><header className={styles.header}><div><h1>Launch drills</h1><p>Свежие эксплуатационные доказательства, обязательные перед коммерческим запуском.</p></div><button className={styles.button} onClick={()=>void load()}>Обновить</button></header>{error&&<div className={`${styles.notice} ${styles.error}`}>{error}</div>}{data&&<><section className={styles.grid}><div className={styles.card}><small>Launch state</small><strong className={data.ready?styles.good:styles.bad}>{data.ready?"READY":"BLOCKED"}</strong></div><div className={styles.card}><small>Restore drill</small><strong className={data.restore.fresh?styles.good:styles.bad}>{data.restore.fresh?"PASS":"MISSING"}</strong></div><div className={styles.card}><small>Rollback drill</small><strong className={data.rollback.fresh?styles.good:styles.bad}>{data.rollback.fresh?"PASS":"MISSING"}</strong></div><div className={styles.card}><small>Freshness</small><strong>{data.max_age_hours} ч</strong></div></section><section className={styles.section}><h2>Operational evidence</h2><table className={styles.table}><thead><tr><th>Проверка</th><th>Статус</th><th>Время</th><th>Evidence</th><th>SHA256</th></tr></thead><tbody>{Object.entries(data.drills).map(([kind,item])=><tr key={kind}><td>{label[kind]??kind}</td><td><span className={styles.pill}>{item?.fresh?"PASS":"MISSING / STALE"}</span></td><td>{item?new Date(item.passed_at).toLocaleString("ru"):"—"}</td><td>{item?.evidence_reference||"—"}</td><td><code>{item?.checksum_sha256?item.checksum_sha256.slice(0,16)+"…":"—"}</code></td></tr>)}</tbody></table></section><section className={styles.section}><h2>Как закрыть блокеры</h2><p><code>bash scripts/production_drills.sh --confirm-production-drills</code> выполняет автоматические load/chaos/E2E проверки. Provider/payment drills записываются только после реального проверенного сценария через <code>scripts/record_manual_drill.sh</code>. Restore и rollback должны быть фактически выполнены соответствующими drill-скриптами.</p></section></>}</>}
