# Generated by Django 5.2.5 on 2026-08-23 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_name", models.CharField(max_length=80)),
                ("object_id", models.CharField(max_length=80)),
                ("payload_hash", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                ("result", models.CharField(blank=True, max_length=80)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentFeeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(default="yookassa", max_length=32)),
                ("payment_method", models.CharField(default="unknown", max_length=50)),
                ("percent", models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ("fixed_rub", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("effective_from", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Выполняется"),
                            ("succeeded", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("checked_count", models.PositiveIntegerField(default=0)),
                ("corrected_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(default="yookassa", max_length=32)),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, max_length=80, null=True, unique=True),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("amount_rub", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="RUB", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создан локально"),
                            ("pending", "Ожидает оплаты"),
                            ("succeeded", "Оплачен"),
                            ("canceled", "Отменён"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                ("confirmation_url", models.URLField(blank=True)),
                ("return_url", models.URLField()),
                ("description", models.CharField(max_length=128)),
                (
                    "receipt_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Не требуется настройкой"),
                            ("pending", "Ожидается"),
                            ("succeeded", "Сформирован"),
                            ("failed", "Ошибка"),
                            ("legal_review", "Нужна юридическая проверка"),
                        ],
                        default="legal_review",
                        max_length=20,
                    ),
                ),
                ("provider_payload", models.JSONField(blank=True, default=dict)),
                ("last_error", models.CharField(blank=True, max_length=200)),
                ("credited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentCostSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("gross_rub", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "net_received_rub",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "acquiring_fee_rub",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                ("source", models.CharField(default="provider", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost",
                        to="payments.payment",
                    ),
                ),
                (
                    "fee_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.paymentfeeversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(blank=True, max_length=80, null=True, unique=True),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("amount_rub", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создан локально"),
                            ("pending", "В обработке"),
                            ("succeeded", "Завершён"),
                            ("canceled", "Отменён"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                ("provider_payload", models.JSONField(blank=True, default=dict)),
                ("wallet_debited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
        ),
    ]
