"use client";

import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";

type Agent={id:string;name:string;role:string;objective:string;status:string;autonomy:string;updated_at:string};
type Template={slug:string;name:string;role:string;objective:string;autonomy:string;system_level:string};
type Autonomy="controlled"|"semi_autonomous"|"autonomous";
type OpsSummary={agents:{total:number;active:number};runs:{active:number;waiting_approval:number;failed_30d:number;budget_exceeded_30d:number};approvals:{pending:number};cost:{actual_rub_30d:string}};

const autonomyText:Record<Autonomy,string>={controlled:"Только готовить результат",semi_autonomous:"Работать самостоятельно, важное согласовывать",autonomous:"Работать автономно в заданных пределах"};
const statusText:Record<string,string>={draft:"Черновик",active:"Работает",paused:"Пауза",archived:"Архив"};
const sourceOptions=[["web","Интернет"],["files","Мои файлы"],["site","Мой сайт"]] as const;

export default function AgentStudioV2(){
 const router=useRouter();
 const[agents,setAgents]=useState<Agent[]>([]);const[templates,setTemplates]=useState<Template[]>([]);const[summary,setSummary]=useState<OpsSummary|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");
 const[description,setDescription]=useState("");const[details,setDetails]=useState(false);const[business,setBusiness]=useState("");const[sources,setSources]=useState<string[]>(["web"]);const[autonomy,setAutonomy]=useState<Autonomy>("semi_autonomous");const[schedule,setSchedule]=useState("По необходимости");
 const load=async()=>{setLoading(true);try{const[a,t,s]=await Promise.all([api<Agent[]>("/agents/"),api<Template[]>("/agents/templates/"),api<OpsSummary>("/agents/operations/summary/")]);setAgents(a);setTemplates(t);setSummary(s);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить AI-сотрудников")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const sourceText=useMemo(()=>[sources.includes("web")?"актуальный интернет-поиск":"",sources.includes("files")?"файлы и проекты пользователя":"",sources.includes("site")?"информацию с сайта":""].filter(Boolean).join(", "),[sources]);
 const toggleSource=(value:string)=>setSources(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value]);
 const create=async()=>{if(description.trim().length<12){setError("Опишите, что должен делать AI-сотрудник");return}setBusy("create");setError("");try{const enriched=[description.trim(),details&&business.trim()?`Контекст бизнеса: ${business.trim()}.`:"",details&&sourceText?`Используй: ${sourceText}.`:"",details?`Режим работы: ${autonomyText[autonomy]}. Частота: ${schedule}.`:""].filter(Boolean).join(" ");const agent=await api<Agent>("/agents/from-description/",{method:"POST",body:JSON.stringify({description:enriched})});if(details){await api(`/agents/${agent.id}/config/`,{method:"PATCH",body:JSON.stringify({autonomy,instructions:`Контекст пользователя: ${business.trim()||"не указан"}. Желаемая частота: ${schedule}.`})})}router.push(`/app/agents/${agent.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать AI-сотрудника")}finally{setBusy("")}};
 const createTemplate=async(slug:string)=>{setBusy(slug);setError("");try{const agent=await api<Agent>("/agents/from-template/",{method:"POST",body:JSON.stringify({template:slug})});router.push(`/app/agents/${agent.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать сотрудника")}finally{setBusy("")}};
 const money=(value:string|undefined)=>Number(value||0).toLocaleString("ru-RU",{minimumFractionDigits:2,maximumFractionDigits:2});
 return <main className="studioPage">
  <header className="studioHero"><div><span className="studioEyebrow">AGENT STUDIO</span><h1>Создайте AI-сотрудника обычными словами</h1><p>Опишите результат. Система сама соберёт роль, инструкции и карту действий. Технические настройки можно открыть позже.</p></div><div className="studioHeroActions"><Link href="/app/teams">Команды</Link><Link href="/app/runs">Запуски</Link></div></header>
  {error&&<div className="studioAlert error">{error}</div>}
  <section className="studioCreateCard"><div className="studioCreateIntro"><div><span>Новый сотрудник</span><h2>Что он должен делать?</h2></div><button type="button" className="studioGhost" onClick={()=>setDetails(v=>!v)}>{details?"Скрыть настройки":"Настроить подробнее"}</button></div><textarea className="studioPrompt" rows={5} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Например: каждый день находи темы для соцсетей, готовь посты и изображения, а перед публикацией показывай мне результат на согласование."/>
   {details&&<div className="studioAdvanced"><label><span>Контекст бизнеса <small>необязательно</small></span><textarea rows={2} value={business} onChange={e=>setBusiness(e.target.value)} placeholder="Например: стоматология в Москве, аудитория 30–55 лет"/></label><div><span className="studioFieldLabel">Источники</span><div className="studioChips">{sourceOptions.map(([value,label])=><button type="button" key={value} className={sources.includes(value)?"active":""} onClick={()=>toggleSource(value)}>{sources.includes(value)?"✓ ":""}{label}</button>)}</div></div><label><span>Самостоятельность</span><select value={autonomy} onChange={e=>setAutonomy(e.target.value as Autonomy)}><option value="controlled">Только готовить — действия подтверждаю я</option><option value="semi_autonomous">Работать самому — важное согласовывать</option><option value="autonomous">Работать автономно в заданных пределах</option></select></label><label><span>Когда работать</span><select value={schedule} onChange={e=>setSchedule(e.target.value)}><option>По необходимости</option><option>Каждый день</option><option>По будням</option><option>Раз в неделю</option><option>Несколько раз в день</option></select></label></div>}
   <div className="studioCreateFooter"><span>Сначала создаётся безопасный черновик. Внешние действия не запускаются автоматически.</span><button className="studioPrimary" onClick={()=>void create()} disabled={busy==="create"||description.trim().length<12}>{busy==="create"?"Создаём…":"Создать сотрудника"}</button></div>
  </section>
  {summary&&<section className="studioStats"><Link href="/app/runs"><span>Работает сейчас</span><b>{summary.runs.active}</b></Link><Link href="/app/runs"><span>Ждут решения</span><b>{summary.approvals.pending}</b></Link><div><span>Расход · 30 дней</span><b>{money(summary.cost.actual_rub_30d)} ₽</b></div></section>}
  <section className="studioSection"><div className="studioSectionHead"><div><h2>Мои сотрудники</h2><p>Открывайте сотрудника, чтобы увидеть задачи, память, расписание и разрешения.</p></div></div>{loading?<div className="studioEmpty">Загружаем сотрудников…</div>:agents.length?<div className="studioCards">{agents.map(agent=><Link href={`/app/agents/${agent.id}`} className="studioCard" key={agent.id}><div className="studioCardTop"><span className={`studioStatus ${agent.status}`}>{statusText[agent.status]||agent.status}</span><small>{autonomyText[(agent.autonomy as Autonomy)]||agent.autonomy}</small></div><h3>{agent.name}</h3><p>{agent.objective||"Цель пока не описана"}</p><span className="studioOpen">Открыть →</span></Link>)}</div>:<div className="studioEmpty">Пока нет сотрудников. Опишите первого выше — это займёт один шаг.</div>}</section>
  {templates.length>0&&<section className="studioSection compact"><div className="studioSectionHead"><div><h2>Быстрый старт</h2><p>Готовые роли, если не хочется начинать с пустого поля.</p></div></div><div className="studioTemplateRow">{templates.slice(0,6).map(item=><button type="button" key={item.slug} onClick={()=>void createTemplate(item.slug)} disabled={!!busy}><b>{item.name}</b><span>{item.objective}</span></button>)}</div></section>}
 </main>;
}
