"use client";

import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useState} from "react";
import {api} from "../../../lib/api";

type Agent={id:string;name:string;role:string;objective:string;status:string;autonomy:string;system_level:string;updated_at:string};
type Template={slug:string;name:string;role:string;objective:string;autonomy:string;system_level:string};

const statusLabel:Record<string,string>={draft:"Черновик",active:"Работает",paused:"Пауза",archived:"Архив"};
const autonomyLabel:Record<string,string>={controlled:"Контролируемый",semi_autonomous:"Полуавтономный",autonomous:"Автономный"};

export default function AgentsPage(){
 const router=useRouter();
 const[agents,setAgents]=useState<Agent[]>([]);const[templates,setTemplates]=useState<Template[]>([]);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[description,setDescription]=useState("");
 const load=async()=>{try{const[a,t]=await Promise.all([api<Agent[]>("/agents/"),api<Template[]>("/agents/templates/")]);setAgents(a);setTemplates(t);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить агентов")}};
 useEffect(()=>{void load()},[]);
 const create=async(slug:string)=>{setBusy(slug);setError("");try{const agent=await api<Agent>("/agents/from-template/",{method:"POST",body:JSON.stringify({template:slug})});router.push(`/app/agents/${agent.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать агента")}finally{setBusy("")}};
 const createFromDescription=async()=>{if(description.trim().length<12){setError("Опишите сотрудника чуть подробнее");return}setBusy("description");setError("");try{const agent=await api<Agent>("/agents/from-description/",{method:"POST",body:JSON.stringify({description:description.trim()})});router.push(`/app/agents/${agent.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать агента")}finally{setBusy("")}};
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"32px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:32}}><div><div style={{fontSize:13,opacity:.6,marginBottom:8}}>AI WORKSPACE · AGENT STUDIO</div><h1 style={{fontSize:38,margin:"0 0 10px"}}>Ваши AI-сотрудники</h1><p style={{maxWidth:760,opacity:.72,fontSize:17}}>Опишите сотрудника обычным языком. Система сама подберёт роль, инструменты, уровень автономности и построит карту действий, которую можно изменить до запуска.</p></div><Link href="/app" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>← В чат</Link></header>
  {error&&<div style={{padding:14,border:"1px solid #d66",borderRadius:12,marginBottom:20}}>{error}</div>}
  <section style={{border:"1px solid #ddd",borderRadius:22,padding:22,marginBottom:34}}><div style={{fontSize:12,opacity:.55,textTransform:"uppercase"}}>Создать с нуля</div><h2 style={{margin:"8px 0"}}>Какого сотрудника вы хотите нанять?</h2><p style={{opacity:.68,marginTop:0}}>Например: «Нужен SMM-специалист, который каждый день ищет темы, пишет посты, делает изображения и перед публикацией просит подтверждение».</p><textarea rows={5} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Опишите результат, обязанности и ограничения сотрудника..." style={{width:"100%",boxSizing:"border-box",padding:14,border:"1px solid #ccc",borderRadius:13,resize:"vertical",font:"inherit"}}/><div style={{display:"flex",justifyContent:"flex-end",marginTop:12}}><button onClick={()=>void createFromDescription()} disabled={!!busy||description.trim().length<12} style={{padding:"11px 16px",border:0,borderRadius:11,fontWeight:700,cursor:"pointer"}}>{busy==="description"?"Создаём…":"Создать сотрудника"}</button></div></section>
  <section style={{marginBottom:34}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,marginBottom:14}}><div><h2 style={{margin:0}}>Готовые сотрудники</h2><p style={{opacity:.65,margin:"6px 0 0"}}>Быстрый старт с уже собранной картой действий.</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14}}>{templates.map(item=><article key={item.slug} style={{border:"1px solid #ddd",borderRadius:18,padding:18}}><div style={{fontSize:12,opacity:.55,textTransform:"uppercase"}}>{item.role}</div><h3 style={{fontSize:21,margin:"8px 0"}}>{item.name}</h3><p style={{opacity:.7,minHeight:88}}>{item.objective}</p><button disabled={!!busy} onClick={()=>void create(item.slug)} style={{width:"100%",padding:"11px 14px",border:0,borderRadius:11,cursor:"pointer",fontWeight:700}}>{busy===item.slug?"Создаём…":"Нанять"}</button></article>)}</div></section>
  <section><div style={{marginBottom:14}}><h2 style={{margin:0}}>Мои агенты</h2><p style={{opacity:.65,margin:"6px 0 0"}}>Откройте сотрудника, настройте карту действий, лимиты и запустите задачу.</p></div>{!agents.length?<div style={{border:"1px dashed #bbb",borderRadius:18,padding:34,textAlign:"center",opacity:.7}}>Пока нет AI-сотрудников.</div>:<div style={{display:"grid",gap:10}}>{agents.map(agent=><article key={agent.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:16,border:"1px solid #ddd",borderRadius:16,padding:18}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:19}}>{agent.name}</strong><span style={{fontSize:12,padding:"4px 8px",borderRadius:999,border:"1px solid #ddd"}}>{statusLabel[agent.status]||agent.status}</span></div><div style={{opacity:.62,marginTop:5}}>{agent.role||"AI-сотрудник"} · {autonomyLabel[agent.autonomy]||agent.autonomy}</div><p style={{opacity:.72,marginBottom:0}}>{agent.objective||"Цель пока не задана"}</p></div><div style={{display:"flex",alignItems:"center"}}><Link href={`/app/agents/${agent.id}`} style={{textDecoration:"none",padding:"10px 13px",border:"1px solid #ddd",borderRadius:10}}>Открыть</Link></div></article>)}</div>}</section>
 </main>
}
