"use client";

import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";

type Agent={id:string;name:string;role:string;objective:string;instructions?:string;status:string;autonomy:string;system_level:string;updated_at:string};
type Template={slug:string;name:string;role:string;objective:string;autonomy:string;system_level:string};
type Autonomy="controlled"|"semi_autonomous"|"autonomous";

const statusLabel:Record<string,string>={draft:"Черновик",active:"Работает",paused:"Пауза",archived:"Архив"};
const autonomyLabel:Record<string,string>={controlled:"Контролируемый",semi_autonomous:"Полуавтономный",autonomous:"Автономный"};
const sourceOptions=[["web","Интернет и поиск"],["files","Мои файлы и проекты"],["site","Мой сайт"],["none","Только мои инструкции"]] as const;

export default function AgentsPage(){
 const router=useRouter();
 const[agents,setAgents]=useState<Agent[]>([]);const[templates,setTemplates]=useState<Template[]>([]);const[busy,setBusy]=useState("");const[error,setError]=useState("");
 const[work,setWork]=useState("");const[business,setBusiness]=useState("");const[sources,setSources]=useState<string[]>(["web"]);const[autonomy,setAutonomy]=useState<Autonomy>("semi_autonomous");const[scheduleHint,setScheduleHint]=useState("По необходимости");const[advanced,setAdvanced]=useState(false);const[description,setDescription]=useState("");
 const load=async()=>{try{const[a,t]=await Promise.all([api<Agent[]>("/agents/"),api<Template[]>("/agents/templates/")]);setAgents(a);setTemplates(t);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить агентов")}};
 useEffect(()=>{void load()},[]);
 const toggleSource=(value:string)=>setSources(current=>{if(value==="none")return current.includes("none")?[]:["none"];const next=current.filter(item=>item!=="none");return next.includes(value)?next.filter(item=>item!==value):[...next,value]});
 const wizardDescription=useMemo(()=>{
  const sourceText=sources.includes("none")?"Работать только по моим инструкциям без внешнего поиска.":[sources.includes("web")?"использовать актуальный интернет-поиск":"",sources.includes("files")?"использовать файлы и материалы моих проектов":"",sources.includes("site")?"учитывать информацию с моего сайта":""].filter(Boolean).join(", ");
  return [work.trim(),business.trim()?`Контекст компании или задачи: ${business.trim()}.`:"",sourceText?`Источники: ${sourceText}.`:"",`Желаемый режим работы: ${autonomy==="controlled"?"готовить результат и ждать моего решения перед действиями":autonomy==="semi_autonomous"?"обычные действия выполнять самостоятельно, внешние и важные действия подтверждать у меня":"работать максимально автономно в пределах разрешений и бюджета"}.`,`Желаемая частота: ${scheduleHint}.`].filter(Boolean).join(" ");
 },[work,business,sources,autonomy,scheduleHint]);
 const create=async(slug:string)=>{setBusy(slug);setError("");try{const agent=await api<Agent>("/agents/from-template/",{method:"POST",body:JSON.stringify({template:slug})});router.push(`/app/agents/${agent.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать агента")}finally{setBusy("")}};
 const createFromWizard=async()=>{const text=advanced?description.trim():wizardDescription.trim();if(text.length<12){setError("Опишите, что сотрудник должен делать");return}setBusy("description");setError("");try{const agent=await api<Agent>("/agents/from-description/",{method:"POST",body:JSON.stringify({description:text})});const instructions=advanced?"":`Контекст пользователя: ${business.trim()||"не указан"}. Предпочтительный режим: ${autonomyLabel[autonomy]}. Желаемая частота работы: ${scheduleHint}.`;const configured=await api<Agent>(`/agents/${agent.id}/config/`,{method:"PATCH",body:JSON.stringify({autonomy,instructions})});router.push(`/app/agents/${configured.id}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать агента")}finally{setBusy("")}};
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"32px 20px 70px"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:32}}><div><div style={{fontSize:13,opacity:.6,marginBottom:8}}>AI WORKSPACE · AGENT STUDIO</div><h1 style={{fontSize:38,margin:"0 0 10px"}}>Ваши AI-сотрудники</h1><p style={{maxWidth:760,opacity:.72,fontSize:17}}>Создайте сотрудника обычными словами. Вам не нужно знать, что такое промпты, API или workflow: система сама подготовит роль и карту действий, а вы сможете проверить всё до запуска.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link href="/app/teams" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Команды</Link><Link href="/app/schedules" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Автономность</Link><Link href="/app/dev" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>Dev Studio</Link><Link href="/app" style={{textDecoration:"none",padding:"10px 14px",border:"1px solid #ddd",borderRadius:12}}>← В чат</Link></div></header>
  {error&&<div style={{padding:14,border:"1px solid #d66",borderRadius:12,marginBottom:20}}>{error}</div>}
  <section style={{border:"1px solid #ddd",borderRadius:22,padding:22,marginBottom:34}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><div style={{fontSize:12,opacity:.55,textTransform:"uppercase"}}>Создать сотрудника</div><h2 style={{margin:"8px 0"}}>{advanced?"Опишите всё одним текстом":"Ответьте на несколько простых вопросов"}</h2></div><button type="button" onClick={()=>setAdvanced(value=>!value)} style={{padding:"8px 11px",border:"1px solid #ccc",borderRadius:9,background:"transparent"}}>{advanced?"Простой режим":"Я хочу описать сам"}</button></div>
   {advanced?<><p style={{opacity:.68,marginTop:0}}>Например: «Нужен SMM-специалист, который каждый день ищет темы, пишет посты, делает изображения и перед публикацией просит подтверждение».</p><textarea rows={6} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Опишите результат, обязанности и ограничения сотрудника..." style={{width:"100%",boxSizing:"border-box",padding:14,border:"1px solid #ccc",borderRadius:13,resize:"vertical",font:"inherit"}}/></>:<div style={{display:"grid",gap:16}}>
    <label style={{display:"grid",gap:7}}><strong>1. Что должен делать сотрудник?</strong><textarea rows={4} value={work} onChange={e=>setWork(e.target.value)} placeholder="Например: вести соцсети, находить темы, писать посты и готовить изображения" style={{padding:13,border:"1px solid #ccc",borderRadius:12,resize:"vertical",font:"inherit"}}/></label>
    <label style={{display:"grid",gap:7}}><strong>2. Для какого бизнеса или задачи?</strong><textarea rows={3} value={business} onChange={e=>setBusiness(e.target.value)} placeholder="Например: стоматология в Москве, целевая аудитория — взрослые 30–55 лет" style={{padding:13,border:"1px solid #ccc",borderRadius:12,resize:"vertical",font:"inherit"}}/></label>
    <div><strong>3. Откуда брать информацию?</strong><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:9}}>{sourceOptions.map(([value,label])=><button type="button" key={value} onClick={()=>toggleSource(value)} style={{padding:"9px 12px",borderRadius:999,border:"1px solid #bbb",fontWeight:sources.includes(value)?700:400,opacity:sources.includes(value)?1:.6}}>{sources.includes(value)?"✓ ":""}{label}</button>)}</div></div>
    <label style={{display:"grid",gap:7}}><strong>4. Насколько самостоятельно он может работать?</strong><select value={autonomy} onChange={e=>setAutonomy(e.target.value as Autonomy)} style={{padding:11,border:"1px solid #ccc",borderRadius:10}}><option value="controlled">Только готовить результат, действия подтверждаю я</option><option value="semi_autonomous">Работать сам, важные действия подтверждаю я</option><option value="autonomous">Работать максимально самостоятельно в заданных пределах</option></select></label>
    <label style={{display:"grid",gap:7}}><strong>5. Когда он должен работать?</strong><select value={scheduleHint} onChange={e=>setScheduleHint(e.target.value)} style={{padding:11,border:"1px solid #ccc",borderRadius:10}}><option>По необходимости</option><option>Каждый день</option><option>По будням</option><option>Раз в неделю</option><option>Несколько раз в день</option></select><span style={{fontSize:12,opacity:.6}}>Точное время можно выбрать после создания сотрудника.</span></label>
   </div>}
   <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginTop:16}}><span style={{fontSize:13,opacity:.62}}>Сначала создаётся черновик. Никакие внешние действия не выполняются автоматически при создании.</span><button onClick={()=>void createFromWizard()} disabled={!!busy||(advanced?description.trim().length<12:work.trim().length<12)} style={{padding:"11px 16px",border:0,borderRadius:11,fontWeight:700,cursor:"pointer"}}>{busy==="description"?"Создаём…":"Создать и показать карту"}</button></div>
  </section>
  <section style={{marginBottom:34}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,marginBottom:14}}><div><h2 style={{margin:0}}>Готовые сотрудники</h2><p style={{opacity:.65,margin:"6px 0 0"}}>Быстрый старт с уже собранной картой действий.</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14}}>{templates.map(item=><article key={item.slug} style={{border:"1px solid #ddd",borderRadius:18,padding:18}}><div style={{fontSize:12,opacity:.55,textTransform:"uppercase"}}>{item.role}</div><h3 style={{fontSize:21,margin:"8px 0"}}>{item.name}</h3><p style={{opacity:.7,minHeight:88}}>{item.objective}</p><button disabled={!!busy} onClick={()=>void create(item.slug)} style={{width:"100%",padding:"11px 14px",border:0,borderRadius:11,cursor:"pointer",fontWeight:700}}>{busy===item.slug?"Создаём…":"Нанять"}</button></article>)}</div></section>
  <section><div style={{marginBottom:14}}><h2 style={{margin:0}}>Мои агенты</h2><p style={{opacity:.65,margin:"6px 0 0"}}>Откройте сотрудника, настройте карту действий, лимиты и запустите задачу.</p></div>{!agents.length?<div style={{border:"1px dashed #bbb",borderRadius:18,padding:34,textAlign:"center",opacity:.7}}>Пока нет AI-сотрудников.</div>:<div style={{display:"grid",gap:10}}>{agents.map(agent=><article key={agent.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:16,border:"1px solid #ddd",borderRadius:16,padding:18}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:19}}>{agent.name}</strong><span style={{fontSize:12,padding:"4px 8px",borderRadius:999,border:"1px solid #ddd"}}>{statusLabel[agent.status]||agent.status}</span></div><div style={{opacity:.62,marginTop:5}}>{agent.role||"AI-сотрудник"} · {autonomyLabel[agent.autonomy]||agent.autonomy}</div><p style={{opacity:.72,marginBottom:0}}>{agent.objective||"Цель пока не задана"}</p></div><div style={{display:"flex",alignItems:"center"}}><Link href={`/app/agents/${agent.id}`} style={{textDecoration:"none",padding:"10px 13px",border:"1px solid #ddd",borderRadius:10}}>Открыть</Link></div></article>)}</div>}</section>
 </main>;
}
