"use client";

import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";
import type {FileAsset,Project} from "../../../lib/types";
import styles from "./projects.module.css";

const roleLabel:Record<string,string>={owner:"Владелец",editor:"Редактор",viewer:"Просмотр"};
const fileStatus:Record<string,string>={uploaded:"Загружен",processing:"Обрабатывается",ready:"Готов",partial:"Обработан частично",failed:"Ошибка",rejected:"Отклонён"};
type GithubInstallation={id:string;installation_id:number;account:string;repository_selection:string};
type GithubRepository={id:number;full_name:string;private:boolean;default_branch:string};
type GithubBinding={id:string;repository_id:number;full_name:string;default_branch:string;private:boolean;write_enabled:boolean;last_synced_at:string|null};
type GithubConnect={configured:boolean;connect_url:string|null};
type RepoOption={installationId:string;account:string;repo:GithubRepository};

export default function ProjectsPage(){
 const[projects,setProjects]=useState<Project[]>([]);const[files,setFiles]=useState<FileAsset[]>([]);const[editing,setEditing]=useState<Project|null>(null);const[creating,setCreating]=useState(false);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 const[githubConnect,setGithubConnect]=useState<GithubConnect|null>(null);const[githubInstallations,setGithubInstallations]=useState<GithubInstallation[]>([]);const[githubRepos,setGithubRepos]=useState<Record<string,GithubRepository[]>>({});const[githubBindings,setGithubBindings]=useState<Record<string,GithubBinding|null>>({});const[githubBusy,setGithubBusy]=useState<string|null>(null);const[githubLoading,setGithubLoading]=useState(true);const[githubError,setGithubError]=useState("");const[githubNotice,setGithubNotice]=useState("");const[repoChoice,setRepoChoice]=useState<Record<string,string>>({});
 const ownerProjects=projects.filter(project=>project.role==="owner"&&!project.archived_at);
 const repoOptions=useMemo<RepoOption[]>(()=>githubInstallations.flatMap(installation=>(githubRepos[installation.id]??[]).map(repo=>({installationId:installation.id,account:installation.account,repo}))),[githubInstallations,githubRepos]);

 const load=async()=>{
  setError("");setGithubLoading(true);setGithubError("");
  try{
   const[p,f]=await Promise.all([api<Project[]>("/projects/"),api<FileAsset[]>("/files/")]);setProjects(p);setFiles(f);
   const owned=p.filter(project=>project.role==="owner"&&!project.archived_at);
   try{
    const gc=await api<GithubConnect>("/github/connect/");setGithubConnect(gc);
    if(!gc.configured){setGithubInstallations([]);setGithubRepos({});setGithubBindings({});return}
    const gi=await api<GithubInstallation[]>("/github/installations/");setGithubInstallations(gi);
    const repoEntries=await Promise.all(gi.map(async installation=>[installation.id,await api<GithubRepository[]>(`/github/installations/${installation.id}/repositories/`)] as const));setGithubRepos(Object.fromEntries(repoEntries));
    const bindingEntries=await Promise.all(owned.map(async project=>{try{return [project.id,await api<GithubBinding>(`/projects/${project.id}/github/`)] as const}catch{return [project.id,null] as const}}));setGithubBindings(Object.fromEntries(bindingEntries));
   }catch(reason){setGithubError(reason instanceof Error?reason.message:"Не удалось проверить GitHub");}
  }catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить проекты")}
  finally{setGithubLoading(false)}
 };
 useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get("github")==="connected"){setGithubNotice("GitHub подключён. Теперь выберите репозиторий для нужного проекта.");params.delete("github");const query=params.toString();window.history.replaceState({},"",`${window.location.pathname}${query?`?${query}`:""}`)}void load()},[]);
 const filesByProject=useMemo(()=>{const map=new Map<string,FileAsset[]>();for(const file of files)map.set(file.project,[...(map.get(file.project)??[]),file]);return map},[files]);
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const payload={name:String(data.get("name")||"").trim(),description:String(data.get("description")||"").trim(),instruction:String(data.get("instruction")||"")};if(!payload.name)return;setBusy(true);setError("");try{if(editing)await api(`/projects/${editing.id}/`,{method:"PATCH",body:JSON.stringify(payload)});else await api("/projects/",{method:"POST",body:JSON.stringify(payload)});setEditing(null);setCreating(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось сохранить проект")}finally{setBusy(false)}};
 const archive=async(project:Project)=>{if(!window.confirm(`Архивировать проект «${project.name}»?`))return;try{await api(`/projects/${project.id}/`,{method:"DELETE"});await load()}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось архивировать проект")}};
 const restore=async(project:Project)=>{try{await api(`/projects/${project.id}/restore/`,{method:"POST"});await load()}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось восстановить проект")}};
 const bindRepo=async(project:Project)=>{const selected=repoChoice[project.id];if(project.role!=="owner"||!selected)return;const[installationId,repositoryId]=selected.split(":");if(!installationId||!repositoryId)return;setGithubBusy(`project:${project.id}`);setGithubError("");try{const binding=await api<GithubBinding>(`/projects/${project.id}/github/`,{method:"POST",body:JSON.stringify({installation:installationId,repository_id:Number(repositoryId)})});setGithubBindings(current=>({...current,[project.id]:binding}));setGithubNotice(`Репозиторий ${binding.full_name} подключён к проекту «${project.name}».`)}catch(reason){setGithubError(reason instanceof Error?reason.message:"Не удалось подключить репозиторий")}finally{setGithubBusy(null)}};
 const toggleWrite=async(project:Project,binding:GithubBinding)=>{if(project.role!=="owner")return;const next=!binding.write_enabled;if(next&&!window.confirm("Разрешить Dev Studio создавать изменения в этом репозитории? Опасные действия и запись по-прежнему требуют защитных проверок."))return;setGithubBusy(`project:${project.id}`);setGithubError("");try{const result=await api<{write_enabled:boolean}>(`/projects/${project.id}/github/`,{method:"PATCH",body:JSON.stringify({write_enabled:next})});setGithubBindings(current=>({...current,[project.id]:{...binding,write_enabled:result.write_enabled}}));setGithubNotice(result.write_enabled?"Dev Studio получила разрешение на безопасную запись в репозиторий.":"Изменение кода из Dev Studio отключено.")}catch(reason){setGithubError(reason instanceof Error?reason.message:"Не удалось изменить доступ GitHub")}finally{setGithubBusy(null)}};

 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.top}><div><h1>Проекты</h1><p>Контекст, файлы и код проекта в одном месте. Технические настройки можно оставить системе.</p></div><Link href="/app">← Рабочее пространство</Link></header>
  {error&&<div className={styles.notice} role="alert">{error}</div>}{githubError&&<div className={styles.notice} role="alert"><b>GitHub:</b> {githubError} <button className={styles.button} onClick={()=>void load()} disabled={githubLoading}>Проверить снова</button></div>}{githubNotice&&<div className={styles.notice}>{githubNotice}</div>}
  <div className={styles.toolbar}><button className={`${styles.button} ${styles.primary}`} onClick={()=>{setCreating(true);setEditing(null)}}>Новый проект</button></div>

  {ownerProjects.length>0&&<section className={styles.card} style={{marginBottom:12}} aria-label="Подключение GitHub"><div className={styles.cardHead}><div><h2>GitHub для Dev Studio</h2><p>Один раз подключите аккаунт, затем выберите репозиторий у нужного проекта.</p></div><small>{githubLoading?"Проверяем…":githubConnect?.configured?(githubInstallations.length?"Подключён":"Нужен вход"):"Недоступен"}</small></div>
   {githubLoading?<div className={styles.instruction}>Проверяем подключение GitHub…</div>:!githubConnect?.configured?<div className={styles.instruction}><b>GitHub пока не настроен на сервере.</b><div>Чаты, файлы и проекты продолжат работать, но Dev Studio не сможет читать и изменять код. Администратору нужно включить GitHub App в конфигурации сервиса.</div></div>:githubInstallations.length===0?<div className={styles.instruction}><b>Шаг 1 из 2 · подключите GitHub</b><div>Откроется официальный GitHub. Вы сами выбираете, к каким репозиториям дать доступ приложению.</div>{githubConnect.connect_url&&<div className={styles.actions} style={{marginTop:10}}><a className={`${styles.button} ${styles.primary}`} href={githubConnect.connect_url}>Подключить GitHub</a></div>}</div>:<div className={styles.instruction}><b>GitHub подключён</b><div>{githubInstallations.map(item=>item.account).join(", ")} · доступно репозиториев: {repoOptions.length}</div><div className={styles.actions} style={{marginTop:10}}>{githubConnect.connect_url&&<a className={styles.button} href={githubConnect.connect_url}>Изменить доступ в GitHub</a>}<button className={styles.button} onClick={()=>void load()} disabled={githubLoading}>Обновить список</button></div></div>}
  </section>}

  {(creating||editing)&&<section className={styles.card} style={{marginBottom:12}}><form className={styles.form} onSubmit={save}><input name="name" defaultValue={editing?.name??""} placeholder="Название проекта" required/><textarea name="description" defaultValue={editing?.description??""} placeholder="Короткое описание"/><textarea name="instruction" defaultValue={editing?.active_instruction??""} placeholder="Что AI должен учитывать при работе с этим проектом"/><div className={styles.actions}><button type="button" className={styles.button} onClick={()=>{setCreating(false);setEditing(null)}}>Отмена</button><button className={`${styles.button} ${styles.primary}`} disabled={busy}>{busy?"Сохраняем…":"Сохранить"}</button></div></form></section>}

  <section className={styles.grid}>{projects.map(project=>{const projectFiles=filesByProject.get(project.id)??[];const binding=project.role==="owner"?(githubBindings[project.id]??null):null;return <article key={project.id} className={`${styles.card} ${project.archived_at?styles.archived:""}`}><div className={styles.cardHead}><div><h2>{project.name}</h2><p>{project.description||"Без описания"}</p></div><small>{roleLabel[project.role]??"Участник"}</small></div>{project.active_instruction&&<div className={styles.instruction}>{project.active_instruction}</div>}<div className={styles.meta}><span>{projectFiles.length} файлов</span><span>обновлён {new Date(project.updated_at).toLocaleDateString("ru-RU")}</span></div>{projectFiles.length>0&&<div className={styles.files}>{projectFiles.slice(0,5).map(file=><div className={styles.file} key={file.id}><span>{file.original_name}</span><small>{fileStatus[file.status]??"Обрабатывается"}</small></div>)}</div>}
   {!project.archived_at&&project.role==="owner"&&githubConnect?.configured&&<div className={styles.instruction} style={{marginTop:12}}><b>Код проекта</b>{binding?<><div>{binding.full_name} · {binding.default_branch}</div><div className={styles.actions} style={{marginTop:8}}><Link className={styles.button} href="/app/dev">Открыть Dev Studio</Link><button className={styles.button} disabled={githubBusy===`project:${project.id}`} onClick={()=>void toggleWrite(project,binding)}>{binding.write_enabled?"Отключить изменения":"Разрешить Dev Studio"}</button><details><summary style={{cursor:"pointer"}}>Для разработчиков</summary><div style={{marginTop:8}}><Link className={styles.button} href={`/app/projects/${project.id}/github`}>Открыть файлы GitHub</Link></div></details></div><small>{binding.write_enabled?"Dev Studio может подготавливать изменения с защитными проверками.":"Сейчас доступно только чтение кода."}</small></>:githubInstallations.length>0?<div style={{marginTop:8}}><label style={{display:"grid",gap:6}}><span>Шаг 2 из 2 · выберите репозиторий</span><select value={repoChoice[project.id]??""} onChange={event=>setRepoChoice(current=>({...current,[project.id]:event.target.value}))}><option value="">Выберите репозиторий…</option>{repoOptions.map(option=><option key={`${option.installationId}:${option.repo.id}`} value={`${option.installationId}:${option.repo.id}`}>{option.repo.full_name}{githubInstallations.length>1?` · ${option.account}`:""}</option>)}</select></label><div className={styles.actions} style={{marginTop:8}}><button className={`${styles.button} ${styles.primary}`} disabled={!repoChoice[project.id]||githubBusy===`project:${project.id}`} onClick={()=>void bindRepo(project)}>{githubBusy===`project:${project.id}`?"Подключаем…":"Подключить репозиторий"}</button></div></div>:<div>Сначала подключите GitHub в блоке выше.</div>}</div>}
   {!project.archived_at&&project.role!=="owner"&&<div className={styles.instruction} style={{marginTop:12}}>Настройки GitHub доступны только владельцу проекта.</div>}
   <div className={styles.actions}>{!project.archived_at&&project.role!=="viewer"&&<><Link className={`${styles.button} ${styles.primary}`} href={`/app?project=${project.id}`}>Открыть проект</Link><button className={styles.button} onClick={()=>{setEditing(project);setCreating(false)}}>Настройки</button><button className={styles.button} onClick={()=>void archive(project)}>В архив</button></>}{project.archived_at&&project.role!=="viewer"&&<button className={styles.button} onClick={()=>void restore(project)}>Восстановить</button>}</div></article>})}</section>
 </div></main>
}
