export type WorkflowNode={id:string;title:string;type:string;position?:{x:number;y:number};prompt?:string;selected_model?:string;url?:string;connection_id?:string;method?:string;path?:string;body?:unknown;on_true?:string;on_false?:string;condition_source?:string;operator?:string;value?:string;wait_minutes?:number;message?:string;status?:string;[key:string]:unknown};
export type WorkflowGraph={version?:number;routing?:string;nodes?:WorkflowNode[];edges?:Array<{from:string;to:string}>};
export const workflowTypes=[['llm','AI-задача'],['search','Поиск в интернете'],['browser','Браузер: прочитать сайт'],['http','HTTP API / интеграция'],['condition','Условие'],['approval','Согласование'],['wait','Ожидание'],['notify','Уведомление'],['publish','WordPress'],['files','Файлы проекта'],['image','Изображение'],['review','Проверка AI'],['finish','Завершение']] as const;
export const llmTypes=new Set(['llm','research','web','files','review','analytics']);
export const typeLabel=(type:string)=>workflowTypes.find(row=>row[0]===type)?.[1]??type;
export function graphLinks(graph:WorkflowGraph){const nodes=graph.nodes??[],edges=graph.edges??[];return (graph.routing==='explicit'?edges:nodes.slice(0,-1).map((node,i)=>edges.find(edge=>edge.from===node.id)??{from:node.id,to:nodes[i+1].id})).filter(edge=>nodes.find(node=>node.id===edge.from)?.type!=='finish')}
export function orderedGraph(graph:WorkflowGraph):WorkflowGraph{
 const nodes=graph.nodes??[],ids=new Set(nodes.map(node=>node.id));const links=[...(graph.edges??[]),...nodes.flatMap(node=>node.type==='condition'?[node.on_true,node.on_false].filter(Boolean).map(to=>({from:node.id,to:String(to)})):[])];const incoming=new Map(nodes.map(node=>[node.id,0])),next=new Map<string,Set<string>>();
 for(const edge of links){if(!ids.has(edge.from)||!ids.has(edge.to))throw Error('Связь ведёт к отсутствующему узлу');if(edge.from===edge.to)throw Error('Узел нельзя соединить с собой');const targets=next.get(edge.from)??new Set<string>();if(!targets.has(edge.to)){targets.add(edge.to);incoming.set(edge.to,incoming.get(edge.to)!+1)}next.set(edge.from,targets)}
 const pending=[...nodes],result:WorkflowNode[]=[];while(pending.length){const index=pending.findIndex(node=>incoming.get(node.id)===0);if(index<0)throw Error('Эта связь создаёт цикл');const [node]=pending.splice(index,1);result.push(node);for(const target of next.get(node.id)??[])incoming.set(target,incoming.get(target)!-1)}if(nodes.length&&result[0]?.id!==nodes[0].id)throw Error('Начальный узел не может иметь входящую связь');return {...graph,nodes:result,routing:'explicit'};
}

export async function workflowPlannerKey(description:string,agentId='new') {const bytes=new TextEncoder().encode(JSON.stringify({description,agent:agentId}));const digest=await crypto.subtle.digest('SHA-256',bytes);return 'agent-plan:'+Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,'0')).join('');}
