"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../lib/api";
import styles from "./usage.module.css";

type Period={requests:number;cost_rub:string;input_tokens:number;output_tokens:number};type ModelRow={routed_model:string;requests:number;cost_rub:string;input_tokens:number;output_tokens:number};type Day={day:string;requests:number;cost_rub:string;input_tokens:number;output_tokens:number};type Usage={today:Period;seven_days:Period;thirty_days:Period;by_model:ModelRow[];daily:Day[]};
const money=(value:string|number)=>`${Number(value).toFixed(2).replace(".",",")} ₽`;const tokens=(value:number)=>new Intl.NumberFormat("ru-RU",{notation:value>9999?"compact":"standard",maximumFractionDigits:1}).format(value);
export default function UsagePage(){const[data,setData]=useState<Usage|null>(null);const[error,setError]=useState("");useEffect(()=>{api<Usage>("/auth/usage/").then(setData).catch(reason=>setError(reason instanceof Error?reason.message:"Не удалось загрузить статистику"))},[]);const maxDay=useMemo(()=>Math.max(1,...(data?.daily.map(x=>Number(x.cost_rub))??[1])),[data]);const total=Number(data?.thirty_days.cost_rub??0);return <main className={styles.page}><div className={styles.shell}><header className={styles.top}><div><h1>Использование</h1><p>Ваши расходы, запросы и токены. Без технической перегрузки.</p></div><Link href="/app">← Workspace</Link></header>{error&&<div className={styles.section}>{error}</div>}{!data?<div className={styles.empty}>Загрузка…</div>:<><section className={styles.grid}><div className={styles.card}><small>Сегодня</small><strong>{money(data.today.cost_rub)}</strong><span>{data.today.requests} запросов · {tokens(data.today.input_tokens+data.today.output_tokens)} токенов</span></div><div className={styles.card}><small>7 дней</small><strong>{money(data.seven_days.cost_rub)}</strong><span>{data.seven_days.requests} запросов · {tokens(data.seven_days.input_tokens+data.seven_days.output_tokens)} токенов</span></div><div className={styles.card}><small>30 дней</small><strong>{money(data.thirty_days.cost_rub)}</strong><span>{data.thirty_days.requests} запросов · {tokens(data.thirty_days.input_tokens+data.thirty_days.output_tokens)} токенов</span></div></section><section className={styles.two}><div className={styles.section}><h2>Расход за 30 дней</h2>{data.daily.length?<div className={styles.bars}>{Array.from({length:30},(_,index)=>{const item=data.daily[Math.max(0,data.daily.length-30)+index];const height=item?Math.max(3,Number(item.cost_rub)/maxDay*100):2;return <div key={index} className={styles.bar} style={{height:`${height}%`}} title={item?`${item.day}: ${money(item.cost_rub)}`:"Нет расходов"}/>})}</div>:<div className={styles.empty}>Расходов пока нет.</div>}</div><div className={styles.section}><h2>По моделям</h2><div className={styles.models}>{data.by_model.length?data.by_model.map(row=>{const share=total?Number(row.cost_rub)/total*100:0;return <div key={row.routed_model||"unknown"} className={styles.modelRow}><b>{row.routed_model||"Не указана"}</b><span>{money(row.cost_rub)}</span><small>{row.requests} запросов · {tokens(row.input_tokens+row.output_tokens)} токенов</small><div className={styles.track}><div className={styles.fill} style={{width:`${Math.max(1,share)}%`}}/></div></div>}):<div className={styles.empty}>Данных пока нет.</div>}</div></div></section></>}</div></main>}
